Repository influxdata/influxdb, pull requests merged in 2018-04, with the labels that each got.

#9666 Update the interface for the simplified call valuer
  Godeps
  Gopkg.lock
  Gopkg.toml
  query/cursor.go
  query/math.go
Labels: review

#9670 Add adjustable TSI log file size.
  etc/config.sample.toml
  tsdb/config.go
  tsdb/index/tsi1/index.go
  tsdb/index/tsi1/partition.go
Labels: kind/enhancement, needs-backport/1.5, review

#9672 [1.5] Adjustable TSI Compaction Threshold
  etc/config.sample.toml
  tsdb/config.go
  tsdb/index/tsi1/index.go
  tsdb/index/tsi1/partition.go
Labels: kind/enhancement, review

#9673 Update explain analyze to output data related to the iterator scanners
  query/select.go
Labels: review

#9676 Ensure that conditions are encoded correctly even if the AST is not properly formed
  query/iterator.go
  query/iterator_test.go
Labels: review

#9679 Check for root user when running buildtsi.
  cmd/influx_inspect/buildtsi/buildtsi.go
Labels: kind/enhancement, needs-backport/1.5, review

#9632 Implement floor, ceil, and round functions
  query/math.go
Labels: kind/feature request, proposed

#9399 Allow customizing the unix socket group and permissions created by the server
  services/httpd/config.go
  services/httpd/service.go
  toml/toml.go
  toml/toml_test.go
Labels: kind/feature request, review

#9684 Fix stream package to allow for renaming the file before writing it to the stream
  pkg/tar/stream.go
  tests/backup_restore_test.go
  tsdb/engine/tsm1/engine.go
Labels: kind/bug, review

#9687 Fix panic in readTombstoneV4
  tsdb/engine/tsm1/tombstone.go
  tsdb/engine/tsm1/tombstone_test.go
Labels: review

#9680 Check for root user when running buildtsi.
  cmd/influx_inspect/buildtsi/buildtsi.go
Labels: kind/enhancement, kind/feature request

#9682 Avoid a panic when using show diagnostics with text/csv
  services/httpd/response_writer.go
  services/httpd/response_writer_test.go
Labels: kind/bug, review

#9686 Adding additional aggregate benchmarks for tsm1
  tsdb/engine/tsm1/engine_test.go
Labels: review

#9699 Return time range from delete predicate func
  tsdb/engine.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
  tsdb/shard.go
Labels: review

#9696 Properly track the response bytes written for queries in all format types
  services/httpd/response_writer.go
  services/httpd/response_writer_test.go
Labels: kind/bug, review

#9689 Tar stream fix for backup error #9613
  pkg/tar/stream.go
  tests/backup_restore_test.go
  tsdb/engine/tsm1/engine.go
Labels: kind/bug, review

#9705 Check for errors from binary.Uvarint when reading TSI logs
  tsdb/index/tsi1/log_file.go
  tsdb/index/tsi1/measurement_block.go
  tsdb/index/tsi1/tag_block.go
  tsdb/index/tsi1/tag_block_test.go
  tsdb/index/tsi1/tsi1.go
Labels: area/storage, kind/bug, review

#9712 Changed file download retry rate to have exponential wait times
  cmd/influxd/backup/backup.go
Labels: kind/bug, review

#9714 SHOW SERIES hangs
  tsdb/index.go
Labels: review

#9711 update CircleCI config to 2.0 syntax
  .circleci/config.yml
  .gitignore
  CONTRIBUTING.md
  circle-test.sh
  circle.yml
  services/subscriber/service_test.go
Labels: area/tests, flaky test, kind/bug, review

#9710 Update client README - close client resources
  client/README.md
Labels: proposed

#9620 Add more math functions to influxql
  query/compile.go
  query/compile_test.go
  query/math.go
Labels: kind/feature request, review

#9737 Respect rp parameter in /query
  coordinator/statement_executor.go
  coordinator/statement_executor_test.go
  query/executor.go
  services/httpd/handler.go
Labels: kind/feature request, review

#9743 Add 'influx_inspect deletetsm'
  cmd/influx_inspect/deletetsm/deletetsm.go
  cmd/influx_inspect/help/help.go
  cmd/influx_inspect/main.go
Labels: review

#9615 Remove error for series file when no shards exist
  tsdb/shard.go
Labels: kind/bug, review

#9028 Fix linting on cmd files
  cmd/influx/cli/cli.go
  cmd/influx_inspect/report/report.go
  cmd/influx_tsm/tsdb/database.go
  cmd/influx_tsm/tsdb/internal/meta.pb.go
  cmd/influxd/run/server.go
  cmd/store/query/query.go
Labels: proposed

#9757 Add suppress-write-log option to disable the write log when the log is enabled
  etc/config.sample.toml
  services/httpd/config.go
  services/httpd/handler.go
  services/httpd/handler_test.go
Labels: kind/feature request, review

#9751 Fix the validation for multiple nested distinct calls
  query/compile.go
  query/compile_test.go
Labels: kind/bug, needs-backport/1.5, review

#9260 Add additional technical analysis algorithms
  query/call_iterator.go
  query/compile.go
  query/functions.go
  query/internal/gota/README.md
  query/internal/gota/cmo.go
  query/internal/gota/cmo_test.go
  query/internal/gota/ema.go
  query/internal/gota/ema_test.go
  query/internal/gota/kama.go
  query/internal/gota/kama_test.go
  query/internal/gota/rsi.go
  query/internal/gota/rsi_test.go
  query/internal/gota/trix.go
  query/internal/gota/trix_test.go
  query/internal/gota/utils_test.go
  query/select.go
Labels: kind/feature request, proposed

#9758 HLL++: estimate memory footprint bytes
  pkg/estimator/hll/hll.go
  pkg/estimator/hll/hll_test.go
Labels: kind/refactor, review

#9713 Update backup flags to have long/short versions
  cmd/influxd/backup/backup.go
  cmd/influxd/restore/restore.go
  man/influxd-backup.txt
  man/influxd-restore.txt
  tests/backup_restore_test.go
Labels: kind/feature request, review

#9769 fix flaky subscriber tests
  services/subscriber/service_test.go
Labels: review

#9761 Fix tsdb/index/inmem benchmark tests
  tsdb/index/inmem/inmem_test.go
Labels: kind/bug, review

#9752 Command line tool to import binary format data
  cmd/influx-tools/importer/README.md
  cmd/influx-tools/importer/command.go
  cmd/influx-tools/importer/importer.go
  cmd/influx-tools/importer/series_writer.go
  cmd/influx-tools/importer/shard_writer.go
  cmd/influx-tools/internal/errlist/errlist.go
  cmd/influx-tools/internal/format/binary/reader.go
  cmd/influx-tools/internal/format/binary/reader_test.go
  cmd/influx-tools/internal/tlv/tlv.go
  cmd/influx-tools/main.go
  cmd/influx-tools/server/server.go
Labels: review

#9777 Log information about index version during startup
  tsdb/shard.go
  tsdb/store.go
Labels: kind/feature request, review

#9778 Include the query task status in the QueryInfo struct
  query/task_manager.go
Labels: review

#9783 tsm1: Replace goroutine `merge` with k-way merge
  tsdb/engine/tsm1/digest.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
  tsdb/engine/tsm1/file_store_internal_test.go
Labels: review

#9781 tsdb/indx/inmem: Fix megacheck issue
  tsdb/index/inmem/inmem_test.go
Labels: area/storage, kind/bug, review

#9785 Rename & log corrupt tsm files on load
  cmd/influx_inspect/deletetsm/deletetsm.go
  tsdb/engine/tsm1/file_store.go
Labels: review

#9793 Add key sanitization to deletetsm
  cmd/influx_inspect/deletetsm/deletetsm.go
  models/points.go
Labels: kind/feature request, review
