Repository influxdata/influxdb, pull requests merged in 2018-11, with the labels that each got.

#10443 chore: update revisions of flux and influxql
  CHANGELOG.md
  Godeps
  Gopkg.lock
Labels: review

#10444 chore(deps): Update platform and flux
  Gopkg.lock
Labels: review

#10445 Remove flaky CLI tests
  cmd/influx/cli/cli_test.go
Labels: flaky test, review

#10446 Gs 1.7 db
  Gopkg.lock
Labels: review

#10449 Improve APIs to increase reuse in Enterprise
  cmd/influxd/run/server.go
  flux/control/controller.go
  flux/functions/inputs/buckets.go
  services/httpd/handler.go
  services/httpd/handler_test.go
  services/httpd/service.go
Labels: review

#10391 Reduce allocations for high measurement writes
  tsdb/shard.go
  tsdb/shard_test.go
Labels: review

#10454 Update Flux and Platform dependencies
  Gopkg.lock
Labels: review

#10437 Don't use fmt.Errorf on random strings
  client/v2/client.go
Labels: proposed

#9943 Some typo and Wrong position of comment
  models/points.go
  tsdb/engine/tsm1/engine.go
Labels: proposed

#10455 Update changelog
  CHANGELOG.md
Labels: review

#10457 Update flux and platform dependencies
  Gopkg.lock
Labels: review

#10458 Update flux dep constraint to 0.7.0
  Gopkg.lock
  Gopkg.toml
Labels: review

#10460 Release date update
  CHANGELOG.md
  Gopkg.lock
Labels: review

#10461 Added missing release notes
  CHANGELOG.md
Labels: review

#10472 Fix empty results when using _value in filter expression
  services/storage/series_cursor.go
  services/storage/series_cursor_test.go
Labels: needs-backport/1.7, review

#10474 Fix go:generate line to refer to correct proto file
  services/storage/gen.go
  services/storage/source.pb.go
Labels: needs-backport/1.7, review

#10483 chore: changelog updates
  CHANGELOG.md
  Gopkg.lock
Labels: review

#10494 Fix ApplyEnvOverrides when a type that implements Unmarshaler is in a slice
  toml/toml.go
  toml/toml_test.go
Labels: kind/bug, needs-backport/1.7, review

#10499 Fix ApplyEnvOverrides when a type that implements Unmarshaler is in a slice
  toml/toml.go
  toml/toml_test.go
Labels: kind/bug, review

#10508 fix verify seriesfile in presence of tombstones
  cmd/influx_inspect/verify/seriesfile/verify.go
Labels: needs-backport/1.7, review

#10514 Backport fix verify seriesfile in presence of tombstones
  cmd/influx_inspect/verify/seriesfile/verify.go
Labels: review

#10523 Remove "Verbose" option from controller.Config
  flux/control/controller.go
Labels: review

#10509 tsdb: don't allow deletes to a database in mixed index mode
  tsdb/store.go
Labels: review

#10517 tsdb: clean up fields index for every kind of delete
  tsdb/engine/tsm1/engine.go
  tsdb/index.go
  tsdb/index/inmem/inmem.go
  tsdb/index/inmem/inmem_test.go
  tsdb/index/tsi1/index.go
Labels: review

#10525 Skip and warn series files in retention policy directory.
  tsdb/store.go
Labels: area/storage, review

#10526 Backport: don't allow deletes to a database in mixed index mode
  tsdb/store.go
Labels: review

#10527 Backport: always cleaning up the fields index
  tsdb/engine/tsm1/engine.go
  tsdb/index.go
  tsdb/index/inmem/inmem.go
  tsdb/index/inmem/inmem_test.go
  tsdb/index/tsi1/index.go
Labels: review

#10528 Skip and warn series files in retention policy directory.
  tsdb/store.go
Labels: area/storage, review

#10516 tsdb: conflict based concurrency resolution
  tsdb/epoch_tracker.go
  tsdb/epoch_tracker_test.go
  tsdb/guard.go
  tsdb/guard_test.go
  tsdb/store.go
Labels: review

#10531 tsdb: conflict based concurrency resolution
  tsdb/epoch_tracker.go
  tsdb/epoch_tracker_test.go
  tsdb/guard.go
  tsdb/guard_test.go
  tsdb/store.go
Labels: review

#10530 Update to Flux 0.7.1
  Gopkg.lock
  Gopkg.toml
  cmd/influx_tools/internal/format/binary/reader_test.go
  cmd/influx_tools/internal/format/binary/writer_test.go
  flux/functions/inputs/buckets.go
  internal/array_cursors.go
  internal/storage_store.go
  services/httpd/handler.go
  tsdb/cursor.go
  tsdb/engine/tsm1/array_cursor.gen.go
  tsdb/engine/tsm1/array_cursor.gen.go.tmpl
  tsdb/engine/tsm1/array_cursor_iterator.go
Labels: needs-backport/1.7, review
