Repository influxdata/influxdb, pull requests merged in 2018-08, with the labels that each got.

#10150 Allow specifying some TLS configuration.
  client/influxdb.go
  cmd/influxd/run/config.go
  cmd/influxd/run/config_test.go
  cmd/influxd/run/server.go
  etc/config.sample.toml
  pkg/tlsconfig/tls_config.go
  services/httpd/config.go
  services/httpd/service.go
  services/opentsdb/config.go
  services/opentsdb/service.go
  services/subscriber/config.go
  services/subscriber/http.go
  services/subscriber/service.go
Labels: review

#10154 Provide configurable TLS options
  client/influxdb.go
  cmd/influxd/run/config.go
  cmd/influxd/run/config_test.go
  cmd/influxd/run/server.go
  etc/config.sample.toml
  pkg/tlsconfig/tls_config.go
  services/httpd/config.go
  services/httpd/service.go
  services/opentsdb/config.go
  services/opentsdb/service.go
  services/subscriber/config.go
  services/subscriber/http.go
  services/subscriber/service.go
Labels: kind/feature request, review

#10152 Add option to hint MADV_WILLNEED to kernel
  etc/config.sample.toml
  tsdb/config.go
  tsdb/config_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
  tsdb/engine/tsm1/mmap_unix.go
  tsdb/engine/tsm1/mmap_windows.go
  tsdb/engine/tsm1/reader.go
Labels: area/configuration, area/tsm, kind/feature request, review

#10155 Add option to hint MADV_WILLNEED to kernel
  etc/config.sample.toml
  tsdb/config.go
  tsdb/config_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
  tsdb/engine/tsm1/mmap_unix.go
  tsdb/engine/tsm1/mmap_windows.go
  tsdb/engine/tsm1/reader.go
Labels: kind/feature request, review

#10113 Add digest manifest
  Gopkg.lock
  tsdb/engine/tsm1/digest.go
  tsdb/engine/tsm1/digest_reader.go
  tsdb/engine/tsm1/digest_test.go
  tsdb/engine/tsm1/digest_writer.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
Labels: needs-backport/1.6, review

#10156 Add digest manifest
  tsdb/engine/tsm1/digest.go
  tsdb/engine/tsm1/digest_reader.go
  tsdb/engine/tsm1/digest_test.go
  tsdb/engine/tsm1/digest_writer.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
Labels: review

#10157 updated the release date for 1.6.1
  CHANGELOG.md
Labels: review

#10161 Simplify loops
  coordinator/points_writer_test.go
  services/meta/data.go
  tsdb/engine/tsm1/engine_test.go
  tsdb/store.go
Labels: review

#10163 updated influxql sha to the latest
  Godeps
Labels: review

#10164 influx_inspect: Make buildtsi code resusable
  cmd/influx_inspect/buildtsi/buildtsi.go
Labels: review

#10166 tsdb: Cleanup compaction throughput code
  tsdb/store.go
Labels: review

#10173 test(stress): Fix flaky test
  stress/stress_test.go
Labels: flaky test, review

#10172 Fix iterator panic in read service
  tsdb/index.go
Labels: review

#10184 backport SHOW MEASUREMENTS panic fix
  pkg/slices/bytes.go
  pkg/slices/bytes_test.go
  tsdb/index.go
Labels: review

#10187 updated CHANGELOG with PR 10184
  CHANGELOG.md
Labels: review

#10186 [Experimental] TSI Series ID set caching
  CHANGELOG.md
  Godeps
  Gopkg.lock
  Gopkg.toml
  LICENSE_OF_DEPENDENCIES.md
  tsdb/index.go
  tsdb/index/tsi1/cache.go
  tsdb/index/tsi1/cache_test.go
  tsdb/index/tsi1/index.go
  tsdb/index/tsi1/index_file.go
  tsdb/index/tsi1/index_test.go
  tsdb/index/tsi1/log_file.go
  tsdb/index/tsi1/log_file_test.go
  tsdb/index/tsi1/partition.go
  tsdb/index/tsi1/testdata/index-file-index/0/L0-00000002.tsl
  tsdb/index/tsi1/testdata/index-file-index/0/L1-00000001.tsi
  tsdb/index/tsi1/testdata/index-file-index/0/MANIFEST
  tsdb/index/tsi1/testdata/index-file-index/1/L0-00000002.tsl
  tsdb/index/tsi1/testdata/index-file-index/1/L1-00000001.tsi
  tsdb/index/tsi1/testdata/index-file-index/1/MANIFEST
  tsdb/index/tsi1/testdata/index-file-index/2/L0-00000002.tsl
  tsdb/index/tsi1/testdata/index-file-index/2/L1-00000001.tsi
  tsdb/index/tsi1/testdata/index-file-index/2/MANIFEST
  tsdb/index/tsi1/testdata/index-file-index/3/L0-00000002.tsl
  tsdb/index/tsi1/testdata/index-file-index/3/L1-00000001.tsi
  tsdb/index/tsi1/testdata/index-file-index/3/MANIFEST
  tsdb/index/tsi1/testdata/index-file-index/4/L0-00000002.tsl
  tsdb/index/tsi1/testdata/index-file-index/4/L1-00000001.tsi
  tsdb/index/tsi1/testdata/index-file-index/4/MANIFEST
  tsdb/index/tsi1/testdata/index-file-index/5/L0-00000002.tsl
  tsdb/index/tsi1/testdata/index-file-index/5/L1-00000001.tsi
  tsdb/index/tsi1/testdata/index-file-index/5/MANIFEST
  tsdb/index/tsi1/testdata/index-file-index/6/L0-00000002.tsl
  tsdb/index/tsi1/testdata/index-file-index/6/L1-00000001.tsi
  tsdb/index/tsi1/testdata/index-file-index/6/MANIFEST
  tsdb/index/tsi1/testdata/index-file-index/7/L0-00000002.tsl
  tsdb/index/tsi1/testdata/index-file-index/7/L1-00000001.tsi
  tsdb/index/tsi1/testdata/index-file-index/7/MANIFEST
  tsdb/index_test.go
  tsdb/series_file.go
  tsdb/series_file_test.go
  tsdb/series_partition.go
  tsdb/series_set.go
  tsdb/series_set_test.go
  tsdb/testdata/line-protocol-1M.txt.gz
Labels: review

#10188 feat(tsdb): Add CursorType to enable selection of batch cursors
  tsdb/cursor.go
  tsdb/engine/tsm1/engine_cursor.go
Labels: area/storage, review

#10181 Fix line protocol parsing panic
  models/points.go
  models/points_test.go
Labels: kind/bug, needs-backport/1.6, review

#10149 Run dep ensure with dep 0.5.0
  Gopkg.lock
Labels: review

#10190 Reduce allocations in TSI TagSets implementation
  tsdb/index.go
  tsdb/index_test.go
  tsdb/series_file.go
  tsdb/series_file_test.go
  tsdb/testdata/line-protocol-1M.txt.gz
Labels: area/tsi, kind/feature request, needs-backport/1.6, performance, review

#10191 Code Issues 759 Pull requests 37 Projects 0 Wiki Insights Settings Reduce allocations in TSI TagSets implementation
  tsdb/index.go
  tsdb/index_test.go
  tsdb/series_file.go
  tsdb/series_file_test.go
  tsdb/testdata/line-protocol-1M.txt.gz
Labels: kind/feature request, review

#9978 Minor fix for legacy restore
  cmd/influxd/restore/restore.go
Labels: proposed

#10197 pkg/snowflake: reduce contention in Next calls
  pkg/snowflake/gen.go
  pkg/snowflake/gen_test.go
Labels: review

#10202 pkg/snowflake: be more robust against sequence rollover
  pkg/snowflake/gen.go
  pkg/snowflake/gen_test.go
Labels: review

#10201 pkg/snowflake: update platform branch.
  pkg/snowflake/gen.go
  pkg/snowflake/gen_test.go
Labels: review

#10209 fix the comments error
  pkg/limiter/writer.go
Labels: proposed

#9801 Add option for unicode validation.
  etc/config.sample.toml
  tsdb/config.go
  tsdb/shard.go
Labels: review

#10200 httpd/meta: use open auth when unrestricted
  services/httpd/handler.go
  services/meta/data.go
Labels: review

#10213 Test InfluxDB on Go 1.11rc1
  Dockerfile_build_ubuntu64_go1.11
  coordinator/meta_client_test.go
  releng/_go_versions.sh
  services/continuous_querier/service_test.go
  services/retention/service_test.go
  services/snapshotter/service_test.go
Labels: review

#10212 Ensure orhpaned series cleaned up with shard drop
  tsdb/config.go
  tsdb/config_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
  tsdb/index.go
  tsdb/index/inmem/inmem.go
  tsdb/index/tsi1/index.go
  tsdb/index_test.go
  tsdb/shard_internal_test.go
  tsdb/shard_test.go
  tsdb/store.go
  tsdb/store_test.go
Labels: kind/bug, needs-backport/1.5, needs-backport/1.6, review

#10217 fix(tsm1): return boolean iterator for booleans
  tsdb/engine/tsm1/cursor_iterator.go
Labels: review

#10222 fix(tsm1): Fix panic when calling Close multiple times on a descending cursor.
  tsdb/engine/tsm1/array_cursor.gen.go
  tsdb/engine/tsm1/array_cursor.gen.go.tmpl
Labels: area/storage, review

#10219 Ensure orhpaned series cleaned up with shard drop
  tsdb/config.go
  tsdb/config_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
  tsdb/index.go
  tsdb/index/inmem/inmem.go
  tsdb/index/tsi1/index.go
  tsdb/index_test.go
  tsdb/shard_internal_test.go
  tsdb/shard_test.go
  tsdb/store.go
  tsdb/store_test.go
Labels: kind/bug, review

#10220 Reduce allocations in TSI TagSets implementation
  cmd/store/query/query.go
  coordinator/points_writer_test.go
  services/meta/data.go
  tsdb/engine/tsm1/cache_race_test.go
  tsdb/engine/tsm1/engine_test.go
  tsdb/index.go
  tsdb/index_test.go
  tsdb/series_file.go
  tsdb/series_file_test.go
  tsdb/store.go
  tsdb/testdata/line-protocol-1M.txt.gz
Labels: kind/feature request, review

#10221 Ensure orhpaned series cleaned up with shard drop
  tsdb/config.go
  tsdb/config_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
  tsdb/index.go
  tsdb/index/inmem/inmem.go
  tsdb/index/tsi1/index.go
  tsdb/shard_internal_test.go
  tsdb/store.go
  tsdb/store_test.go
Labels: kind/bug, review

#10215 Switch digests to use snappy compression
  tsdb/engine/tsm1/digest.go
  tsdb/engine/tsm1/digest_reader.go
  tsdb/engine/tsm1/digest_test.go
  tsdb/engine/tsm1/digest_writer.go
Labels: kind/feature request, review

#10227 Use snappy compression for digests
  tsdb/engine/tsm1/digest.go
  tsdb/engine/tsm1/digest_reader.go
  tsdb/engine/tsm1/digest_test.go
  tsdb/engine/tsm1/digest_writer.go
Labels: review

#10228 update influxql version
  Gopkg.lock
  Gopkg.toml
Labels: review

#10226 Unmap LogFile on successful open
  tsdb/index/tsi1/log_file.go
Labels: area/tsi, review

#10230 Update to the Godeps for the latest influxql
  Godeps
Labels: review

#10231 fix(storage): Fix potential panic if nil is returned
  services/storage/group_resultset.go
  services/storage/group_resultset_test.go
Labels: review

#10236 fix(tsm1): return boolean array iterator for booleans
  tsdb/engine/tsm1/array_cursor_iterator.go
Labels: review

#10237 update release date for 1.6.2
  CHANGELOG.md
Labels: review

#10246 Fix the inherited interval for derivative and others
  query/compile.go
  query/compile_test.go
Labels: review

#10252 Fixing the changelog
  CHANGELOG.md
Labels: review

#10251 Fix the inherited interval for derivative and others
  query/compile.go
  query/compile_test.go
Labels: kind/bug, review
