Repository influxdata/influxdb, pull requests merged in 2018-05, with the labels that each got.

#9791 Optimize the spread function to process points iteratively instead of in batch
  query/call_iterator.go
  query/functions.go
  tsdb/index/inmem/meta.go
Labels: kind/feature request, review

#9649 Allow math functions to be used in the condition
  tsdb/engine/tsm1/iterator.gen.go
  tsdb/engine/tsm1/iterator.gen.go.tmpl
  tsdb/index.go
  tsdb/index/inmem/meta.go
Labels: kind/feature request, review

#9800 Backport #9785: Rename corrupt tsm files on load.
  tsdb/engine/tsm1/file_store.go
Labels: review

#9803 Update changelog
  CHANGELOG.md
Labels: review

#9794 tsdb/index: Add Bytes() methods
  pkg/estimator/hll/hll.go
  pkg/estimator/hll/hll_test.go
  pkg/estimator/sketch.go
  tsdb/index.go
  tsdb/index/inmem/inmem.go
  tsdb/index/inmem/inmem_test.go
  tsdb/index/inmem/meta.go
  tsdb/index/tsi1/file_set.go
  tsdb/index/tsi1/index.go
  tsdb/index/tsi1/index_file.go
  tsdb/index/tsi1/log_file.go
  tsdb/index/tsi1/measurement_block.go
  tsdb/index/tsi1/partition.go
  tsdb/series_set.go
  tsdb/shard.go
Labels: review

#9808 Backport import fixes
  cmd/influx-tools/export/exporter.go
  cmd/influx-tools/importer/README.md
  cmd/influx-tools/importer/command.go
  cmd/influx-tools/importer/importer.go
  cmd/influx-tools/internal/format/binary/writer.go
Labels: review

#9812 tsdb/WAL: Better respect for WAL disabled
  tsdb/engine/tsm1/engine.go
Labels: review

#9748 Prevent series type conflict
  pkg/radix/tree.go
  pkg/radix/tree_test.go
  tsdb/engine/tsm1/cache.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
  tsdb/engine/tsm1/file_store.go
  tsdb/shard.go
Labels: review

#9822 Implement SHOW STATS FOR 'indexes'
  cmd/influxd/run/server.go
  coordinator/statement_executor.go
  tsdb/engine.go
  tsdb/engine/tsm1/engine.go
  tsdb/index.go
  tsdb/index/inmem/inmem.go
  tsdb/index/inmem/inmem_test.go
  tsdb/index/inmem/meta.go
  tsdb/index/tsi1/index.go
  tsdb/index/tsi1/log_file.go
  tsdb/shard.go
  tsdb/store.go
Labels: area/stats, kind/feature request, review

#9827 Correct godoc for SeriesFile.CreateSeriesListIfNotExists
  tsdb/series_file.go
  tsdb/series_partition.go
Labels: area/documentation, area/tsm, review

#9838 Include the query task status in the QueryInfo struct
  query/task_manager.go
Labels: review

#9832 Add dumptsmwal command to influx_inspect.
  cmd/influx_inspect/dumptsmwal/dumptsmwal.go
  cmd/influx_inspect/main.go
Labels: kind/feature request, review

#9828 Cleanup index memory footprint counting code
  tsdb/engine.go
  tsdb/engine/tsm1/engine.go
  tsdb/index.go
  tsdb/index/inmem/inmem.go
  tsdb/index/inmem/inmem_test.go
  tsdb/index/tsi1/index.go
  tsdb/index_test.go
  tsdb/shard.go
  tsdb/store.go
Labels: area/storage, kind/bug, review

#9826 TSM Filename Injection
  tsdb/engine.go
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
  tsdb/engine/tsm1/file_store_test.go
Labels: review

#9841 tsm1: ensure some race conditions are impossible
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/file_store.go
Labels: review

#9824 radix: optimize for our use case
  pkg/radix/buffer.go
  pkg/radix/buffer_test.go
  pkg/radix/tree.go
  pkg/radix/tree_test.go
  tsdb/engine/tsm1/engine.go
Labels: review

#9858 Return the correct auxiliary values for top/bottom
  query/functions.go
  query/iterator_test.go
  query/point.gen.go
  query/point.gen.go.tmpl
  query/select_test.go
Labels: kind/bug, review

#9866 Close TSMReaders from FileStore.Close after releasing FileStore mutex
  tsdb/engine/tsm1/file_store.go
Labels: area/retention policies, kind/bug, review

#9868 Close TSMReaders from FileStore.Close after releasing FileStore mutex
  tsdb/engine/tsm1/file_store.go
Labels: review

#9860 rename "triple_exponential_average" -> "triple_exponential_derivative"
  query/call_iterator.go
  query/compile.go
  query/functions.go
  query/select.go
Labels: proposed

#9869 Return the correct auxiliary values for top/bottom
  query/functions.go
  query/point.gen.go
  query/point.gen.go.tmpl
  query/select_test.go
Labels: review

#9870 Fix the new top/bottom unit tests
  query/select_test.go
Labels: review

#9852 file store: send notifications about new/deleted tsm files.
  tsdb/engine.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
Labels: review

#9853 Fix the log2 function to return values
  query/math.go
  query/math_test.go
Labels: review

#9880 dumptsmwal: fix minor vet error
  cmd/influx_inspect/dumptsmwal/dumptsmwal.go
Labels: review

#9836 Performance optimization suggestions
  tsdb/index/inmem/inmem.go
Labels: pm/review, proposed

#9885 Revert "Performance optimization suggestions"
  tsdb/index/inmem/inmem.go
Labels: review

#9879 tsdb: add shard number to the observer
  tsdb/engine.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
Labels: review

#9888 [1.6] HTTP Write Throttle
  etc/config.sample.toml
  services/httpd/config.go
  services/httpd/handler.go
  services/httpd/handler_test.go
Labels: kind/feature request, review

#9896 fix(tsm1): Avoid searching index if key outside index bounds
  tsdb/engine/tsm1/reader.go
Labels: review

#9898 Add optional pprof http endpoint immediately on startup.
  cmd/influxd/run/command.go
  etc/config.sample.toml
  services/httpd/config.go
Labels: review

#9892 tsdb: observe tombstone files as well
  tsdb/engine.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
  tsdb/engine/tsm1/file_store_observer.go
  tsdb/engine/tsm1/file_store_test.go
  tsdb/engine/tsm1/reader.go
  tsdb/engine/tsm1/tombstone.go
  tsdb/engine/tsm1/tombstone_test.go
Labels: review

#9907 Fix the influx_inspect man page
  man/influx_inspect.txt
Labels: review

#9908 Updated CHANGELOG;set a release date
  CHANGELOG.md
Labels: review

#9855 Remove an unused variable caught by megacheck in the importer
  cmd/influx-tools/importer/importer.go
Labels: review

#9917 refactor(services/storage): Enhanced group support for Read RPC
  cmd/store/query/query.go
  logger/context.go
  services/storage/batch_cursor.gen.go
  services/storage/batch_cursor.gen.go.tmpl
  services/storage/batch_cursor.go
  services/storage/eval.go
  services/storage/group_resultset.go
  services/storage/group_resultset_test.go
  services/storage/predicate.pb.go
  services/storage/predicate.proto
  services/storage/response_writer.gen.go
  services/storage/response_writer.gen.go.tmpl
  services/storage/response_writer.go
  services/storage/resultset.go
  services/storage/rpc_service.go
  services/storage/series_cursor.go
  services/storage/series_cursor_test.go
  services/storage/storage.go
  services/storage/storage.pb.go
  services/storage/storage.proto
  services/storage/storage.yarpc.go
  services/storage/store.go
  services/storage/tagsbuffer.go
Labels: review

#9924 [1.5] Fix panic in readTombstoneV4
  tsdb/engine/tsm1/tombstone.go
  tsdb/engine/tsm1/tombstone_test.go
Labels: kind/bug, review

#9918 TSM1 Open Limiter
  tsdb/engine.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
  tsdb/store.go
Labels: kind/bug, review

#9928 TSM: Enforce OpenLimiter must not be nil
  tsdb/engine/tsm1/file_store.go
Labels: area/tsm, kind/bug, review

#9926 fix(services/storage): Add nil checks to prevent panics
  services/storage/group_resultset.go
  services/storage/series_cursor.go
  services/storage/store.go
Labels: kind/bug, review
