Repository influxdata/influxdb, pull requests merged in 2018-02, with the labels that each got.

#9422 Ensure nil sketches never returned
  pkg/estimator/hll/hll.go
  tsdb/store.go
Labels: review

#9423 Fix imports of multiple databases in a single import file from `influx -import`
  CHANGELOG.md
  importer/v8/importer.go
  tests/export_import_test.go
Labels: review

#9426 Fix a deadlock in the monitor test
  monitor/service_test.go
Labels: review

#9430 Use --no-verbose with wget to reduce output
  Dockerfile_build_ubuntu32
  Dockerfile_build_ubuntu64
  Dockerfile_build_ubuntu64_git
  Dockerfile_build_ubuntu64_go19
  Dockerfile_jenkins_ubuntu32
Labels: review

#9434 Ensure db specified for SHOW CARDINALITY
  coordinator/statement_executor.go
Labels: review

#9441 simplify code
  tsdb/engine/tsm1/engine.go
Labels: review

#9439 Remove IsAdmin() method from meta.User interface
  services/meta/client_test.go
  services/meta/data.go
Labels: review

#9056 Add logging configuration to the main configuration file
  CHANGELOG.md
  Godeps
  LICENSE_OF_DEPENDENCIES.md
  cmd/influxd/main.go
  cmd/influxd/run/command.go
  cmd/influxd/run/config.go
  etc/config.sample.toml
  logger/config.go
  logger/logger.go
Labels: kind/feature request, review

#9443 Fix regression when math between literals is used in a field
  query/compile.go
  query/compile_test.go
Labels: kind/bug, review

#9445 Suppress the InfluxDB banner if the log output is not a TTY
  cmd/influxd/run/command.go
  etc/config.sample.toml
  logger/logger.go
Labels: kind/feature request, review

#9449 Added option to write HTTP request logs to separate file
  etc/config.sample.toml
  services/httpd/config.go
  services/httpd/handler.go
  services/httpd/service.go
Labels: kind/feature request, review

#9450 Fix data race when collecting sketches
  tsdb/store.go
Labels: review

#9451 Inmem series creation improvements
  tsdb/index/inmem/inmem.go
  tsdb/index/inmem/meta.go
  tsdb/series_segment.go
Labels: review

#9455 Add a reference to the license for zap-logfmt
  LICENSE_OF_DEPENDENCIES.md
Labels: review

#9464 Re-open last WAL segment
  tsdb/engine/tsm1/engine_test.go
  tsdb/engine/tsm1/file_store.go
  tsdb/engine/tsm1/wal.go
  tsdb/engine/tsm1/wal_test.go
Labels: kind/bug, review

#9465 Mark a shard as in process of being deleted
  tsdb/store.go
Labels: review

#9466 Fix the logging sample config
  etc/config.sample.toml
Labels: review

#9454 Update logging calls to take advantage of structured logging
  cmd/influxd/main.go
  cmd/influxd/run/command.go
  coordinator/points_writer.go
  logger/logger.go
  logger/style_guide.md
  monitor/service.go
  monitor/service_test.go
  services/collectd/service.go
  services/continuous_querier/service.go
  services/graphite/service.go
  services/httpd/handler.go
  services/httpd/service.go
  services/meta/client.go
  services/opentsdb/handler.go
  services/opentsdb/service.go
  services/precreator/service.go
  services/retention/service.go
  services/snapshotter/service.go
  services/subscriber/service.go
  services/udp/service.go
  tsdb/engine/tsm1/cache.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
  tsdb/engine/tsm1/wal.go
  tsdb/store.go
Labels: kind/feature request, review

#9470 Make closing TSM cursors idempotent
  tsdb/engine/tsm1/iterator.gen.go
  tsdb/engine/tsm1/iterator.gen.go.tmpl
  tsdb/engine/tsm1/iterator_test.go
Labels: kind/bug, review

#9472 Remove noisy trace logging in TSM engine
  tsdb/engine/tsm1/engine.go
Labels: review

#9456 Generate trace logs for a number of important InfluxDB operations
  cmd/influx_inspect/buildtsi/buildtsi.go
  logger/fields.go
  logger/logger.go
  monitor/service.go
  pkg/snowflake/README.md
  pkg/snowflake/gen.go
  pkg/snowflake/gen_test.go
  services/collectd/service.go
  services/continuous_querier/service.go
  services/graphite/service.go
  services/httpd/handler.go
  services/meta/client.go
  services/opentsdb/service.go
  services/retention/service.go
  services/subscriber/service.go
  services/udp/service.go
  tsdb/engine/tsm1/engine.go
  tsdb/index/tsi1/partition.go
  tsdb/series_partition.go
  tsdb/store.go
Labels: kind/feature request, review

#9471 Update sample config with information on logging levels
  etc/config.sample.toml
  query/query_executor.go
Labels: review

#9474 series keys are produced in ascending order
  services/storage/series_cursor.go
Labels: review

#9442 Fix the 1.4.3 changelog to have the correct year
  CHANGELOG.md
Labels: review

#9477 rename + namespace keys, fix doc comment
  .gitignore
  logger/fields.go
  services/continuous_querier/service.go
  services/retention/service.go
  tsdb/engine/tsm1/engine.go
  tsdb/index/tsi1/index.go
  tsdb/index/tsi1/partition.go
  tsdb/series_partition.go
  tsdb/store.go
Labels: review

#9483 prefix with `tsm1_` for consistency
  tsdb/engine/tsm1/engine.go
Labels: review

#9488 Improve startup time of inmem index
  tsdb/engine/tsm1/engine.go
  tsdb/index.go
  tsdb/index/inmem/inmem.go
  tsdb/index/tsi1/index.go
Labels: kind/feature request, review

#9487 fallback to inmem TagSets implementation
  tsdb/engine/tsm1/engine.go
  tsdb/index.go
Labels: review

#9489 Add dumptsi path error handling.
  cmd/influx_inspect/dumptsi/dumptsi.go
  tsdb/index/tsi1/index.go
  tsdb/index/tsi1/partition.go
Labels: review

#9398 Fix stddev() call to report itself as always returning a float
  CHANGELOG.md
  influxql/ast.go
Labels: kind/bug, review

#9397 Fix stddev() call to report itself as always returning a float
  CHANGELOG.md
  Godeps
Labels: kind/bug, review

#9495 use child logger
  tsdb/engine/tsm1/engine.go
Labels: review

#9494 Skip creating cursors for series not in a shard
  tsdb/index/inmem/inmem.go
  tsdb/index/inmem/meta.go
  tsdb/index/inmem/meta_test.go
Labels: review

#9490 Support less granular mtime in LastModified test
  tsdb/engine/tsm1/engine_test.go
Labels: review

#9493 Fix the implicit time range in a subquery
  query/compile.go
  query/iterator.go
  query/select.go
  query/subquery.go
Labels: kind/bug, review

#9491 Evaluate a true boolean literal when calculating tag sets
  Godeps
  tsdb/index.go
  tsdb/index/inmem/meta.go
Labels: kind/bug, review

#9496 Fix panic on tsi1 log replay of deleted series.
  tsdb/index/tsi1/log_file.go
Labels: kind/bug
