Repository influxdata/influxdb, pull requests merged in 2018-07, with the labels that each got.

#10013 Filter iterators as high up a possible
  tsdb/index.go
  tsdb/meta_test.go
  tsdb/shard_test.go
Labels: review

#10034 Update the github.com/golang/protobuf dependency in gdm to match dep
  Godeps
Labels: review

#10032 Add new TSI index cardinality report to influx_inspect
  cmd/influx_inspect/main.go
  cmd/influx_inspect/reporttsi/report.go
Labels: area/tooling, review

#10044 Implement bitset iterator
  tsdb/index.go
  tsdb/index/tsi1/file_set.go
  tsdb/index/tsi1/log_file.go
  tsdb/index/tsi1/measurement_block.go
  tsdb/series_set.go
Labels: kind/feature request, review

#10047 Updated release date for 1.6
  CHANGELOG.md
Labels: review

#10046 httpd: fix flaky test in timeout handler
  services/httpd/handler.go
  services/httpd/handler_test.go
Labels: review

#10050 Resolve deadlock deleting from many measurements concurrently
  tsdb/index/tsi1/partition.go
  tsdb/shard.go
Labels: review

#10048 Improve performance of buildtsi tool / series creation
  cmd/influx_inspect/buildtsi/buildtsi.go
  models/points.go
  tsdb/index/tsi1/index.go
  tsdb/index/tsi1/log_file.go
  tsdb/index/tsi1/partition.go
  tsdb/series_set.go
Labels: review

#10005 Missing hardwareAddr in uuid v1 generation
  uuid/uuid.go
Labels: proposed

#10058 cleanup import order in uuid.go
  uuid/uuid.go
Labels: review

#10051 Update example config with UDP precision option
  etc/config.sample.toml
  services/udp/config.go
  services/udp/config_test.go
Labels: kind/bug, needs-backport/1.6, review

#10073 Update to Go 1.10
  CONTRIBUTING.md
  Dockerfile
  Dockerfile_build_ubuntu32
  Dockerfile_build_ubuntu64
  Dockerfile_build_ubuntu64_git
  Dockerfile_build_ubuntu64_go1.11
  Dockerfile_jenkins_ubuntu32
  Jenkinsfile
  cmd/influx_tools/internal/format/binary/writer_test.go
  releng/_go_versions.sh
  test.sh
Labels: needs-backport/1.6, review

#10012 Improve series segment recovery
  tsdb/series_segment.go
  tsdb/series_segment_test.go
Labels: kind/bug, review

#10076 Fix windows mmap on zero length file.
  cmd/store/query/query.go
  pkg/mmap/mmap_windows.go
Labels: kind/bug, review

#10078 Improve LogFile performance with bitset iterator
  tsdb/index.go
  tsdb/index/tsi1/file_set.go
  tsdb/index/tsi1/log_file.go
  tsdb/index/tsi1/measurement_block.go
  tsdb/series_set.go
Labels: kind/feature request, review

#10037 Ensure Filter iterators executed as late as possible
  tsdb/index.go
  tsdb/meta_test.go
  tsdb/shard_test.go
Labels: kind/bug, review

#10077 Add TSI index cardinality report to influx_inspect
  cmd/influx_inspect/main.go
  cmd/influx_inspect/reporttsi/report.go
  cmd/store/query/query.go
Labels: kind/feature request, review

#10079 Update to Go 1.10
  CONTRIBUTING.md
  Dockerfile
  Dockerfile_build_ubuntu32
  Dockerfile_build_ubuntu64
  Dockerfile_build_ubuntu64_git
  Dockerfile_build_ubuntu64_go1.11
  Dockerfile_jenkins_ubuntu32
  Jenkinsfile
  cmd/influx-tools/internal/format/binary/writer_test.go
  releng/_go_versions.sh
  test.sh
Labels: kind/feature request, review

#10080 Improve performance of buildtsi and TSI planning
  cmd/influx_inspect/buildtsi/buildtsi.go
  models/points.go
  tsdb/index/tsi1/index.go
  tsdb/index/tsi1/log_file.go
  tsdb/index/tsi1/partition.go
  tsdb/series_set.go
Labels: kind/feature request, review

#10082 httpd: fix flaky test in timeout handler
  services/httpd/handler.go
  services/httpd/handler_test.go
Labels: review

#10066 Update CHANGELOG on the 1.6 branch to include the 1.5.x maintenance releases.
  CHANGELOG.md
Labels: review

#10061 Document UDP precision setting in config
  etc/config.sample.toml
  services/udp/config.go
  services/udp/config_test.go
Labels: kind/bug, review

#10083 Update Godeps
  Godeps
Labels: review

#10021 bug fix from seriesfile enable EnableCompactions function
  tsdb/series_partition.go
Labels: proposed

#10091 Allow tag keys to contain underscores
  Gopkg.lock
  Gopkg.toml
  tsdb/store.go
Labels: kind/bug, review

#10092 Update Windows CI Go to 1.10
  appveyor.yml
Labels: needs-backport/1.6, review

#10089 inmem: use radix sort for series ids
  pkg/radix/sort.go
  pkg/radix/sort_test.go
  tsdb/index/inmem/meta.go
Labels: review

#10095 Fix a panic when matching on a specific type of regular expression
  Gopkg.lock
  Gopkg.toml
Labels: kind/bug, review

#10094 Fix a panic when matching on a specific type of regular expression
  Gopkg.lock
Labels: kind/bug, review

#10097 inmem: use radix sort for series ids
  pkg/radix/sort.go
  pkg/radix/sort_test.go
  tsdb/index/inmem/meta.go
Labels: review

#10099 Improve performance of read service for single measurements
  coordinator/statement_executor_test.go
  services/storage/predicate_influxql.go
  services/storage/predicate_test.go
  services/storage/series_cursor.go
  tsdb/shard.go
  tsdb/shard_test.go
Labels: kind/feature request, review

#10067 Update CHANGELOG on master for 1.5.x releases and 1.6 release date.
  CHANGELOG.md
Labels: review

#10102 Remove max concurrent compaction limit
  tsdb/store.go
Labels: kind/feature request, needs-backport/1.6, review

#10103 Remove max concurrent compaction limit
  tsdb/store.go
Labels: kind/feature request, review

#10063 Make store include context in logs
  tsdb/store.go
Labels: needs-backport/1.6, review

#10104 fix(storage): Check for Array cursor types
  services/storage/group_resultset.go
Labels: review

#10109 Update Godeps
  Godeps
Labels: review

#10105 Make store include context in logs
  tsdb/store.go
Labels: review

#10132 fix(influx_tools): Use Array cursor types
  cmd/influx_tools/internal/format/binary/reader_test.go
  cmd/influx_tools/internal/format/binary/writer.go
  cmd/influx_tools/internal/format/binary/writer_test.go
  cmd/influx_tools/internal/format/conflictwriter.go
  cmd/influx_tools/internal/format/line/writer.go
  cmd/influx_tools/internal/format/text/writer.go
  cmd/influx_tools/internal/format/writer.go
Labels: review
