Repository influxdata/influxdb, pull requests merged in 2018-12, with the labels that each got.

#10534 chore: CHANGELOG changes
  CHANGELOG.md
Labels: review

#10130 client/v2: support custom dialer, not just socks proxy
  client/v2/client.go
Labels: kind/feature request, proposed

#10535 chore: update Flux to v0.7.2
  Gopkg.lock
  Gopkg.toml
Labels: review

#10537 Update copyright information
  LICENSE
Labels: review

#10539 Drop NaN values when writing back points
  coordinator/statement_executor.go
  coordinator/statement_executor_test.go
Labels: review

#10549 Pass the query authorizer to subqueries
  query/iterator.go
  query/subquery_test.go
Labels: kind/bug, review

#10552 Backport #10549: Pass the query authorizer to subqueries
  query/iterator.go
  query/subquery_test.go
Labels: kind/bug, review

#10558 Backport #10549: Pass the query authorizer to subqueries
  query/iterator.go
  query/subquery_test.go
Labels: review

#10559 Backport #10549: Pass the query authorizer to subqueries
  query/iterator.go
Labels: review

#10538 Add data generator to influx_tools command
  Gopkg.lock
  Gopkg.toml
  cmd/influx_tools/export/exporter.go
  cmd/influx_tools/generate/exec/command.go
  cmd/influx_tools/generate/exec/generator.go
  cmd/influx_tools/generate/exec/series_generator.go
  cmd/influx_tools/generate/init/command.go
  cmd/influx_tools/generate/plan.go
  cmd/influx_tools/generate/spec.go
  cmd/influx_tools/help/help.go
  cmd/influx_tools/importer/importer.go
  cmd/influx_tools/internal/profile/profile.go
  cmd/influx_tools/internal/shard/writer.go
  cmd/influx_tools/main.go
  cmd/influx_tools/server/server.go
Labels: review

#10568 Flux group(mode:"by") does not push down correct operation to storage layer
  flux/functions/inputs/from.go
Labels: review

#10569 build: update Flux to v0.9.0
  Gopkg.lock
  Gopkg.toml
Labels: review

#10571 Update platform to resolve panic with group push down
  Gopkg.lock
Labels: review

#10556 Drop NaN values when writing back points
  coordinator/statement_executor.go
  coordinator/statement_executor_test.go
Labels: kind/bug, review

#10572 tsdb: mixed shard tests
  tsdb/store_test.go
Labels: review

#10576 Update Go runtime to 1.10.6
  CONTRIBUTING.md
  Dockerfile
  Dockerfile_build_ubuntu32
  Dockerfile_build_ubuntu64
  Dockerfile_build_ubuntu64_git
  Dockerfile_build_ubuntu64_go1.11
  Dockerfile_jenkins_ubuntu32
  Jenkinsfile
  appveyor.yml
  coordinator/meta_client_test.go
  releng/_go_versions.sh
  services/continuous_querier/service_test.go
  services/httpd/response_writer_test.go
  services/retention/service_test.go
  services/snapshotter/service_test.go
  test.sh
  tsdb/engine/tsm1/engine.go
Labels: review

#10536 Limit force-full and cold compaction size.
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
Labels: area/storage, area/tsm, review

#10577 Fix TSM1 panic on reader error.
  tsdb/engine/tsm1/file_store.go
Labels: review

#10578 Limit database and retention policy names to 255 characters
  services/meta/data.go
  services/meta/data_test.go
  services/meta/errors.go
Labels: review

#10585 Limit database and retention policy names to 255 characters
  services/meta/data.go
  services/meta/data_test.go
  services/meta/errors.go
Labels: review

#10580 Add user authentication and authorization support for Flux HTTP requests
  cmd/influxd/run/server.go
  flux/control/controller.go
  flux/functions/inputs/buckets.go
  flux/functions/inputs/from.go
  services/httpd/handler.go
  services/httpd/handler_test.go
  services/meta/context.go
  services/meta/query_authorizer.go
Labels: kind/enhancement, review

#10588 chore: set a release date for 1.5.5 GA
  CHANGELOG.md
Labels: review

#10593 Limit force-full and cold compaction size.
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
Labels: review

#10590 build(flux): update to Flux v0.11.0
  Gopkg.lock
  Gopkg.toml
Labels: review

#10598 Call storage.Group API to correctly map group mode
  flux/functions/inputs/from.go
Labels: review
