Repository influxdata/influxdb, pull requests merged in 2018-09, with the labels that each got.

#10256 Revert: Unmap LogFile on successful open
  tsdb/index/tsi1/log_file.go
Labels: panic, review

#10211 Use the const var as the parameter in the construction function
  monitor/config.go
Labels: proposed

#10262 Fix the derivative and others time ranges for aggregate data
  query/compile.go
  query/compile_test.go
Labels: kind/bug, review

#10271 fix(tsm1): Fix FloatBatchDecodeAll to return empty slice an no error
  tsdb/engine/tsm1/batch_float.go
  tsdb/engine/tsm1/batch_float_test.go
Labels: review

#10273 Fix the derivative and others time ranges for aggregate data
  query/compile.go
  query/compile_test.go
Labels: kind/bug, review

#10274 Fix the derivative and others time ranges for aggregate data
  query/compile.go
  query/compile_test.go
Labels: kind/bug, review

#10278 Remove TSI1 HLL sketches from heap.
  tsdb/index/tsi1/file_set.go
  tsdb/index/tsi1/index.go
  tsdb/index/tsi1/index_file.go
  tsdb/index/tsi1/log_file.go
  tsdb/index/tsi1/measurement_block.go
  tsdb/index/tsi1/partition.go
  tsdb/index_test.go
  tsdb/store_test.go
Labels: area/storage, review

#10280 Remove TSI1 HLL sketches from heap.
  tsdb/index/tsi1/file_set.go
  tsdb/index/tsi1/index.go
  tsdb/index/tsi1/index_file.go
  tsdb/index/tsi1/log_file.go
  tsdb/index/tsi1/measurement_block.go
  tsdb/index/tsi1/partition.go
  tsdb/index_test.go
  tsdb/store_test.go
Labels: area/storage, kind/feature request, review

#10286 Update for release date for 1.6.3
  CHANGELOG.md
Labels: review

#10265 Update to Go 1.11
  CONTRIBUTING.md
  Dockerfile
  Dockerfile_build_ubuntu32
  Dockerfile_build_ubuntu64
  Dockerfile_build_ubuntu64_git
  Dockerfile_jenkins_ubuntu32
  Jenkinsfile
  releng/_go_versions.sh
  services/httpd/response_writer_test.go
  test.sh
Labels: review

#10303 fix(storage): Set the Type field to Tag
  services/storage/predicate_influxql.go
  services/storage/predicate_test.go
Labels: review

#10307 Backup continue on errors
  cmd/influxd/backup/backup.go
  man/influxd-backup.txt
Labels: kind/enhancement, kind/feature request, review
