Repository influxdata/influxdb, pull requests merged in 2018-03, with the labels that each got.

#9505 ensure ENV overrides are applied when configuring logging
  cmd/influxd/run/command.go
Labels: review

#9510 Fix TSI log file recovery.
  tsdb/index/tsi1/log_file.go
  tsdb/index/tsi1/log_file_test.go
Labels: kind/bug, review

#9513 Fix missing Store.Close() unlock.
  tsdb/store.go
Labels: kind/bug, review

#9520 Updated CHANGELOG.md to the GA released date - 2017-03-06
  CHANGELOG.md
Labels: review

#9525 Turn the ExecutionContext into a context.Context
  coordinator/statement_executor.go
  query/compile.go
  query/execution_context.go
  query/executor.go
  query/executor_test.go
  query/iterator.go
  query/iterator_test.go
  query/monitor.go
  query/monitor_test.go
  query/select.go
  query/task_manager.go
  services/continuous_querier/service_test.go
  services/httpd/handler_test.go
Labels: review

#9538 Use the error in the point limit monitor test
  query/monitor_test.go
Labels: review

#9531 Modify the Select call to return a Cursor
  coordinator/statement_executor.go
  query/cursor.go
  query/emitter.go
  query/emitter_test.go
  query/explain.go
  query/internal/internal.pb.go
  query/iterator.gen.go
  query/iterator.gen.go.tmpl
  query/iterator_mapper.go
  query/iterator_mapper_test.go
  query/monitor_test.go
  query/select.go
  query/select_test.go
  query/subquery.go
Labels: review

#9536 Fix the deadlocks in the monitor tests
  monitor/service_test.go
Labels: review

#9492 Evaluate a true boolean literal when calculating tag sets
  Godeps
  tsdb/index/inmem/meta.go
  tsdb/index/tsi1/file_set.go
Labels: kind/bug, review

#9542 Allow time variable to be case insensitive again
  Godeps
Labels: kind/bug, review

#9541 Allow time variable to be case insensitive again
  Godeps
Labels: kind/bug, review

#9553 Support setting the log level through the environment variable
  cmd/influxd/run/config.go
  cmd/influxd/run/config_test.go
Labels: kind/bug, needs-backport/1.5, review

#9429 Support proxy environment variables in the influx client
  client/influxdb.go
  client/influxdb_test.go
  client/v2/client.go
  client/v2/client_test.go
  cmd/influx/cli/cli.go
  man/influx.txt
Labels: kind/feature request, review

#9552 Add option to disable WAL
  tsdb/engine.go
  tsdb/engine/tsm1/engine.go
Labels: review

#9551 Fix panic when checking fieldsets
  services/subscriber/service_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_cursor.go
  tsdb/index.go
  tsdb/shard.go
  tsdb/shard_test.go
  tsdb/store_test.go
Labels: kind/bug, review

#9461 Do not drop on the floor small buffers
  tsdb/engine/tsm1/pools.go
Labels: proposed

#9564 Support setting the log level through the environment variable
  cmd/influxd/run/config.go
  cmd/influxd/run/config_test.go
Labels: kind/bug, review

#9406 Use dep for dependency management instead of gdm
  .gitignore
  CONTRIBUTING.md
  Dockerfile
  Gopkg.lock
  Gopkg.toml
  Jenkinsfile
  appveyor.yml
  build.py
  releng/source-tarball/Dockerfile
  releng/source-tarball/fs/usr/local/bin/influxdb_tarball.bash
Labels: review

#9573 Ensure correct number of tags parsed when commas used
  models/points.go
  models/points_test.go
Labels: kind/bug, review

#9568 Update influxql to include the function type evaluators in the query package
  Godeps
  Gopkg.lock
  Gopkg.toml
  query/compile.go
  query/functions.go
  query/select.go
Labels: review

#9376 Move ApplyEnvOverrides to toml package
  cmd/influxd/run/config.go
  toml/toml.go
  toml/toml_test.go
Labels: review

#9575 Ensure correct number of tags parsed
  models/points.go
  models/points_test.go
Labels: kind/bug, review

#9576 Bugfix for shard collisions resulting from attempted _internal import
  cmd/influxd/restore/restore.go
  tests/backup_restore_test.go
Labels: kind/bug, review

#9582 Improve performance of SHOW SERIES query
  tsdb/index.go
  tsdb/shard.go
Labels: review

#9580 Fix data race in WAL
  .hooks/pre-commit
  tsdb/engine/tsm1/wal.go
  tsdb/engine/tsm1/wal_test.go
Labels: kind/bug, needs-backport/1.5, review

#9585 Improve performance of SHOW SERIES query
  tsdb/index.go
  tsdb/shard.go
Labels: kind/bug, review

#9586 Allow SHOW SERIES kill
  tsdb/index.go
  tsdb/shard.go
Labels: kind/bug, review

#9566 Fix panic when checking fieldsets
  services/subscriber/service_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_cursor.go
  tsdb/index.go
  tsdb/shard.go
  tsdb/shard_test.go
  tsdb/store_test.go
Labels: kind/bug, review

#9588 Use math/bits exclusively instead of go-bits
  Godeps
  Gopkg.lock
  Gopkg.toml
  pkg/bits/bits.go
  pkg/bits/bits_1.9.go
  pkg/estimator/hll/hll.go
  tsdb/engine/tsm1/float.go
Labels: review

#9587 Fix data race in WAL
  .hooks/pre-commit
  tsdb/engine/tsm1/wal.go
  tsdb/engine/tsm1/wal_test.go
Labels: kind/bug, review

#9594 Updated CHANGELOG for 1.5.1
  CHANGELOG.md
Labels: review

#9595 Update dependencies and remove unnecessary constraints from Gopkg.toml
  Godeps
  Gopkg.lock
  Gopkg.toml
  write-gdm-deps.sh
Labels: review

#9600 Updated all dependencies
  Godeps
  Gopkg.lock
  Gopkg.toml
Labels: review

#9591 Handle embedded and ignored fields in toml env override
  toml/toml.go
  toml/toml_test.go
Labels: review

#9603 Remove error for series file when no shards exist
  tsdb/shard.go
Labels: review

#9563 Refactor the math engine to compile the query and use eval
  CHANGELOG.md
  query/compile.go
  query/cursor.go
  query/executor.go
  query/functions.go
  query/iterator.gen.go
  query/iterator.gen.go.tmpl
  query/iterator.go
  query/iterator_test.go
  query/math.go
  query/monitor.go
  query/select.go
  query/select_test.go
  query/subquery.go
  tests/server_test.go
  tsdb/shard.go
Labels: breaking change, kind/feature request, review

#9499 Implement basic trigonometry functions
  query/compile.go
  query/math.go
Labels: kind/feature request, review

#9612 Revert "Use MADV_WILLNEED when loading TSM files"
  tsdb/engine/tsm1/mmap_unix.go
  tsdb/engine/tsm1/mmap_windows.go
  tsdb/engine/tsm1/reader.go
Labels: kind/bug, review

#9567 Storage RPC API improvements
  cmd/store/main.go
  cmd/store/query/query.go
  query/iterator.go
  services/storage/batch_cursor.gen.go
  services/storage/batch_cursor.gen.go.tmpl
  services/storage/batch_cursor.go
  services/storage/predicate_influxql.go
  services/storage/response_writer.gen.go
  services/storage/response_writer.gen.go.tmpl
  services/storage/response_writer.go
  services/storage/resultset.go
  services/storage/series_cursor.go
  services/storage/series_cursor_test.go
  services/storage/storage.yarpc.go
  tsdb/cursor.go
  tsdb/engine.go
  tsdb/engine/tsm1/batch_cursor.gen.go
  tsdb/engine/tsm1/batch_cursor.gen.go.tmpl
  tsdb/engine/tsm1/cursor_iterator.gen.go
  tsdb/engine/tsm1/cursor_iterator.gen.go.tmpl
  tsdb/engine/tsm1/cursor_iterator.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_cursor.go
  tsdb/engine/tsm1/engine_test.go
  tsdb/series_cursor.go
  tsdb/shard.go
Labels: review

#9609 Add capability change compaction planner
  tsdb/engine.go
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
Labels: review

#9621 Fix flaky test TestServer_ConcurrentPointsWriter_Subscriber
  tests/server_test.go
Labels: review

#9629 Do not overwrite _measurement tag for multi-tenant reads
  services/storage/series_cursor.go
Labels: review

#9634 check for failure case where backup dir has no manifest files
  cmd/influxd/restore/restore.go
Labels: kind/bug, review

#9633 Fix regression to allow now() to be used as the group by offset again
  query/compile.go
  query/select_test.go
Labels: kind/bug, needs-backport/1.4, needs-backport/1.5, review

#9637 Use a null placeholder for NaN results
  query/call_iterator.go
  query/cursor.go
  query/iterator_mapper.go
  query/select_test.go
Labels: review

#9638 backport: check for failure case where backup dir has no manifest files
  cmd/influxd/restore/restore.go
Labels: kind/bug, review

#9647 Delete deleted shards in retention service.
  services/retention/service.go
  services/retention/service_test.go
Labels: kind/bug, review

#9648 Remove unused query code
  query/iterator.gen.go
  query/iterator.gen.go.tmpl
Labels: review

#9651 Fix regression to allow now() to be used as the group by offset again
  query/compile.go
  query/select_test.go
Labels: kind/bug, review

#9652 [1.5] Delete deleted shards
  services/retention/service.go
  services/retention/service_test.go
Labels: review

#9614 1.5: Revert "Use MADV_WILLNEED when loading TSM files"
  tsdb/engine/tsm1/mmap_unix.go
  tsdb/engine/tsm1/mmap_windows.go
  tsdb/engine/tsm1/reader.go
Labels: kind/bug

#9659 Ignore index size in Engine.DiskSize().
  tsdb/engine/tsm1/engine.go
Labels: kind/bug

#9660 Ignore index size in Engine.DiskSize().
  tsdb/engine/tsm1/engine.go
Labels: kind/bug

#9661 Fix buildtsi partition key.
  cmd/influx_inspect/buildtsi/buildtsi.go
Labels: kind/bug

#9658 Fix curl commands in contributing doc
  CONTRIBUTING.md
Labels: proposed

#9663 Log error encountered when reading WAL files
  cmd/influx_inspect/export/export.go
  tsdb/engine/tsm1/cache.go
Labels: review

#9665 Enable casting values from a subquery
  query/cast.go
  query/cursor.go
  query/iterator.gen.go
  query/iterator.gen.go.tmpl
  query/iterator.go
  query/iterator_mapper.go
  query/iterator_mapper_test.go
  query/select.go
  query/subquery.go
  query/subquery_test.go
Labels: kind/bug, review
