Repository influxdata/influxdb, pull requests merged in 2019-08, with the labels that each got.

#14444 fix(query): make show series exact cardinality count only distinct series
  query/statement_rewriter.go
  query/statement_rewriter_test.go
Labels: kind/bug, needs-backport/1.7

#14557 fix(query): make show series exact cardinality count only distinct series
  query/statement_rewriter.go
  query/statement_rewriter_test.go
Labels: kind/bug

#14636 fix(flux): Fix hanging test by ensuring results are read
  query/stdlib/testing/end_to_end_test.go
  query/stdlib/testing/testing.go
Labels: team/compute

#14638 perf(storage): reduce allocations when accessing series file or TSI
  pkg/rhh/rhh.go
  storage/engine_test.go
  tsdb/index_test.go
  tsdb/tsi1/index_test.go
Labels: performance

#14593 fix(query/compile.go): time range was exceeding min/max bounds under …
  query/compile.go
  query/compile_test.go
Labels: kind/bug

#14674 fix(storage): Ensure ResponseWriter flushes all buffered data
  pkg/data/gen/arrays.gen.go
  pkg/data/gen/arrays.gen.go.tmpl
  storage/reads/helpers_test.go
  storage/reads/response_writer.gen.go
  storage/reads/response_writer.gen.go.tmpl
  storage/reads/response_writer.go
  storage/reads/response_writer_test.go
  tsdb/cursors/arrayvalues.gen.go
  tsdb/cursors/arrayvalues.gen.go.tmpl
  tsdb/cursors/arrayvalues.go
Labels: area/storage

#14779 refactor(tasks): separate coordinator and middleware
  CHANGELOG.md
  cmd/influxd/launcher/launcher.go
  task/backend/coordinator.go
  task/backend/coordinator/coordinator.go
  task/backend/coordinator/coordinator_test.go
  task/backend/coordinator/support_test.go
  task/backend/coordinator_test.go
  task/backend/middleware/middleware.go
  task/backend/middleware/middleware_test.go
  task/backend/middleware/options.go
Labels: area/tasks, team/compute

#14724 docs(http): update swagger for easily use in clients
  http/swagger.yml
Labels: area/api

#14725 docs(http): update suggestions swagger definition to reflect reality
  http/swagger.yml
Labels: area/api

#14872 feat(kv): Add kv.Service org & bucket ID validation hooks.
  kv/bucket.go
  kv/bucket_test.go
  kv/org.go
  kv/org_test.go
  kv/service.go
Labels: area/storage
