Repository influxdata/influxdb, pull requests merged in 2019-05, with the labels that each got.

#13723 Ensure GroupCursor Keys is union of keys from all GroupCursors of current partition key
  storage/reads/mergegroupresultset.go
  storage/reads/mergegroupresultset_test.go
Labels: blocking/release/beta

#13743 Ensure sort keys are correctly delimited to avoid collisions
  storage/reads/group_resultset.go
  storage/reads/group_resultset_test.go
Labels: blocking/release/beta

#13779 fix(storage): don't remap renamed TSM file
  tsdb/tsm1/reader_mmap.go
Labels: kind/bug

#12103 fix(task): filter tasks by after param
  task/backend/bolt/bolt.go
  task/backend/storetest/storetest.go
Labels: area/tasks, team/workloads

#13854 Fix the ordering for selectors within a subquery with different outer tags
  query/iterator.gen.go
  query/iterator.gen.go.tmpl
  query/select.go
  query/subquery_test.go
Labels: kind/bug

#13697 Fix version output (v1.7)
  cmd/influx/cli/cli.go
Labels: area/cli
