Repository influxdata/influxdb, pull requests merged in 2019-04, with the labels that each got.

#13053 Add nil check for tagKeyValueEntry.setIDs()
  tsdb/index/inmem/meta.go
  tsdb/index/inmem/meta_test.go
Labels: area/storage, kind/bug, needs-backport/1.6, needs-backport/1.7

#13169 Document process for building distribution files locally
  CONTRIBUTING.md
Labels: area/documentation

#13150 Add nil check for tagKeyValueEntry.setIDs()
  tsdb/index/inmem/meta.go
  tsdb/index/inmem/meta_test.go
Labels: area/storage, kind/bug

#13151 Add nil check for tagKeyValueEntry.setIDs()
  tsdb/index/inmem/meta.go
  tsdb/index/inmem/meta_test.go
Labels: area/storage, kind/bug

#13205 Update predicate key mapping to match 2.x behavior
  services/storage/predicate_influxql.go
Labels: needs-backport/1.7

#12780 Improve bulk series file writes.
  pkg/rhh/rhh.go
  storage/config.go
  storage/engine.go
  tsdb/config.go
  tsdb/series_file.go
  tsdb/series_index.go
  tsdb/series_partition.go
  tsdb/series_partition_test.go
  tsdb/tsm1/config.go
Labels: area/storage, kind/feature request

#13441 Fix the sort order for aggregates so that they are sorted by tag and then time
  query/iterator.gen.go
  query/iterator.gen.go.tmpl
  query/subquery_test.go
Labels: kind/bug

#13442 Fix the sort order for aggregates so that they are sorted by tag and then time
  query/iterator.gen.go
  query/iterator.gen.go.tmpl
  query/subquery_test.go
Labels: kind/bug

#13382 fix(tsdb): Remove TSI stats file cache
  tsdb/tsi1/file_set.go
  tsdb/tsi1/index.go
  tsdb/tsi1/index_test.go
  tsdb/tsi1/partition.go
  tsdb/tsi1/stats.go
Labels: area/tsi, kind/bug

#13443 Fix the sort order for aggregates so that they are sorted by tag and then time
  query/iterator.gen.go
  query/iterator.gen.go.tmpl
  query/subquery_test.go
Labels: kind/bug

#13459 Fill resets the previous value when a new series or window is encountered
  query/cursor.go
  query/select_test.go
Labels: kind/bug

#13463 Use the timezone when evaluating time literals in subqueries
  query/iterator.go
  query/subquery_test.go
Labels: kind/bug

#13501 fill resets the previous value when a new series or window is encountered
  query/cursor.go
  query/select_test.go
Labels: kind/bug

#13426 Implementation of storage schema TagValues API
  storage/engine_schema.go
  storage/reads/merge.go
  storage/reads/merge_test.go
  storage/reads/store.go
  storage/reads/string_iterator_reader.go
  storage/reads/string_iterator_reader_test.go
  storage/reads/string_iterator_writer.go
  storage/readservice/store.go
  tsdb/cursor.go
  tsdb/cursors/arrayvalues.gen.go
  tsdb/cursors/arrayvalues.gen.go.tmpl
  tsdb/cursors/arrayvalues.gen.go.tmpldata
  tsdb/cursors/arrayvalues.gen_test.go
  tsdb/cursors/gen.go
  tsdb/cursors/string.go
  tsdb/tsm1/array_encoding.go
  tsdb/tsm1/encoding.go
  tsdb/tsm1/encoding_test.go
  tsdb/tsm1/engine.go
  tsdb/tsm1/engine_schema.go
  tsdb/tsm1/engine_schema_test.go
  tsdb/tsm1/engine_test.go
  tsdb/tsm1/file_store.go
  tsdb/tsm1/reader.go
  tsdb/tsm1/reader_index.go
  tsdb/tsm1/reader_index_iterator.go
  tsdb/tsm1/reader_index_iterator_test.go
  tsdb/tsm1/reader_range_iterator.go
  tsdb/tsm1/reader_range_iterator_test.go
  tsdb/tsm1/reader_time_range.go
Labels: area/storage, performance

#13504 fill resets the previous value when a new series or window is encountered
  query/cursor.go
  query/select_test.go
Labels: kind/bug

#13540 Use the timezone when evaluating time literals in subqueries
  query/iterator.go
  query/subquery_test.go
Labels: kind/bug

#13539 Use the timezone when evaluating time literals in subqueries
  query/iterator.go
  query/subquery_test.go
Labels: kind/bug

#13564 Fix csv decoder bug where empty tag values cause an array index panic
  services/httpd/response_writer.go
  services/httpd/response_writer_test.go
Labels: kind/bug

#13567 Fix csv decoder bug where empty tag values cause an array index panic
  services/httpd/response_writer.go
  services/httpd/response_writer_test.go
Labels: kind/bug

#13566 Fix csv decoder bug where empty tag values cause an array index panic
  services/httpd/response_writer.go
  services/httpd/response_writer_test.go
Labels: kind/bug

#12377 Merge point parse & explode
  gather/recorder.go
  http/write_handler.go
  models/points.go
  models/points_internal_test.go
  models/points_test.go
  query/stdlib/influxdata/influxdb/to.go
  query/stdlib/influxdata/influxdb/to_test.go
  storage/engine_test.go
  tsdb/explode.go
  tsdb/explode_test.go
  tsdb/index_test.go
  tsdb/tsm1/engine_delete_bucket_test.go
  tsdb/tsm1/engine_test.go
Labels: area/storage

#13527 Implementation of storage schema TagKeys API
  models/points.go
  models/points_test.go
  models/tagkeysset.go
  models/tagkeysset_test.go
  storage/engine_schema.go
  storage/readservice/store.go
  tsdb/cursors/string.go
  tsdb/tsm1/engine_schema.go
  tsdb/tsm1/engine_schema_test.go
  tsdb/tsm1/reader_range_iterator.go
  tsdb/tsm1/reader_range_iterator_test.go
Labels: area/storage, performance
