Repository influxdata/influxdb, pull requests merged in 2019-12, with the labels that each got.

#15322 fix(http): remove a HTTPNotificationRuleBase.url from required properties
  http/swagger.yml
Labels: area/api

#15363 fix(http): Return an empty array if organization has no secret keys
  bolt/secret.go
  http/org_service.go
  http/org_test.go
  kv/secret.go
Labels: area/api

#16137 feat(query): add trace_id and sampled to the query log
  logger/fields.go
  query/logger.go
  query/logging.go
  query/logging_test.go
Labels: team/compute

#16067 fix(http): update swagger for easily use in clients
  http/swagger.yml
Labels: area/api

#16263 feat(tasks): remove flux stats from run log and replace with trace id
  http/query_handler.go
  http/query_handler_test.go
  kit/tracing/testing/testing.go
  kit/tracing/tracing.go
  logger/fields.go
  query/logging.go
  task/backend/executor/executor.go
  task/backend/executor/task_executor.go
  task/backend/executor/task_executor_test.go
Labels: area/tasks
