Repository influxdata/influxdb, pull requests merged in 2019-11, with the labels that each got.

#15697 feat(kv): Cursor API accepts hints for improving performance
  bolt/kv.go
  inmem/kv.go
  kv/store.go
  kv/task.go
  kv/task_private_test.go
  mock/kv.go
  task/servicetest/servicetest.go
  testing/kv.go
Labels: team/compute

#15754 build(flux): update Flux to v0.53.0
  go.mod
  go.sum
Labels: team/query

#15731 fix(storage): array cursor iterator should return stats of all observed cursors
  CHANGELOG.md
  tsdb/tsm1/array_cursor_iterator.go
  tsdb/tsm1/engine_cursor_test.go
Labels: area/storage, kind/bug

#15878 fix(tsm1): make digest safe for concurrent use
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
Labels: 1.x, kind/bug

#15881 fix(tsm1): make digest safe for concurrent use
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
Labels: 1.x, kind/bug

#15917 feat(pkger): extend apply HTTP API to return parse err with 422 resp
  http/pkger_http_server.go
  http/pkger_http_server_test.go
  http/pkger_parse_err_test.go
  http/swagger.yml
  pkger/parser.go
  pkger/parser_test.go
  pkger/service.go
Labels: team/user-tools

#15970 Fix compaction logic on infrequent cache snapshots
  tsdb/engine/tsm1/engine.go
Labels: 1.x, kind/bug

#15986 fix(tasks): construct permissions for finish run to write to system buckets
  task/backend/analytical_storage.go
  task/backend/analytical_storage_test.go
  task/backend/executor/task_executor.go
  task/backend/executor/task_executor_test.go
  task/backend/support_test.go
Labels: area/tasks
