Repository influxdata/influxdb, pull requests merged in 2019-10, with the labels that each got.

#15295 fix(http): Ensures users are created with an active status
  CHANGELOG.md
  bolt/user.go
  inmem/user_service.go
  kv/user.go
  testing/onboarding.go
  testing/user_service.go
Labels: team/api

#15245 fix(notification/rule): fixed http NotificationRule
  http/notification_rule.go
  kv/notification_rule.go
  testing/notification_rule.go
Labels: area/api

#12568 Expose debug pprof port 6060
  Dockerfile
Labels: kind/bug, stale-exempt

#15341 update golang version to 1.12.10
  .circleci/config.yml
  CHANGELOG.md
  CONTRIBUTING.md
  Dockerfile
  Dockerfile_build_ubuntu32
  Dockerfile_build_ubuntu64
  Dockerfile_build_ubuntu64_git
  Dockerfile_build_ubuntu64_go1.11
  Dockerfile_jenkins_ubuntu32
  Jenkinsfile
  appveyor.yml
  releng/_go_versions.sh
  services/httpd/response_writer_test.go
  test.sh
Labels: team/qa

#15452 chore(gateway): log error on unauthorized attempt
  CHANGELOG.md
  http/authentication_middleware.go
Labels: area/api, area/auth, team/compute

#15241 feat(influxdb): Add system buckets on org creation
  authorizer/bucket.go
  bolt/id_test.go
  bolt/lookup_service_test.go
  bucket.go
  cmd/influxd/launcher/launcher.go
  http/bucket_service.go
  http/influxdb/bucket.go
  http/swagger.yml
  http/write_handler.go
  http/write_handler_test.go
  inmem/bucket_service.go
  kv/bucket.go
  kv/lookup_service_test.go
  kv/org.go
  mock/bucket_service.go
  mock/generators.go
  storage/bucket_service.go
  storage/retention.go
  task/backend/analytical_storage.go
  task/backend/analytical_storage_test.go
  testing/organization_service.go
Labels: team/api, team/user-tools

#15531 fix(influxdb): fall back to legacy system buckets
  bucket.go
  ui/cypress/e2e/buckets.test.ts
  ui/cypress/e2e/labels.test.ts
Labels: area/api, team/user-tools

#14373 fix(tsdb): add missing err in SeriesPartition.Open
  tsdb/series_partition.go
Labels: stale-exempt

#15524 Update flux version to v0.50.2
  Gopkg.lock
  Gopkg.toml
  cmd/influx/cli/flux.go
  flux/control/controller.go
  flux/stdlib/influxdata/influxdb/buckets.go
  flux/stdlib/influxdata/influxdb/dependencies.go
  flux/stdlib/influxdata/influxdb/from.go
  flux/stdlib/influxdata/influxdb/from_test.go
  flux/stdlib/influxdata/influxdb/metrics.go
  flux/stdlib/influxdata/influxdb/operators.go
  flux/stdlib/influxdata/influxdb/rules.go
  flux/stdlib/influxdata/influxdb/rules_test.go
  flux/stdlib/influxdata/influxdb/source.go
  flux/stdlib/influxdata/influxdb/source_test.go
  flux/stdlib/influxdata/influxdb/storage.go
  flux/stdlib/influxdata/influxdb/v1/databases.go
  mock/storage_reads.go
  patches/flux.patch
  storage/reads/datatypes/storage_common.pb.go
  storage/reads/datatypes/storage_common.proto
  storage/reads/helpers_test.go
  storage/reads/reader.go
  storage/reads/reader_test.go
  storage/reads/response_writer.gen.go
  storage/reads/response_writer.go
  storage/reads/stream_reader.go
  storage/reads/stream_reader_test.go
  storage/reads/table.gen.go
  storage/reads/table.go
  tsdb/cursors/arrayvalues.gen.go
  tsdb/cursors/arrayvalues.go
Labels: kind/feature-request

#15293 test(query): add PromQL end-to-end tests in go submodule
  .circleci/config.yml
  Makefile
  cmd/influxd/launcher/launcher_helpers.go
  query/promql/internal/promqltests/README.md
  query/promql/internal/promqltests/end_to_end_test.go
  query/promql/internal/promqltests/engine.go
  query/promql/internal/promqltests/go.mod
  query/promql/internal/promqltests/go.sum
  query/promql/internal/promqltests/helpers.go
  query/promql/internal/promqltests/input.txt
  query/promql/internal/promqltests/tests.go
Labels: team/query

#15642 Update flux version to v0.50.2
  Gopkg.lock
  Gopkg.toml
  cmd/influx/cli/flux.go
  flux/control/controller.go
  flux/stdlib/influxdata/influxdb/buckets.go
  flux/stdlib/influxdata/influxdb/dependencies.go
  flux/stdlib/influxdata/influxdb/from.go
  flux/stdlib/influxdata/influxdb/from_test.go
  flux/stdlib/influxdata/influxdb/metrics.go
  flux/stdlib/influxdata/influxdb/operators.go
  flux/stdlib/influxdata/influxdb/rules.go
  flux/stdlib/influxdata/influxdb/rules_test.go
  flux/stdlib/influxdata/influxdb/source.go
  flux/stdlib/influxdata/influxdb/source_test.go
  flux/stdlib/influxdata/influxdb/storage.go
  flux/stdlib/influxdata/influxdb/v1/databases.go
  mock/storage_reads.go
  patches/flux.patch
  storage/reads/datatypes/storage_common.pb.go
  storage/reads/datatypes/storage_common.proto
  storage/reads/helpers_test.go
  storage/reads/reader.go
  storage/reads/reader_test.go
  storage/reads/response_writer.gen.go
  storage/reads/response_writer.go
  storage/reads/stream_reader.go
  storage/reads/stream_reader_test.go
  storage/reads/table.gen.go
  storage/reads/table.go
  tsdb/cursors/arrayvalues.gen.go
  tsdb/cursors/arrayvalues.go
Labels: kind/feature-request

#15646 feat(influxdb): Prevent the deletion of system buckets
  bucket.go
  http/bucket_service.go
  inmem/bucket_service.go
  kv/bucket.go
  testing/bucket_service.go
Labels: area/api, team/user-tools

#15675 fix(tasks): wire auth context down to scheduler runner
  task/backend/scheduler.go
Labels: area/tasks, kind/bug
