Repository influxdata/influxdb, pull requests merged in 2019-01, with the labels that each got.

#10584 Fix invalid UTF-8 bytes preventing shard opening
  tsdb/engine/tsm1/engine_test.go
  tsdb/internal/meta.pb.go
  tsdb/internal/meta.proto
  tsdb/shard.go
Labels: kind/bug, review

#10608 chore: update Flux to v0.12.0
  Gopkg.lock
  Gopkg.toml
Labels: review

#10613 Fixing date; capitalization of InfluxDB
  README.md
Labels: review

#10614 chore: Update Flux to 0.12.0
  Gopkg.lock
  Gopkg.toml
Labels: review

#10617 Fix panic in Prometheus read API
  services/httpd/handler.go
Labels: review

#10624 CHANGELOG updates for 1.6.5
  CHANGELOG.md
Labels: review

#10625 Fix release date
  CHANGELOG.md
Labels: review

#10664 Marked functions that always return floats as always returning floats
  query/functions.go
Labels: kind/bug, review

#10951 Marked functions that always return floats as always returning floats
  query/functions.go
Labels: kind/bug, review

#10950 Marked functions that always return floats as always returning floats
  query/functions.go
Labels: kind/bug, review

#10952 chore: temporarily treat appveyor as no-op
  appveyor.yml
Labels: review

#10949 chore: use upstream version of kin-openapi
  go.mod
  go.sum
Labels: review

#10996 Add support for optionally logging Flux queries
  etc/config.sample.toml
  services/httpd/config.go
  services/httpd/handler.go
Labels: kind/feature request, needs-backport/1.7

#10998 Add support for optionally logging Flux queries
  etc/config.sample.toml
  services/httpd/config.go
  services/httpd/handler.go
Labels: kind/feature request

#10957 add(gather): add writer interface
  bolt/scraper.go
  bolt/scraper_test.go
  cmd/influxd/launcher/launcher.go
  gather/README.md
  gather/handler.go
  gather/metrics.go
  gather/metrics_test.go
  gather/prometheus.go
  gather/recorder.go
  gather/scheduler.go
  gather/scheduler_test.go
  gather/scraper.go
  gather/scraper_test.go
  gather/storage.go
  http/api_handler.go
  http/scraper_service.go
  http/scraper_service_test.go
  inmem/scraper.go
  scraper.go
  testing/scraper_target.go
Labels: review

#10954 feat(tasks): update task options from api
  go.mod
  go.sum
  http/task_service.go
  query/functions/tests/placeholder.go
  task.go
  task/backend/bolt/bolt.go
  task/backend/inmem_store.go
  task/backend/store.go
  task/backend/storetest/storetest.go
  task/options/options.go
  task/platform_adapter.go
  task/servicetest/servicetest.go
  task_test.go
Labels: review

#11003 Fix Cardinality estimation error
  tsdb/index/tsi1/index.go
  tsdb/index/tsi1/log_file.go
  tsdb/index_test.go
  tsdb/store_test.go
Labels: kind/bug

#10948 Add organization to dashboards
  bolt/dashboard.go
  bolt/lookup_service_test.go
  dashboard.go
  http/dashboard_service.go
  http/dashboard_test.go
  http/proto.go
  http/proto_test.go
  inmem/dashboard.go
  testing/dashboards.go
Labels: review

#11525 Allow TSI bitset cache to be configured
  etc/config.sample.toml
  tsdb/config.go
  tsdb/config_test.go
  tsdb/index/tsi1/index.go
  tsdb/index/tsi1/index_test.go
  tsdb/index/tsi1/testdata/line-protocol-1M.txt.gz
  tsdb/index_test.go
Labels: kind/feature request, needs-backport/1.7

#11620 Add litmus test runs to nightly build
  .circleci/config.yml
Labels: Litmus
