Repository influxdata/influxdb, pull requests merged in 2019-07, with the labels that each got.

#14254 fix(tsdb): Fix tsm1 block merge.
  tsdb/tsm1/reader_block_iterator.go
Labels: area/tsm

#14232 Prevent data from re-appearing on startup in some cases
  tsdb/engine/tsm1/engine_test.go
  tsdb/engine/tsm1/wal.go
Labels: kind/bug

#14262 Storage reads should be in domain [start, end)
  storage/reads/datatypes/storage_common.proto
  tsdb/tsm1/array_cursor.gen.go
  tsdb/tsm1/array_cursor.gen.go.tmpl
Labels: kind/bug

#14264 Fix Prometheus read panic
  services/httpd/handler.go
Labels: 1.x, kind/bug

#14270 Remove stray fmt.Println in tsm1.StringArrayEncodeAll
  tsdb/engine/tsm1/batch_string.go
Labels: kind/bug

#14271 Remove stray fmt.Println in tsm1.StringArrayEncodeAll
  tsdb/engine/tsm1/batch_string.go
Labels: kind/bug

#14266 fix(storage): Fix issue where fields re-appear
  tests/server_delete_test.go
  tsdb/index/inmem/inmem.go
  tsdb/shard_test.go
Labels: kind/bug, needs-backport/1.7

#14287 fix(tasks) report errors found when iterating over flux query
  CHANGELOG.md
  task/backend/executor/executor.go
  task/backend/executor/task_executor.go
  task/backend/executor/task_executor_test.go
Labels: area/tasks

#14315 Update Go version to 1.12
  CHANGELOG.md
  CONTRIBUTING.md
  Dockerfile
  Dockerfile_build_ubuntu32
  Dockerfile_build_ubuntu64
  Dockerfile_build_ubuntu64_git
  Dockerfile_build_ubuntu64_go1.12
  Dockerfile_jenkins_ubuntu32
  Jenkinsfile
  appveyor.yml
  releng/_go_versions.sh
  services/httpd/response_writer_test.go
  test.sh
Labels: 1.x

#14307 Subquery ordering with aggregates in descending mode was wrong
  query/iterator.gen.go
  query/iterator.gen.go.tmpl
  query/subquery_test.go
Labels: kind/bug

#14369 fix(ui/cloud): update location for upgrade button
  ui/src/cloud/components/CheckoutButton.tsx
  ui/src/shared/constants/index.ts
Labels: team/control

#14286 Fix issue where fields re-appear after DROP MEASUREMENT
  tests/server_delete_test.go
  tsdb/index/inmem/inmem.go
  tsdb/shard_test.go
Labels: kind/bug

#14357 Subquery ordering with aggregates in descending mode was wrong
  query/iterator.gen.go
  query/iterator.gen.go.tmpl
  query/select.go
  query/subquery_test.go
Labels: kind/bug

#14402 Fix the http handler to not mislabel series as partial
  services/httpd/handler.go
  services/httpd/handler_test.go
  tests/server_test.go
Labels: kind/bug

#14421 Fix the http handler to not mislabel series as partial
  services/httpd/handler.go
  services/httpd/handler_test.go
  tests/server_test.go
Labels: kind/bug

#14480 fix: enforce bucket authentication on task update
  CHANGELOG.md
  authorizer/task.go
  authorizer/task_test.go
Labels: area/auth, area/tasks
