Repository influxdata/influxdb, pull requests merged in 2019-09, with the labels that each got.

#14902 fix(storage): replace TSI compaction wait group with counter.
  tsdb/tsi1/partition.go
Labels: area/storage, needs-backport/1.7, needs-backport/1.8

#14929 fix(tsi1): Remove TSI cardinality stats cache
  storage/engine.go
  tsdb/tsi1/config.go
  tsdb/tsi1/file_set.go
  tsdb/tsi1/index.go
  tsdb/tsi1/index_test.go
  tsdb/tsi1/partition.go
Labels: area/storage

#14935 fix(task): Create tags using NewTags to ensure they are sorted
  task/backend/analytical_storage.go
Labels: team/compute

#15127 feat(tsdb): Add SQL export for TSI indexes
  cmd/influxd/inspect/export_index.go
  cmd/influxd/inspect/inspect.go
  tsdb/explode.go
  tsdb/tsi1/sql_index_exporter.go
  tsdb/tsi1/sql_index_exporter_test.go
Labels: area/storage

#15182 fix(tsi1): replace TSI compaction wait group with counter
  tsdb/index/tsi1/partition.go
Labels: area/tsi

#15188 fix(tsi1): replace TSI compaction wait group with counter
  tsdb/index/tsi1/partition.go
Labels: area/tsi

#15174 refactor(dependencies): use new dependency injection framework
  cmd/influx/repl.go
  cmd/influxd/launcher/launcher.go
  cmd/influxd/launcher/query_test.go
  go.mod
  go.sum
  query/bridges.go
  query/control/controller.go
  query/control/controller_test.go
  query/stdlib/influxdata/influxdb/buckets.go
  query/stdlib/influxdata/influxdb/dependencies.go
  query/stdlib/influxdata/influxdb/from.go
  query/stdlib/influxdata/influxdb/metrics.go
  query/stdlib/influxdata/influxdb/source.go
  query/stdlib/influxdata/influxdb/source_test.go
  query/stdlib/influxdata/influxdb/storage.go
  query/stdlib/influxdata/influxdb/to.go
  query/stdlib/influxdata/influxdb/to_test.go
  query/stdlib/influxdata/influxdb/v1/databases.go
  storage/readservice/service.go
  storage/readservice/store.go
  storage/wal/verifier_test.go
  task/backend/analytical_storage_test.go
  task/options/options.go
  tsdb/tsm1/metrics_test.go
Labels: team/query

#15203 build(flux): update to Flux v0.48.0
  cmd/influx/repl.go
  cmd/influxd/launcher/launcher.go
  cmd/influxd/launcher/query_test.go
  go.mod
  go.sum
  query/bridges.go
  query/control/controller.go
  query/control/controller_test.go
  query/spec.go
  query/stdlib/influxdata/influxdb/buckets.go
  query/stdlib/influxdata/influxdb/dependencies.go
  query/stdlib/influxdata/influxdb/from.go
  query/stdlib/influxdata/influxdb/metrics.go
  query/stdlib/influxdata/influxdb/source.go
  query/stdlib/influxdata/influxdb/source_test.go
  query/stdlib/influxdata/influxdb/storage.go
  query/stdlib/influxdata/influxdb/to.go
  query/stdlib/influxdata/influxdb/to_test.go
  query/stdlib/influxdata/influxdb/v1/databases.go
  query/stdlib/testing/testing.go
  storage/readservice/service.go
  storage/readservice/store.go
  storage/wal/verifier_test.go
  task/backend/analytical_storage_test.go
  task/options/options.go
  tsdb/tsm1/metrics_test.go
Labels: team/query

#15148 fix(http): fixed http NotificationEndpoint
  http/notification_endpoint.go
  http/swagger.yml
  kv/notification_endpoint.go
  testing/notification_endpoint.go
Labels: area/api

#15150 fix(http): add ParenExpression
  http/swagger.yml
Labels: area/api

#15179 fix(alerts): remove the cron option from checks/rules
  http/swagger.yml
  notification/check/check.go
  notification/rule/rule.go
Labels: area/api

#15267 fix(influxdb): Always return user status
  bolt/user.go
  http/bucket_test.go
  http/check_test.go
  http/notification_endpoint_test.go
  http/user_resource_mapping_test.go
  http/user_service.go
  inmem/user_service.go
  testing/user_service.go
  user.go
Labels: team/api

#15178 fix(http): add discriminator for Check schema
  http/swagger.yml
Labels: area/api

#15216 fix(http/check): fix handler path for a list of all labels for a check
  http/check_service.go
Labels: area/api

#15198 fix(http): add a discriminator for a Threshold schema, add links into CheckBase schema
  http/swagger.yml
Labels: area/api

#15244 fix(http): update NotificationRuleBase and NotificationRule schema to reflect reality
  http/swagger.yml
Labels: area/api
