Repository influxdata/influxdb, pull requests merged in 2019-03, with the labels that each got.

#11617 Merge point parse & explode.
  gather/recorder.go
  http/write_handler.go
  models/points.go
  models/points_internal_test.go
  models/points_test.go
  query/stdlib/influxdata/influxdb/to.go
  query/stdlib/influxdata/influxdb/to_test.go
  storage/engine_test.go
  tsdb/explode.go
  tsdb/explode_test.go
  tsdb/index_test.go
  tsdb/tsm1/engine_delete_bucket_test.go
  tsdb/tsm1/engine_test.go
Labels: area/storage

#12319 Revert "Merge point parse & explode."
  gather/recorder.go
  http/write_handler.go
  models/points.go
  models/points_internal_test.go
  models/points_test.go
  query/stdlib/influxdata/influxdb/to.go
  query/stdlib/influxdata/influxdb/to_test.go
  storage/engine_test.go
  tsdb/explode.go
  tsdb/explode_test.go
  tsdb/index_test.go
  tsdb/tsm1/engine_delete_bucket_test.go
  tsdb/tsm1/engine_test.go
Labels: kind/bug

#12615 Migrate influxd binary to cobra Command package
  CHANGELOG.md
  build.go
  cmd/influxd/launcher/launcher.go
  cmd/influxd/main.go
  go.sum
  kit/cli/viper.go
Labels: area/cli

#11964 Add 2.0 support for `report-tsm` tool
  cmd/influx/debug.go
  cmd/influx/inspect.go
  cmd/influxd/inspect/inspect.go
  cmd/influxd/main.go
  go.sum
  tsdb/tsm1/array_cursor_iterator.go
  tsdb/tsm1/engine.go
  tsdb/tsm1/report.go
Labels: area/tooling

#12813 Drop all unsupported Prometheus values written to the remote write endpoint
  prometheus/converters.go
  services/httpd/handler.go
  services/httpd/handler_test.go
Labels: 1.x, area/writes
