Repository influxdata/influxdb, pull requests merged in 2019-02, with the labels that each got.

#10276 Fix bug with incorrect ABS results for negative integer values
  query/iterator.go
  query/math.go
  query/math_test.go
  services/continuous_querier/service.go
Labels: kind/bug, proposed

#10336 Fix linting errors in the errlist package
  cmd/influx_tools/internal/errlist/errlist.go
Labels: proposed

#10401 Fix lint warnings snapshotter
  services/snapshotter/client.go
Labels: proposed

#10403 Fix golint warnings for services/graphite
  services/graphite/parser.go
Labels: proposed

#9944 Hash ring's hash mod
  tsdb/engine/tsm1/ring.go
Labels: community-pr, proposed

#10438 to fix the dead link to InfluxQL in the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: area/documentation, proposed

#10484 chore: install gcc
  releng/unit-tests/Dockerfile
Labels: review

#10392 Fix misspelling identified by misspell
  models/points.go
  models/time.go
  pkg/encoding/simple8b/encoding.go
  pkg/estimator/hll/hll.go
  query/call_iterator.go
  query/executor.go
  query/iterator.go
  query/select.go
  services/httpd/handler_test.go
  stress/config.go
  stress/v2/stress_client/stress_client.go
  tests/server_test.go
  tsdb/engine/tsm1/batch_integer_test.go
  tsdb/engine/tsm1/bool.go
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
  tsdb/engine/tsm1/file_store.go
  tsdb/engine/tsm1/int_test.go
  tsdb/engine/tsm1/reader.go
  tsdb/engine/tsm1/timestamp.go
  tsdb/engine/tsm1/wal.go
  tsdb/index.go
  tsdb/index/tsi1/tsi1.go
  tsdb/series_segment.go
Labels: community-pr, proposed

#10350 Golint logger package
  logger/config.go
  logger/context.go
  logger/fields.go
  logger/logger.go
Labels: community-pr, proposed

#10505 Do not rebuild series index on delete for series not overlapping in time
  CHANGELOG.md
  tsdb/engine/tsm1/engine.go
Labels: community-pr, proposed

#10546 clientv2 - QueryCtx()
  client/v2/client.go
  client/v2/udp.go
Labels: community-pr, proposed

#9916 add test case for #9522
  tests/server_test.go
Labels: community-pr, proposed

#10502 No rebuild series index on delete when the series still exists in cache
  CHANGELOG.md
  tsdb/engine/tsm1/engine.go
Labels: community-pr, proposed

#10522 Fix compaction logic on infrequent cache snapshots
  tsdb/engine/tsm1/engine.go
Labels: community-pr, proposed

#10414 reuse ValuerEval objects
  query/cursor.go
  tsdb/engine/tsm1/iterator.gen.go
  tsdb/engine/tsm1/iterator.gen.go.tmpl
Labels: community-pr, kind/feature request

#11742 Use Systemd for Amazon Linux 2
  scripts/post-install.sh
  scripts/post-uninstall.sh
Labels: kind/bug

#11743 Backport: Use Systemd for Amazon Linux 2
  scripts/post-install.sh
  scripts/post-uninstall.sh
Labels: kind/bug

#11604 Allow TSI bitset cache to be configured
  etc/config.sample.toml
  tsdb/config.go
  tsdb/config_test.go
  tsdb/index/tsi1/index.go
  tsdb/index/tsi1/index_test.go
  tsdb/index/tsi1/testdata/line-protocol-1M.txt.gz
  tsdb/index_test.go
Labels: kind/feature request

#11747 enable Litmus Smoke tests on daily PRs
  .circleci/config.yml
  etc/litmus_fail_notify.sh
  etc/litmus_success_notify.sh
Labels: Litmus

#10591 [BUG FIX] Fix nil pointer dereference at /api/v1/prom/read
  services/httpd/handler.go
  services/httpd/handler_test.go
Labels: community-pr, proposed

#11785 use attach_workspace for litmus nightly builds
  .circleci/config.yml
Labels: Litmus

#10206 Fix legacy restore bug #10072
  CHANGELOG.md
  cmd/influxd/restore/restore.go
Labels: community-pr, proposed

#10332 Simplify s[:] to s where s is a slice
  services/snapshotter/service.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/reader.go
  tsdb/index/tsi1/index.go
  tsdb/index/tsi1/partition.go
Labels: community-pr, proposed

#10375 Modify context key type
  logger/context.go
  pkg/metrics/context.go
  pkg/tracing/context.go
  query/execution_context.go
  query/executor.go
  query/monitor.go
Labels: community-pr, proposed

#11792 Revert "Limit force-full and cold compaction size."
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
Labels: kind/bug

#11791 Revert "Limit force-full and cold compaction size."
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/store.go
Labels: kind/bug

#11829 Convert TagValueSeriesIDCache to use string fields.
  pkg/tracing/context.go
  query/executor.go
  tsdb/index/tsi1/cache.go
Labels: kind/bug

#11831 Convert TagValueSeriesIDCache to use string fields
  tsdb/index/tsi1/cache.go
Labels: kind/bug

#11834 Convert TagValueSeriesIDCache to use string fields
  tsdb/tsi1/cache.go
Labels: kind/bug

#11833 Ensure that cached series id sets are Go heap backed
  tsdb/index/tsi1/cache.go
  tsdb/index/tsi1/cache_test.go
Labels: kind/bug

#11832 Ensure that cached series id sets are Go heap backed
  tsdb/index/tsi1/cache.go
  tsdb/index/tsi1/cache_test.go
Labels: kind/bug

#11750 Update tagKeyValue mutex to write lock.
  tsdb/index/inmem/meta.go
Labels: kind/bug

#11908 Update tagKeyValue mutex to write lock.
  tsdb/index/inmem/meta.go
Labels: kind/bug

#11909 Update tagKeyValue mutex to write lock.
  tsdb/index/inmem/meta.go
Labels: kind/bug

#10541 Fix open/close race in SeriesFile
  tsdb/series_file.go
  tsdb/series_file_test.go
Labels: community-pr, kind/bug, proposed

#11970 Fix some more shard epoch races
  tsdb/store.go
Labels: needs-backport/1.7
