Repository influxdata/influxdb, pull requests merged in 2020-07, with the labels that each got.

#18824 feat(storage): Add logging points writer
  cmd/influxd/launcher/launcher.go
  mock/points_writer.go
  storage/points_writer.go
  storage/points_writer_test.go
Labels: area/storage, team/storage

#18849 chore(build): remove all of the go1.12 references from build
  .circleci/config.yml
  CONTRIBUTING.md
  Dockerfile_build_ubuntu64_go1.12
  Dockerfile_jenkins_ubuntu32
  test.sh
Labels: area/build

#18847 fix(storage): Refactor LoggingPointsWriter to use BucketFinder
  cmd/influxd/launcher/launcher.go
  storage/points_writer.go
  storage/points_writer_test.go
Labels: area/storage, team/storage

#17814 feat(prometheus): update prometheus remote protocol
  go.mod
  go.sum
  prometheus/converters.go
  prometheus/remote/generate.go
  prometheus/remote/remote.pb.go
  prometheus/remote/remote.proto
  services/httpd/handler.go
  services/httpd/handler_test.go
  tests/server_test.go
Labels: 1.x

#18892 chore: update CHANGELOG.md
  CHANGELOG.md
Labels: team/qa

#18894 feat(storage): InfluxQL schema APIs without time range
  storage/engine_measurement_notime_schema.go
  tsdb/cursors/schema.go
  tsdb/tsm1/engine_measurement_notime_schema.go
  tsdb/tsm1/engine_measurement_notime_schema_test.go
  tsdb/tsm1/engine_measurement_schema.go
Labels: area/influxql, area/performance

#18901 feat(tsdb): Add CreatedAt field for tsm1.FileStat
  tsdb/tsm1/file_store.go
  tsdb/tsm1/reader.go
  tsdb/tsm1/tombstone.go
Labels: area/storage, team/storage

#18913 fix(storage): Reduce the check frequency
  tsdb/tsm1/engine_schema.go
Labels: area/influxql, area/performance

#18982 feat(mincore): Add page fault limiter
  cmd/influxd/launcher/launcher.go
  pkg/mincore/limiter.go
  pkg/mincore/limiter_test.go
  pkg/mincore/mincore_unix.go
  pkg/mincore/mincore_windows.go
  storage/engine.go
  tsdb/tsm1/engine.go
  tsdb/tsm1/file_store.go
  tsdb/tsm1/reader.gen.go
  tsdb/tsm1/reader.gen.go.tmpl
  tsdb/tsm1/reader.go
  tsdb/tsm1/reader_mmap.go
Labels: area/storage, team/storage

#19018 feat(tsdb): Add optional mincore limiter to TSI & Series File
  pkg/mincore/limiter.go
  storage/engine.go
  tsdb/seriesfile/series_file.go
  tsdb/seriesfile/series_index.go
  tsdb/seriesfile/series_partition.go
  tsdb/seriesfile/series_segment.go
  tsdb/tsi1/index.go
  tsdb/tsi1/index_file.go
  tsdb/tsi1/index_files.go
  tsdb/tsi1/log_file.go
  tsdb/tsi1/measurement_block.go
  tsdb/tsi1/measurement_block_test.go
  tsdb/tsi1/partition.go
  tsdb/tsi1/tag_block.go
  tsdb/tsi1/tag_block_test.go
  tsdb/tsi1/tsi1.go
  tsdb/tsi1/tsi1_test.go
Labels: area/storage, team/storage

#19085 feat(httpc): add error return argument to auth func
  pkg/httpc/client.go
  pkg/httpc/options.go
  pkg/httpc/req.go
Labels: proposed
