Repository influxdata/influxdb, pull requests merged in 2020-04, with the labels that each got.

#17530 fix(go.mod): Update go version in mod file to 1.13
  go.mod
Labels: 1.x

#17383 fix(authorizer): fix auth for authorizations
  authorizer/auth.go
  authorizer/auth_test.go
  authorizer/authorize_find.go
Labels: team/compute

#17532 fix(tsdb): Replace panic with error while de/encoding corrupt data
  tsdb/engine/tsm1/compact.gen.go
  tsdb/engine/tsm1/compact.gen.go.tmpl
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/digest.go
  tsdb/engine/tsm1/encoding.go
  tsdb/engine/tsm1/encoding_test.go
  tsdb/engine/tsm1/file_store.go
  tsdb/engine/tsm1/reader_test.go
Labels: 1.x, area/tsm

#17563 fix: Invariant violated: mixed block types for a single series
  tsdb/tsm1/cache.go
  tsdb/tsm1/cache_entry.go
  tsdb/tsm1/encoding.go
  tsdb/tsm1/engine.go
Labels: area/storage, team/storage

#17453 feat(storage): Measurement(Names|TagKeys|TagValues) schema APIs
  models/points.go
  models/points_test.go
  storage/engine_measurement_schema.go
  tsdb/cursors/schema.go
  tsdb/tsm1/engine_measurement_schema.go
  tsdb/tsm1/engine_measurement_schema_test.go
  tsdb/tsm1/engine_schema.go
Labels: area/influxql

#17598 feat(kv): add ability to configure a max permissions using auth filter function
  kv/service.go
  kv/session.go
  kv/task.go
  task/servicetest/servicetest.go
Labels: area/feature flags

#17597 fix(tenant): make storage pass tenant tests
  tenant/error.go
  tenant/service_bucket.go
  tenant/service_test.go
  tenant/service_urm_test.go
  tenant/storage_bucket.go
  tenant/storage_urm.go
  tenant/storage_urm_test.go
  tenant/storage_user.go
  testing/tenant.go
  testing/user_resource_mapping_service.go
Labels: team/compute

#17610 fix(storage): Fix query cursor read that caused cursor truncation.
  storage/reads/array_cursor.gen.go
  storage/reads/array_cursor.gen.go.tmpl
  storage/reads/array_cursor_test.go
Labels: area/storage, team/storage

#17638 fix: verify precision parameter in write requests
  CHANGELOG.md
  services/httpd/handler.go
  services/httpd/handler_test.go
Labels: 1.x, needs-backport/1.8

#17589 feat(tsm1): Implementation of MeasurementFields schema API
  tsdb/cursors/arrayvalues.go
  tsdb/cursors/schema.go
  tsdb/tsm1/cache.go
  tsdb/tsm1/cache_entry.go
  tsdb/tsm1/encoding.go
  tsdb/tsm1/engine.go
  tsdb/tsm1/engine_measurement_schema.go
  tsdb/tsm1/engine_measurement_schema_test.go
  tsdb/tsm1/engine_schema.go
  tsdb/tsm1/file_store.go
  tsdb/tsm1/reader.go
  tsdb/tsm1/reader_range_iterator.go
  tsdb/tsm1/reader_range_iterator_test.go
  tsdb/tsm1/reader_range_maxtime_iterator.go
  tsdb/tsm1/reader_range_maxtime_iterator_test.go
Labels: area/influxql

#17712 Update CHANGELOG.md
  CHANGELOG.md
Labels: 1.x

#17698 fix(tls): Enable configuration of TLS 1.3
  CHANGELOG.md
  etc/config.sample.toml
  pkg/tlsconfig/tls_config.go
Labels: 1.x, area/auth

#17716 chore: update changelog
  CHANGELOG.md
Labels: 1.x

#17707 fix(models): Optimize allocations in NewPoint()
  models/points.go
Labels: area/storage, team/storage

#17722 fix(tsdb): Revert "fix: remove some unsafe marshalling to reduce risk…
  cmd/influxd/backup_util/backup_util.go
  tests/backup_restore_test.go
  tsdb/index/tsi1/index_file.go
  tsdb/index/tsi1/measurement_block.go
  tsdb/index/tsi1/tag_block.go
  tsdb/series_set_test.go
Labels: 1.x

#17728 chore(storage): Remove redundant gRPC service from protobuf definition
  storage/reads/datatypes/storage_common.pb.go
  storage/reads/datatypes/storage_common.proto
Labels: area/influxql

#17737 feat(storage): Provide public MeasurementFields API
  storage/engine_measurement_schema.go
  storage/engine_schema.go
  tsdb/tsm1/engine_measurement_schema.go
  tsdb/tsm1/engine_schema.go
Labels: area/influxql

#17745 feat(storage): New data types for measurement schema gRPC APIs
  go.mod
  go.sum
  storage/engine_measurement_schema.go
  storage/reads/datatypes/predicate.pb.go
  storage/reads/datatypes/storage_common.pb.go
  storage/reads/datatypes/storage_common.proto
  tsdb/cursors/fieldtype_string.go
  tsdb/cursors/gen.go
  tsdb/cursors/schema.go
  tsdb/cursors/schema_test.go
  tsdb/tsm1/engine_measurement_schema.go
  tsdb/tsm1/engine_measurement_schema_test.go
Labels: area/influxql

#17818 chore(build): start running nightly builds 2hour earlier
  .circleci/config.yml
Labels: team/qa

#17063 feat(influxdb): Backport modules to 1.7.x
  CONTRIBUTING.md
  Dockerfile
  Dockerfile_build_ubuntu32
  Dockerfile_build_ubuntu64
  Dockerfile_build_ubuntu64_git
  Dockerfile_jenkins_ubuntu32
  Gopkg.lock
  Gopkg.toml
  Jenkinsfile
  build.py
  build.sh
  go.mod
  go.sum
  query/internal/gota/cmo_test.go
  query/internal/gota/trix_test.go
  test.sh
  tsdb/engine/tsm1/file_store_key_iterator_test.go
  tsdb/engine/tsm1/ring_test.go
Labels: 1.x

#17878 feat(storage): Add compaction enablement API to Engine.
  storage/engine.go
Labels: team/storage
