Repository influxdata/influxdb, pull requests merged in 2020-06, with the labels that each got.

#18566 fix(tsdb): Add refs for file-sourced tag keys
  tsdb/tsm1/engine_schema.go
Labels: area/storage, team/storage

#17243 chore(tsdb): clean up unused ShardID in EngineOptions
  tsdb/engine.go
Labels: 1.x

#17381 chore(dumptsm): clean up dead code
  cmd/influx_inspect/dumptsm/dumptsm.go
Labels: 1.x

#18013 chore: fix code format
  _tools/tmpl/main.go
  _tools/tmpl/main_test.go
  cmd/influxd/backup_util/backup_util.go
  tests/backup_restore_test.go
Labels: 1.x

#17596 improvement(query): performance improvement for sorted merge iterator
  query/iterator.gen.go
  query/iterator.gen.go.tmpl
  query/iterator.gen_test.go
Labels: 1.x, area/performance

#18429 fix(httpd): add user authentication for prometheus remote read api
  CHANGELOG.md
  etc/config.sample.toml
  services/httpd/config.go
  services/httpd/handler.go
Labels: 1.x

#18664 feat(storage): Add option to disable WritePoints() validation.
  models/points_test.go
  storage/engine.go
Labels: area/storage, team/storage

#18077 perf(tsi1): batch write tombstone entries when dropping/deleting
  tsdb/engine/tsm1/engine.go
  tsdb/index.go
  tsdb/index/inmem/inmem.go
  tsdb/index/tsi1/index.go
  tsdb/index/tsi1/index_test.go
  tsdb/index/tsi1/log_file.go
  tsdb/index/tsi1/partition.go
Labels: 1.x, area/storage

#17254 fix(tsi1): wait deleting epoch before dropping shard
  tsdb/store.go
Labels: 1.x, area/storage

#18694 fix(tsi1): wait deleting epoch before dropping shard
  tsdb/store.go
Labels: 1.x, area/storage

#18695 fix(tsi1): wait deleting epoch before dropping shard
  tsdb/store.go
Labels: 1.x, area/storage

#18689 perf(tsi1): batch write tombstone entries when dropping/deleting
  tsdb/engine/tsm1/engine.go
  tsdb/index.go
  tsdb/index/inmem/inmem.go
  tsdb/index/tsi1/index.go
  tsdb/index/tsi1/index_test.go
  tsdb/index/tsi1/log_file.go
  tsdb/index/tsi1/partition.go
Labels: 1.x, area/storage

#18687 perf(tsi1): batch write tombstone entries when dropping/deleting
  tsdb/engine/tsm1/engine.go
  tsdb/index.go
  tsdb/index/inmem/inmem.go
  tsdb/index/tsi1/index.go
  tsdb/index/tsi1/index_test.go
  tsdb/index/tsi1/log_file.go
  tsdb/index/tsi1/partition.go
Labels: 1.x, area/storage

#18410 fix(handler): allow CORS in v2 compatibility endpoints
  CHANGELOG.md
  services/httpd/handler.go
  services/httpd/handler_test.go
Labels: 1.x

#17319 fix(flux): buckets call no longer panics
  flux/stdlib/influxdata/influxdb/buckets.go
  patches/flux.patch
Labels: 1.x
