Repository influxdata/influxdb, pull requests merged in 2020-01, with the labels that each got.

#16530 fix(storage): prevent infinite loop in predicate matcher
  tsdb/tsm1/predicate.go
  tsdb/tsm1/predicate_test.go
Labels: kind/bug

#16524 fix(tsm1): Compaction log error
  CHANGELOG.md
  tsdb/engine/tsm1/engine.go
Labels: 1.x

#16651 chore: changelog updated for 1.7.10 GA
  CHANGELOG.md
Labels: team/qa
