Repository influxdata/influxdb, pull requests merged in 2020-05, with the labels that each got.

#18004 fix(httpd): Fixes key collisions when serializing /debug/vars
  services/httpd/handler.go
  services/httpd/handler_test.go
Labels: 1.x

#18018 fix(reads): Fix ResultSetToLineProtocol to generate correct output
  mock/reads_resultset.go
  mock/reads_resultset_test.go
  storage/reads/resultset_lineprotocol.go
Labels: area/influxql

#17800 feat: dbrp service
  authorizer/authorize_find.go
  authz.go
  cmd/influx/authorization.go
  cmd/influxd/launcher/launcher.go
  dbrp/error.go
  dbrp/http_client_dbrp.go
  dbrp/http_client_dbrp_test.go
  dbrp/http_server_dbrp.go
  dbrp/http_server_dbrp_test.go
  dbrp/middleware_auth.go
  dbrp/middleware_auth_test.go
  dbrp/service.go
  dbrp/service_test.go
  dbrp_mapping.go
  http/api_handler.go
  http/client.go
  http/swagger.yml
  mock/dbrp_mapping.go
  testing/dbrp_mapping_v2.go
Labels: area/HTTP, area/influxql

#18096 feat(http): Client disconnections should return a HTTP 499 error code.
  authorization/http_server.go
  http/bucket_service.go
  http/org_service.go
  kit/transport/http/api.go
  kit/transport/http/api_test.go
  kit/transport/http/error_handler.go
  pkger/http_server.go
  session/http_server.go
  tenant/http_handler_urm.go
  tenant/http_server.go
  tenant/http_server_bucket.go
  tenant/http_server_onboarding.go
  tenant/http_server_org.go
  tenant/http_server_user.go
Labels: area/HTTP, team/storage

#18114 fix(dbrp): Fix API interface calls
  dbrp/http_server_dbrp.go
Labels: area/HTTP, team/storage

#18014 chore: clean up unused functions
  internal/tsdb_store.go
  tsdb/engine.go
  tsdb/engine/tsm1/engine.go
  tsdb/shard.go
  tsdb/store.go
Labels: 1.x

#18158 fix(tsdb): Disable series id set cache size by default.
  tsdb/config.go
Labels: area/storage, team/storage

#18203 fix(tsdb): Defer closing of underlying SeriesIDSetIterators
  tsdb/index.go
Labels: area/storage, team/storage

#18211 fix(dbrpv2): reflect match count correctly
  dbrp/service.go
  testing/dbrp_mapping_v2.go
Labels: area/influxql

#18212 fix(tsdb): Defer closing of underlying SeriesIDSetIterators
  tsdb/index.go
Labels: area/storage, team/storage

#18213 fix(tsdb): Defer closing of underlying SeriesIDSetIterators
  tsdb/index.go
Labels: area/storage, team/storage

#18232 chore: update changelog with 1.7.11 entry
  CHANGELOG.md
Labels: team/qa

#18286 fix(tsdb): Disable series id set cache size by default.
  tsdb/config.go
Labels: area/storage, team/storage
