Repository influxdata/influxdb, pull requests merged in 2020-09, with the labels that each got.

#19480 chore: remove algo-w branch from nightly builds
  .circleci/config.yml
Labels: area/2.x, area/build

#19497 feat: Create initial stubs for influxd upgrade command
  cmd/influxd/main.go
  cmd/influxd/upgrade/upgrade.go
  cmd/influxd/upgrade/v1_dump_meta.go
  cmd/influxd/upgrade/v2_dump_meta.go
Labels: area/2.x

#19525 feat: Port shard pre-creation service from InfluxDB 1.x
  cmd/influxd/launcher/launcher.go
  storage/config.go
  storage/engine.go
  v1/services/precreator/README.md
  v1/services/precreator/config.go
  v1/services/precreator/config_test.go
  v1/services/precreator/service.go
  v1/services/precreator/service_test.go
Labels: area/2.x

#19567 chore(packaging): build rpm and deb packages
  .circleci/config.yml
  .goreleaser.yml
  Makefile
  cmd/influxd/launcher/launcher.go
  scripts/influxdb.service
  scripts/init.sh
  scripts/logrotate
  scripts/post-install.sh
  scripts/post-uninstall.sh
  scripts/pre-install.sh
Labels: area/2.x, area/build, area/packaging

#19583 fix: ShardGroupDuration is updated for retention period updates
  cmd/influxd/launcher/storage_test.go
  storage/engine.go
Labels: area/2.x

#19609 feat: Add -lponly flag to export sub-command
  cmd/influx_inspect/export/export.go
Labels: 1.x

#19611 feat: Backport lponly feature to 1.8
  cmd/influx_inspect/export/export.go
Labels: 1.x

#19420 fix: lock map before writes
  tsdb/index/tsi1/log_file.go
Labels: 1.x

#19619 chore(build): packages signing
  .circleci/config.yml
  .goreleaser.yml
Labels: area/2.x, area/packaging

#19624 chore: update circleci config to use golang:1.15 images
  .circleci/config.yml
  bolt/bbolt.go
  bolt/id.go
  bolt/kv.go
  bolt/metrics.go
  chronograf/bolt/base.go
  chronograf/bolt/build.go
  chronograf/bolt/change_interval_to_duration.go
  chronograf/bolt/client.go
  chronograf/bolt/config.go
  chronograf/bolt/dashboards.go
  chronograf/bolt/layouts.go
  chronograf/bolt/mapping.go
  chronograf/bolt/org_config.go
  chronograf/bolt/organizations.go
  chronograf/bolt/servers.go
  chronograf/bolt/sources.go
  chronograf/bolt/users.go
  chronograf/server/server.go
  go.mod
  go.sum
Labels: area/2.x, area/build

#19631 fix(CORS): allow PATCH
  services/httpd/handler.go
Labels: 1.x

#19638 chore: do not use apk command
  releng/unit-tests/Dockerfile
Labels: area/build

#19647 chore: revert signature changes to goreleaser
  .circleci/config.yml
  .goreleaser.yml
Labels: area/2.x, area/build, area/packaging

#19670 chore: update CHANGELOG for 1.8.3GA
  CHANGELOG.md
Labels: 1.x, area/documentation
