Repository influxdata/influxdb, pull requests merged in 2020-11, with the labels that each got.

#19902 chore: do not build arm arch
  .goreleaser.yml
Labels: area/2.x, area/build

#19900 chore: make 2.0 RC builds optional
  .circleci/config.yml
Labels: area/2.x

#19893 fix: Upgrade version of jwt-go package to v4.0.0
  go.mod
  go.sum
  services/httpd/handler.go
  services/httpd/handler_test.go
Labels: 1.x

#19908 fix(http): fix /ready response content type
  CHANGELOG.md
  http/ready.go
  http/ready_test.go
Labels: area/HTTP

#19864 feat: Implement backup/restore CLI subcommands
  authorizer/backup.go
  authorizer/restore.go
  backup.go
  bolt/kv.go
  bucket.go
  cmd/influx/backup.go
  cmd/influx/main.go
  cmd/influx/restore.go
  cmd/influxd/launcher/engine.go
  cmd/influxd/launcher/launcher.go
  cmd/influxd/restore/command.go
  http/api_handler.go
  http/backup_service.go
  http/restore_service.go
  inmem/kv.go
  kv/service_test.go
  kv/store.go
  mock/kv.go
  storage/engine.go
  tsdb/engine/tsm1/engine.go
  tsdb/store.go
  v1/services/meta/client.go
  v1/services/meta/data.go
  v1/services/meta/filestore/kv.go
Labels: area/backup and restore

#19956 chore: Improve help for --no-password switch
  cmd/influx/v1_authorization.go
Labels: area/2.x

#19918 chore(swagger): add operationId to /delete
  http/swagger.yml
Labels: area/HTTP

#20003 chore: Remove fragile nats port assignment code
  cmd/influxd/launcher/launcher.go
  go.mod
  go.sum
  nats/server.go
Labels: area/2.x

#20033 fix(tsm1): "snapshot in progress" error during backup
  tsdb/engine.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_internal_test.go
  tsdb/shard.go
  tsdb/shard_test.go
  tsdb/store.go
  tsdb/store_test.go
Labels: 1.x, area/backup and restore, team/edge

#20063 fix(tsm1): "snapshot in progress" error during backup: restore loop with backoff
  tsdb/engine/tsm1/engine.go
Labels: 1.x, area/backup and restore, area/error handling, team/edge, work in progress

#20086 fix: UX improvements and bug fixes to dbrp commands
  cmd/influx/v1_dbrp.go
Labels: area/2.x

#20094 chore: update goreleaser nightly to be inline with daily/release builds
  .goreleaser-nightly.yml
Labels: area/2.x, area/build, area/packaging

#20111 chore: use influxdb2 name for packaging
  .goreleaser-nightly.yml
  .goreleaser.yml
  scripts/post-install.sh
Labels: area/2.x, area/packaging

#20112 chore: remove nightly and hourly e2e jobs
  .circleci/config.yml
Labels: area/2.x, area/build

#20100 fix(write): Successful writes increment write error statistics incorrectly
  coordinator/points_writer.go
Labels: 1.x, area/writes, kind/bug, needs-backport/1.8, team/edge

#20101 fix(write): Successful writes increment write error statistics incorrectly
  CHANGELOG.md
  coordinator/points_writer.go
Labels: 1.x, area/writes, kind/bug, team/edge

#20210 chore(build): add grace test runs to daily PR checks
  .circleci/config.yml
Labels: area/2.x, area/build
