Repository influxdata/influxdb, pull requests merged in 2020-08, with the labels that each got.

#19169 chore: update task tests to use the tenant service
  cmd/influxd/launcher/launcher.go
  kv/task_test.go
  task/backend/analytical_storage_test.go
  task/servicetest/servicetest.go
  tenant/http_server_onboarding_test.go
  tenant/service.go
  tenant/service_onboarding.go
  tenant/service_onboarding_test.go
  tenant/service_org.go
Labels: area/2.x

#19191 feat(pkger): add query parameterization
  cmd/influxd/launcher/pkger_test.go
  http/swagger.yml
  pkger/clone_resource.go
  pkger/models.go
  pkger/models_test.go
  pkger/parser.go
  pkger/parser_models.go
  pkger/parser_test.go
  pkger/service.go
  pkger/service_test.go
  pkger/testdata/dashboard_params.yml
Labels: area/templates

#19233 feat(pkger): parameterize task queries
  cmd/influxd/launcher/pkger_test.go
  pkger/parser.go
  pkger/parser_models.go
  pkger/parser_test.go
  pkger/service_models.go
  pkger/testdata/tasks_params.yml
Labels: area/templates

#19237 fix: use backslash for line breaker
  .circleci/config.yml
Labels: area/build, team/qa

#19135 feat(notification/telegram): add telegram notification
  CHANGELOG.md
  http/swagger.yml
  notification/endpoint/endpoint.go
  notification/endpoint/endpoint_test.go
  notification/endpoint/telegram.go
  notification/rule/rule.go
  notification/rule/rule_test.go
  notification/rule/telegram.go
  notification/rule/telegram_test.go
  ui/src/notifications/endpoints/components/EndpointCards.tsx
  ui/src/notifications/endpoints/components/EndpointOptions.tsx
  ui/src/notifications/endpoints/components/EndpointOptionsTelegram.tsx
  ui/src/notifications/endpoints/components/EndpointOverlay.reducer.ts
  ui/src/notifications/endpoints/components/EndpointTypeDropdown.tsx
  ui/src/notifications/endpoints/components/EndpointsColumn.tsx
  ui/src/notifications/rules/components/RuleMessageContents.tsx
  ui/src/notifications/rules/components/TelegramMessage.tsx
  ui/src/notifications/rules/utils/index.ts
  ui/src/shared/selectors/flags.ts
  ui/src/types/alerting.ts
Labels: team/monitoring

#19187 feat: Collect values written stats
  coordinator/points_writer.go
  services/httpd/handler.go
  services/httpd/service.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
  tsdb/shard.go
  tsdb/store.go
Labels: 1.x, needs-backport/1.8

#19323 refactor: Simplify verifyVersion()
  tsdb/engine/tsm1/reader.go
  tsdb/engine/tsm1/reader_test.go
  tsdb/engine/tsm1/writer.go
Labels: 1.x, needs-backport/1.8

#19329 chore: update CHANGELOG
  CHANGELOG.md
Labels: 1.x, area/build

#19219 feat(paging): add support for after id parameter in find options
  CHANGELOG.md
  http/swagger.yml
  kv/bucket.go
  paging.go
  tenant/storage_bucket.go
  tenant/storage_bucket_test.go
  testing/bucket_service.go
Labels: work in progress

#19460 chore: Use latest version of influxql package
  go.mod
  go.sum
Labels: 1.x

#19458 chore: do not use alpine image, it does not have gcc compiler.
  releng/unit-tests/Dockerfile
Labels: 1.x, area/build
