Repository influxdata/influxdb, pull requests merged in 2020-03, with the labels that each got.

#16709 fix(flux): Reduce influxd and influx startup time if Flux unused
  CHANGELOG.md
  cmd/influx/cli/flux.go
  cmd/influxd/run/server.go
  flux/builtin/builtin.go
  flux/control/controller.go
Labels: 1.x

#17093 fix(http): fix auth in document handler
  authorizer/authorize.go
  authorizer/document.go
  authorizer/label.go
  document.go
  http/api_handler.go
  http/document_service.go
  http/document_service_test.go
  http/document_test.go
  kv/document.go
  kv/document_options.go
  mock/document_service.go
  testing/document.go
Labels: team/compute

#17201 fix(authorizer): fix endpoint handler auth
  authorizer/notification_endpoint.go
  authorizer/notification_endpoint_test.go
  http/notification_endpoint.go
Labels: team/compute

#15952 feat(inspect): add influx_inspect verify-tombstone tool
  cmd/influx_inspect/main.go
  cmd/influx_inspect/verify/tombstone/verify.go
  cmd/influx_tools/compact/command.go
  tsdb/engine/tsm1/tombstone.go
  tsdb/engine/tsm1/tombstone_test.go
Labels: 1.x

#17185 feat(storage): Series File Compaction
  cmd/influxd/inspect/compact_series_file.go
  cmd/influxd/inspect/inspect.go
  tsdb/series_file.go
  tsdb/series_file_test.go
  tsdb/series_partition.go
  tsdb/series_segment.go
Labels: area/storage

#17219 refactor(authorizer): make document permission in line with other ser…
  authorizer/document.go
Labels: team/compute

#17187 build(flux): update Flux to v0.64.0
  flux/stdlib/influxdata/influxdb/rules.go
  flux/stdlib/influxdata/influxdb/rules_test.go
  flux/stdlib/influxdata/influxdb/to.go
  flux/stdlib/influxdata/influxdb/to_test.go
  go.mod
  go.sum
  patches/cursors.patch
  patches/flux.patch
  patches/storage.patch
  storage/reads/datatypes/gen.go
  storage/reads/flux_predicate.go
  storage/reads/flux_reader.go
  storage/reads/flux_table.gen.go
  storage/reads/flux_table.go
  storage/reads/flux_table_test.go
  storage/reads/flux_tags_cache.go
  storage/reads/gen.go
  storage/reads/group_resultset.go
  storage/reads/influxql_eval.go
  storage/reads/influxql_expr.go
  storage/reads/influxql_predicate.go
  storage/reads/influxql_predicate_test.go
  storage/reads/keymerger.go
  storage/reads/keymerger_test.go
  storage/reads/merge.go
  storage/reads/merge_test.go
  storage/reads/mergegroupresultset.go
  storage/reads/mergegroupresultset_test.go
  storage/reads/predicate.go
  storage/reads/predicate_test.go
  storage/reads/reader_test.go
  storage/reads/readstate_string.go
  storage/reads/resultset_lineprotocol.go
  storage/reads/series_cursor_test.go
  storage/reads/store_test.go
  storage/reads/stream_reader.gen.go
  storage/reads/stream_reader.go
  storage/reads/stream_reader_gen_test.go
  storage/reads/stream_reader_test.go
  storage/reads/string_iterator_reader.go
  storage/reads/string_iterator_reader_test.go
  storage/reads/string_iterator_writer.go
  storage/reads/string_iterator_writer_test.go
  storage/reads/viewer.go
Labels: 1.x

#14485 fix: services/httpd: parse correctly Accept header with extra test cases
  services/httpd/accept.go
  services/httpd/response_writer.go
  services/httpd/response_writer_test.go
Labels: 1.x

#17230 fix: ensure we're using go v1.13.8
  Dockerfile
  releng/_go_versions.sh
Labels: 1.x

#17285 fix(http): make label service authorized by default
  http/api_handler.go
  http/check_service.go
  http/notification_endpoint.go
  http/notification_rule.go
Labels: team/compute

#17292 chore(litmus): run integration tests on master:
  .circleci/config.yml
  etc/litmus_fail_notify.sh
  etc/litmus_success_notify.sh
Labels: team/qa

#17295 test(query/stdlib/influxdata/influxdb): update rules_test to use algo-w
  query/stdlib/influxdata/influxdb/rules.go
  query/stdlib/influxdata/influxdb/rules_test.go
Labels: team/query

#17306 chore: added INFLUXPATH parameter required by backup and restore tests
  .circleci/config.yml
Labels: team/qa

#17338 feat(tsdb): Bulk delete series performance improvement
  tsdb/seriesfile/series_file.go
  tsdb/seriesfile/series_file_test.go
  tsdb/seriesfile/series_partition.go
  tsdb/seriesfile/series_verify_test.go
  tsdb/tsi1/index.go
  tsdb/tsi1/index_test.go
  tsdb/tsi1/log_file.go
  tsdb/tsi1/partition.go
  tsdb/tsm1/engine_delete_prefix.go
  tsdb/tsm1/engine_delete_prefix_test.go
Labels: area/storage

#17347 chore(litmus): start influxd on local machine
  .circleci/config.yml
Labels: team/qa

#17286 refactor(authorizer): auth micro framework
  authorizer/authorize.go
  authorizer/authorize_find.go
  authorizer/bucket.go
  authorizer/check.go
  authorizer/check_test.go
  authorizer/dashboard.go
  authorizer/label.go
  authorizer/label_test.go
  authorizer/notification_endpoint.go
  authorizer/notification_rule.go
  authorizer/notification_rule_test.go
  authorizer/org.go
  authorizer/password.go
  authorizer/scraper.go
  authorizer/scraper_test.go
  authorizer/secret.go
  authorizer/secret_test.go
  authorizer/source.go
  authorizer/task.go
  authorizer/telegraf.go
  authorizer/urm.go
  authorizer/user.go
  authorizer/variable.go
  authz.go
Labels: team/compute

#17309 test: add tests for tenant service
  kv/tenant_test.go
  tenant.go
  testing/tenant.go
Labels: team/compute

#17385 feat(tenant): add duplicate read service
  cmd/influxd/launcher/launcher.go
  cmd/influxd/launcher/tenant_test.go
  kv/duplicate_read_test.go
  tenant/duplicate_reads.go
  tenant/metrics_options.go
  tenant/middleware_bucket_metrics.go
  tenant/middleware_org_metrics.go
  tenant/middleware_urm_metrics.go
  tenant/middleware_user_logging.go
  tenant/middleware_user_metrics.go
  tenant/service.go
Labels: team/compute

#17495 fix(snapshotter): Properly read request body
  services/snapshotter/service.go
Labels: 1.x, needs-backport/1.7

#17512 fix(tsdb): Revert "fix: remove some unsafe marshalling to reduce risk of segfault"
  CHANGELOG.md
  cmd/influxd/backup_util/backup_util.go
  tests/backup_restore_test.go
  tsdb/index/tsi1/index_file.go
  tsdb/index/tsi1/measurement_block.go
  tsdb/index/tsi1/tag_block.go
  tsdb/series_set_test.go
Labels: 1.x
