Repository influxdata/influxdb, pull requests merged in 2021-03, with the labels that each got.

#20767 chore: Upgrade 1.x to the latest flux
  .circleci/config.yml
  Dockerfile_build_ubuntu32
  Dockerfile_build_ubuntu64
  Dockerfile_build_ubuntu64_go1.13
  Dockerfile_jenkins_ubuntu32
  Dockerfile_test_ubuntu32
  Jenkinsfile
  Makefile
  cmd/influx/cli/cli.go
  cmd/influx/cli/flux.go
  cmd/influxd/run/server.go
  flux/builtin/builtin.go
  flux/client/http.go
  flux/client/request.go
  flux/control/controller.go
  flux/stdlib/influxdata/influxdb/dependencies.go
  flux/stdlib/influxdata/influxdb/flux_predicate.go
  flux/stdlib/influxdata/influxdb/from.go
  flux/stdlib/influxdata/influxdb/operators.go
  flux/stdlib/influxdata/influxdb/rules.go
  flux/stdlib/influxdata/influxdb/rules_test.go
  flux/stdlib/influxdata/influxdb/source.go
  flux/stdlib/influxdata/influxdb/storage.go
  flux/stdlib/influxdata/influxdb/to.go
  flux/stdlib/influxdata/influxdb/to_test.go
  flux/stdlib/influxdata/influxdb/v1/databases.go
  go.mod
  go.sum
  internal/flux_controller.go
  models/points.go
  pkg-config.sh
  query/encode.go
  query/encode_test.go
  services/httpd/handler_test.go
  storage/reads/flux_reader.go
  test.sh
  tests/server_test.go
  tools.go
Labels: 1.x

#20907 chore: run goimports on 1.8 branch to bring it up to new check-in standards
  _tools/tmpl/main.go
  _tools/tmpl/main_test.go
  cmd/influx_tools/internal/format/binary/binary.pb.go
  cmd/influx_tsm/tsdb/internal/meta.pb.go
  cmd/influxd/backup_util/backup_util.go
  cmd/influxd/backup_util/internal/data.pb.go
  flux/stdlib/influxdata/influxdb/v1/databases.go
  pkg/tracing/wire/binary.pb.go
  prometheus/remote/remote.pb.go
  query/internal/internal.pb.go
  services/meta/internal/meta.pb.go
  services/storage/source.pb.go
  storage/reads/datatypes/predicate.pb.go
  storage/reads/datatypes/storage_common.pb.go
  stress/v2/main.go
  stress/v2/statement/exec.go
  stress/v2/statement/exec_test.go
  stress/v2/statement/go.go
  stress/v2/statement/go_test.go
  stress/v2/statement/influxql.go
  stress/v2/statement/influxql_test.go
  stress/v2/statement/insert.go
  stress/v2/statement/insert_test.go
  stress/v2/statement/query.go
  stress/v2/statement/query_test.go
  stress/v2/statement/set.go
  stress/v2/statement/set_test.go
  stress/v2/statement/statement.go
  stress/v2/statement/wait.go
  stress/v2/statement/wait_test.go
  tests/backup_restore_test.go
  tsdb/engine/tsm1/engine_internal_test.go
  tsdb/internal/meta.pb.go
Labels: 1.x, area/tooling, team/edge

#20910 feat: Make meta queries respect QueryTimeout values
  CHANGELOG.md
  cmd/influxd/run/server.go
  coordinator/statement_executor.go
  internal/tsdb_store.go
  query/executor.go
  query/executor_test.go
  query/task_manager.go
  services/continuous_querier/service_test.go
  services/httpd/handler_test.go
  services/storage/store.go
  tests/server_concurrent_test.go
  tsdb/store.go
  tsdb/store_test.go
Labels: 1.x, area/meta queries, team/edge

#20912 fix(tsdb): minimize lock contention when adding new fields or measure
  CHANGELOG.md
  tsdb/shard.go
  tsdb/shard_test.go
Labels: 1.x, area/performance, team/edge

#20914 fix: infinite recursion bug (#20862)
  CHANGELOG.md
  services/httpd/response_writer.go
Labels: 1.x, area/error handling, team/edge

#20977 feat: influx_inspect export to standard out
  CHANGELOG.md
  cmd/influx_inspect/export/export.go
Labels: 1.x, area/backup and restore, kind/feature-request, team/edge

#20989 feat: influx_inspect export to standard out (#20977)
  CHANGELOG.md
  cmd/influx_inspect/export/export.go
Labels: 1.x, area/backup and restore, kind/feature-request, team/edge

#20990 chore: updated CONTRIBUTING.md for new package config script
  CONTRIBUTING.md
Labels: 1.x, area/documentation, team/edge

#20993 feat: Log query text for POST requests
  CHANGELOG.md
  services/httpd/response_logger.go
Labels: 1.x, area/logging, kind/feature-request, needs-backport/1.8, team/edge

#21021 feat: Log query text for POST requests (#20993)
  CHANGELOG.md
  services/httpd/response_logger.go
Labels: 1.x, area/logging, kind/feature-request, team/edge
