Repository influxdata/influxdb, pull requests merged in 2021-06, with the labels that each got.

#21592 fix: avoid rewriting fields.idx unnecessarily
  CHANGELOG.md
  tsdb/engine/tsm1/engine.go
  tsdb/shard.go
  tsdb/shard_test.go
Labels: 1.x, area/performance, area/writes, kind/enhancement, team/edge

#21609 fix: avoid rewriting fields.idx unnecessarily (#21592) [Port to 1.9]
  CHANGELOG.md
  tsdb/engine/tsm1/engine.go
  tsdb/shard.go
  tsdb/shard_test.go
Labels: 1.x, area/performance, area/writes, kind/enhancement, team/edge

#21610 fix: avoid rewriting fields.idx unnecessarily (#21592)
  CHANGELOG.md
  tsdb/engine/tsm1/engine.go
  tsdb/shard.go
  tsdb/shard_test.go
Labels: area/2.x, area/performance, area/writes, kind/enhancement, team/edge

#21614 chore: minor refactor suggested by go lint
  tsdb/shard.go
Labels: 1.x, area/writes, kind/enhancement, team/edge

#21616 chore: minor refactor suggested by go lint (#21614)
  tsdb/shard.go
Labels: 1.x, area/writes, kind/enhancement, team/edge

#21615 feat: Port influxd inspect verify-tsm
  CHANGELOG.md
  cmd/influx_inspect/verify/tsm/verify.go
  cmd/influx_inspect/verify/tsm/verify_test.go
  cmd/influxd/inspect/inspect.go
  cmd/influxd/inspect/tsm_verify.go
  cmd/influxd/inspect/tsm_verify_test.go
Labels: area/2.x, area/tooling

#21659 fix: Do not close connection twice in DigestWithOptions
  CHANGELOG.md
  tsdb/engine/tsm1/digest.go
Labels: 1.x, area/tsm, kind/bug, team/edge

#21662 fix: Do not close connection twice in DigestWithOptions (#21659)
  CHANGELOG.md
  tsdb/engine/tsm1/digest.go
Labels: area/2.x, area/tsm, kind/bug, team/edge

#21666 fix: do not panic on cleaning up failed iterators
  CHANGELOG.md
  query/iterator.go
Labels: 1.x, area/queries, kind/bug, panic, team/edge

#21693 fix: don't access a field in a nil struct
  tsdb/shard.go
Labels: 1.x, area/writes, kind/bug, team/edge

#21695 fix: Do not close connection twice in DigestWithOptions (#21659)
  CHANGELOG.md
  tsdb/engine/tsm1/digest.go
Labels: 1.x, area/tsm, kind/bug, team/edge

#21696 fix: don't access a field in a nil struct (#21693)
  tsdb/shard.go
Labels: area/2.x, area/writes, kind/bug, team/edge

#21697 fix: do not panic on cleaning up failed iterators (#21666)
  CHANGELOG.md
  query/iterator.go
Labels: 1.x, area/queries, kind/bug, panic, team/edge

#21707 chore: add logging to compaction
  CHANGELOG.md
  cmd/influx_tools/compact/command.go
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
Labels: 1.x, area/logging, kind/enhancement, team/edge

#21710 chore: add logging to compaction (#21707)
  CHANGELOG.md
  cmd/influx_tools/compact/command.go
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
Labels: 1.x, area/logging, kind/enhancement, team/edge

#21764 fix: do not send non-UTF-8 characters to subscriptions (#21558)
  CHANGELOG.md
  models/points.go
  services/subscriber/service.go
  services/subscriber/service_test.go
Labels: 1.x, area/line protocol, area/subscriptions, kind/bug, team/edge
