Repository influxdata/influxdb, pull requests merged in 2021-07, with the labels that each got.

#18819 chore: remove unused field tcpAddr
  cmd/influxd/run/server.go
Labels: 1.x, community-pr

#18961 fix(tsi): clean up FileSet fields
  cmd/influx_inspect/dumptsi/dumptsi.go
  tsdb/index/tsi1/file_set.go
  tsdb/index/tsi1/file_set_test.go
  tsdb/index/tsi1/index.go
  tsdb/index/tsi1/partition.go
Labels: 1.8.3-maybe, 1.x, area/tsi

#21887 chore: add more logging
  tsdb/engine.go
  tsdb/engine/tsm1/engine.go
  tsdb/shard.go
  tsdb/store.go
Labels: area/logging, kind/enhancement, team/edge

#21900 chore: add logging to compaction
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
Labels: area/2.x, area/logging, kind/enhancement, team/edge

#21916 chore: add more logging
  tsdb/engine.go
  tsdb/engine/tsm1/engine.go
  tsdb/shard.go
  tsdb/store.go
Labels: area/2.x, area/logging, kind/enhancement, team/edge

#21914 fix: don't access a field in a nil struct
  tsdb/shard.go
Labels: area/2.x, area/writes, kind/bug, team/edge

#21920 chore: add logging to compaction
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
Labels: area/2.x, area/logging, kind/enhancement, team/edge

#21921 fix: don't access a field in a nil struct (#21693)
  tsdb/shard.go
Labels: 1.x, area/writes, kind/bug, team/edge
