Repository influxdata/influxdb, pull requests merged in 2022-10, with the labels that each got.

#23785 fix: use copy when a rename spans volumes
  pkg/file/file_unix.go
Labels: area/backup and restore, kind/bug, 1.x, team/edge

#23787 fix: add tests for file rename across volumes
  pkg/file/file.go
  pkg/file/file_test.go
  pkg/file/file_unix.go
  pkg/file/file_windows.go
Labels: area/backup and restore, kind/bug, 1.x, team/edge

#23795 feat: add version number to debug/vars
  services/httpd/handler.go
Labels: area/stats, kind/enhancement, 1.x, area/api, team/edge

#23792 fix: use copy when a rename spans volumes (#23785)
  pkg/file/file.go
  pkg/file/file_test.go
  pkg/file/file_unix.go
  pkg/file/file_windows.go
Labels: area/backup and restore, kind/bug, 1.x, team/edge

#23796 feat: add version number to debug/vars (#23795)
  services/httpd/handler.go
Labels: area/stats, kind/enhancement, 1.x, area/api, team/edge

#23808 chore: update to use scheduled pipeline (1.x)
  .circleci/config.yml
Labels: 1.x, area/build, team/edge

#23811 chore: update to use scheduled pipeline (2.x)
  .circleci/config.yml
Labels: area/build, area/2.x, team/edge

#23810 chore: update to use scheduled pipeline (2.4)
  .circleci/config.yml
Labels: area/build, area/2.x, team/edge

#23809 chore: update to use scheduled pipeline (1.10)
  .circleci/config.yml
Labels: 1.x, area/build, team/edge

#23822 fix: log errors in continuous query statistics storage
  services/continuous_querier/service.go
Labels: area/continuous queries, area/stats, kind/enhancement, 1.x, team/edge

#23825 fix: log errors in continuous query statistics storage (#23822)
  services/continuous_querier/service.go
Labels: area/continuous queries, area/stats, kind/enhancement, 1.x, team/edge, area/logging
