Repository influxdata/influxdb, pull requests merged in 2022-06, with the labels that each got.

#23387 fix: replace unprintable and invalid characters in errors
  tsdb/shard.go
  tsdb/shard_internal_test.go
Labels: kind/bug, 1.x, team/edge, area/logging

#23394 fix: replace unprintable and invalid characters in errors (#23387)
  tsdb/shard.go
  tsdb/shard_internal_test.go
Labels: kind/bug, 1.x, team/edge, area/logging

#23396 fix: do not rename files on mmap failure
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
  tsdb/engine/tsm1/file_store_internal_test.go
  tsdb/engine/tsm1/file_store_test.go
  tsdb/engine/tsm1/reader.go
Labels: area/tsm, kind/bug, 1.x, team/edge

#23418 fix: replace unprintable and invalid characters in errors (#23387)
  tsdb/shard.go
  tsdb/shard_internal_test.go
Labels: kind/bug, 1.x, team/edge, area/logging

#23421 fix: do not rename files on mmap failure (#23396)
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
  tsdb/engine/tsm1/file_store_internal_test.go
  tsdb/engine/tsm1/file_store_test.go
  tsdb/engine/tsm1/reader.go
Labels: area/tsm, kind/bug, 1.x, team/edge

#23417 feat: estimate Cloud2 cardinality on 1.X databases (#23351)
  cmd/influx_inspect/cardinality/aggregators/aggregators.go
  cmd/influx_inspect/cardinality/aggregators/aggregators_test.go
  cmd/influx_inspect/cardinality/cardinality.go
  cmd/influx_inspect/help/help.go
  cmd/influx_inspect/main.go
  cmd/influx_inspect/report/report.go
  go.mod
  go.sum
Labels: area/tooling, kind/feature-request, 1.x, kind/feature, team/edge

#23437 fix: remember shards that fail Open(), avoid repeated attempts
  coordinator/points_writer.go
  tsdb/store.go
  tsdb/store_test.go
Labels: area/tsm, kind/bug, area/tsi, 1.x, team/edge

#23445 feat: log the log level regardless of log level (#23425)
  cmd/influxd/run/command.go
Labels: kind/enhancement, 1.x, team/edge, area/logging

#23444 fix: remember shards that fail Open(), avoid repeated attempts (#23437)
  coordinator/points_writer.go
  tsdb/store.go
  tsdb/store_test.go
Labels: area/tsm, kind/bug, area/tsi, 1.x, team/edge

#23454 fix: fully clean up partially opened TSI (#23430)
  go.mod
  go.sum
  pkg/mmap/mmap_unix.go
  tsdb/index/tsi1/file_set.go
  tsdb/index/tsi1/index.go
  tsdb/index/tsi1/index_test.go
  tsdb/index/tsi1/partition.go
Labels: area/tsm, kind/bug, area/tsi, area/2.x, team/edge

#23455 fix: remember shards that fail Open(), avoid repeated attempts (#23437)
  tsdb/store.go
  tsdb/store_test.go
  v1/coordinator/points_writer.go
Labels: area/tsm, kind/bug, kind/enhancement, area/tsi, area/2.x, team/edge, area/logging

#23447 feat: add instance-id flag for identifying edge nodes
  cmd/influxd/launcher/cmd.go
  cmd/influxd/launcher/launcher.go
  replications/service.go
  replications/service_test.go
Labels: kind/enhancement, area/2.x, area/data ingestion, team/edge

#23456 feat: Add remotes and replications to telemetry
  .gitignore
  bolt/bbolt.go
  bolt/metrics.go
  bolt/metrics_test.go
  cmd/influxd/launcher/launcher.go
  kv/migration/all/0020_add_remotes_replications_metrics_buckets.go
  kv/migration/all/all.go
  prometheus/filter.go
  remotes/transport/http.go
  remotes/transport/middleware_kv.go
  remotes/transport/middleware_kv_test.go
  replications/transport/http.go
  replications/transport/middleware_kv.go
  replications/transport/middleware_kv_test.go
  telemetry/metrics.go
Labels: kind/enhancement, area/2.x, team/edge

#23462 fix: lost TSI reference / close TagValueSeriesIDIterator in error case (#23461)
  tsdb/index/tsi1/index.go
Labels: kind/bug, area/tsi, 1.x, team/edge

#23463 fix: lost TSI reference / close TagValueSeriesIDIterator in error case (#23461)
  tsdb/index/tsi1/index.go
Labels: kind/bug, area/tsi, 1.x, team/edge

#23464 fix: lost TSI reference / close TagValueSeriesIDIterator in error case (#23461)
  tsdb/index/tsi1/index.go
Labels: kind/bug, area/tsi, 1.x, team/edge

#23489 chore: update flux to 0.170.1
  go.mod
  go.sum
Labels: kind/enhancement, area/flux, 1.x, team/edge

#23490 chore: update flux to 0.170.1
  go.mod
  go.sum
Labels: kind/enhancement, area/flux, 1.x, team/edge
