Repository influxdata/influxdb, pull requests merged in 2022-05, with the labels that each got.

#23320 feat: log slow queries even without query logging
  cmd/influxd/run/server.go
Labels: kind/feature-request, 1.x, team/edge, area/logging

#23338 feat: log slow queries even without query logging (#23320)
  cmd/influxd/run/server.go
Labels: kind/feature-request, 1.x, team/edge, area/logging

#23336 fix: remove data directory appending for influx_inspect verify
  cmd/influx_inspect/verify/tsm/verify.go
Labels: 1.x

#23351 feat: estimate Cloud2 cardinality on 1.X databases
  cmd/influx_inspect/cardinality/aggregators/aggregators.go
  cmd/influx_inspect/cardinality/aggregators/aggregators_test.go
  cmd/influx_inspect/cardinality/cardinality.go
  cmd/influx_inspect/help/help.go
  cmd/influx_inspect/main.go
  cmd/influx_inspect/report/report.go
  go.mod
  go.sum
Labels: area/tooling, kind/feature-request, area/meta queries, 1.x, team/edge
