Repository influxdata/influxdb, pull requests merged in 2022-04, with the labels that each got.

#21746 fix(httpd): abort processing write request when encountering a precision error.
  services/httpd/handler.go
Labels: 1.x

#23260 fix: remove controller 64bit misalignment
  query/control/controller.go
Labels: area/2.x

#23276 fix(systemd): fix operator in host detection
  scripts/influxd-systemd-start.sh
Labels: area/2.x

#23286 fix: MeasurementsCardinality should not be less than 0
  tsdb/store.go
  tsdb/store_test.go
Labels: kind/bug, 1.x

#23284 feat: partial /v2/api/buckets support: create, delete, list, retrieve
  internal/storage_store.go
  services/httpd/handler.go
  services/httpd/handler_test.go
  services/meta/query_authorizer.go
  services/storage/store.go
Labels: 1.x, area/api, kind/feature, team/edge

#23294 feat: stub out bucket members, owners, and labels
  services/httpd/handler.go
  services/httpd/handler_test.go
Labels: kind/feature-request, 1.x, area/api, team/edge

#23319 fix: do not panic on cleaning up failed iterators (#21666)
  influxql/query/iterator.go
Labels: area/queries, kind/bug, area/2.x, team/edge
