Repository influxdata/influxdb, pull requests merged in 2022-11, with the labels that each got.

#23871 fix: Optimize SHOW FIELD KEY CARDINALITY
  query/statement_rewriter.go
  query/statement_rewriter_test.go
  tsdb/shard.go
Labels: area/performance, area/meta queries, 1.x, team/edge

#23875 fix: remove breaking argument validation for _fieldKeys iterator
  cmd/influx_tools/export/command.go
  tsdb/shard.go
Labels: kind/bug, area/meta queries, 1.x, team/edge

#23884 fix: listBuckets properly returns wrapped response (#23883)
  services/httpd/handler.go
  services/httpd/handler_test.go
Labels: area/meta service, kind/bug, 1.x, area/api, team/edge

#23886 fix: Optimize SHOW FIELD KEY CARDINALITY
  influxql/query/statement_rewriter.go
  influxql/query/statement_rewriter_test.go
Labels: area/performance, area/meta queries, team/edge

#23898 fix(1.10): make buckets API fully compatible
  services/httpd/handler.go
  services/httpd/handler_test.go
Labels: area/meta service, kind/bug, 1.x, area/api, team/edge

#23900 fix: :db/:rp -> :dbrp, fixed create bucket, update bucket (#23898)
  services/httpd/handler.go
  services/httpd/handler_test.go
Labels: area/meta service, kind/bug, 1.x, area/api, team/edge

#23911 feat: upgrade flux to v0.188.0
  .circleci/config.yml
  cmd/influx_tools/internal/format/binary/tools_binary.pb.go
  cmd/influxd/backup_util/internal/backup_util.pb.go
  cmd/influxd/run/server.go
  flux/stdlib/influxdata/influxdb/buckets.go
  flux/stdlib/influxdata/influxdb/filter_test.flux
  flux/stdlib/influxdata/influxdb/multi_measure_test.flux
  flux/stdlib/influxdata/influxdb/rules.go
  flux/stdlib/influxdata/influxdb/tag_values_measurement_or_predicate_test.flux
  flux/stdlib/influxdata/influxdb/to.go
  flux/stdlib/influxdata/influxdb/to_test.go
  flux/stdlib/influxdata/influxdb/v1/databases.go
  flux/stdlib/universe/bare_aggregate_test.flux
  flux/stdlib/universe/merge_filter_test.flux
  flux/stdlib/universe/window_aggregate_by_time_test.flux
  flux/stdlib/universe/window_aggregate_test.flux
  go.mod
  go.sum
  internal/cmd/fluxtest-harness-influxdb/test.go
  pkg/tracing/wire/binary.pb.go
  query/internal/internal.pb.go
  services/httpd/config.go
  services/meta/internal/meta.pb.go
  services/storage/source.pb.go
  storage/reads/array_cursor.gen.go
  storage/reads/array_cursor.gen.go.tmpl
  storage/reads/datatypes/predicate.pb.go
  storage/reads/datatypes/storage_common.pb.go
  test-flux.sh
  tests/server_test.go
  tsdb/internal/fieldsindex.pb.go
Labels: 1.x, area/build, team/edge

#23918 chore: fix trace message text
  tsdb/shard.go
Labels: area/tsm, kind/bug, team/edge, area/logging

#23941 chore: upgrade Go to v1.19.3 (1.x)
  .circleci/config.yml
  cmd/influx/cli/cli.go
  cmd/influx_tools/internal/errlist/errlist.go
  cmd/influxd/run/command.go
  coordinator/points_writer.go
  flux/stdlib/influxdata/influxdb/rules.go
  flux/stdlib/influxdata/influxdb/rules_test.go
  go.mod
  kit/platform/errors/errors.go
  kit/tracing/tracing.go
  monitor/diagnostics/diagnostics.go
  pkg/encoding/simple8b/encoding.go
  pkg/errors/error_capture.go
  pkg/estimator/hll/hll.go
  pkg/tar/stream.go
  pkg/tracing/doc.go
  pkg/tracing/fields/field.go
  pkg/tracing/wire/binary.go
  pkg/tracing/wire/binary.pb.go
  query/encode.go
  query/functions.go
  query/iterator.gen.go
  services/graphite/parser.go
  services/httpd/handler.go
  services/httpd/pprof.go
  services/httpd/response_logger.go
  services/httpd/v2_write_test.go
  services/meta/client.go
  services/opentsdb/service.go
  services/snapshotter/service.go
  services/storage/predicate_influxql.go
  storage/reads/datatypes/predicate.pb.go
  storage/reads/datatypes/storage_common.pb.go
  storage/reads/group_resultset_test.go
  tsdb/engine/tsm1/engine_test.go
  tsdb/engine/tsm1/ring.go
  tsdb/field_validator.go
  tsdb/index/tsi1/doc.go
  tsdb/index/tsi1/index.go
  tsdb/index_test.go
  tsdb/series_set_test.go
  tsdb/shard.go
  tsdb/store.go
Labels: 1.x, area/build, team/edge
