Repository influxdata/influxdb, pull requests merged in 2023-12, with the labels that each got.

#24503 chore: upgrade flux
  go.mod
  go.sum
Labels: kind/enhancement, area/flux, area/2.x, team/edge

#24509 fix: avoid SIGBUS when reading non-std series segment files
  cmd/influx_inspect/verify/seriesfile/verify.go
  tsdb/series_file.go
  tsdb/series_partition.go
  tsdb/series_segment.go
  tsdb/series_segment_test.go
Labels: area/tsm, kind/bug, 1.x, team/edge

#24515 fix: avoid SIGBUS when reading non-std series segment files (#24509)
  cmd/influx_inspect/verify/seriesfile/verify.go
  tsdb/series_file.go
  tsdb/series_partition.go
  tsdb/series_segment.go
  tsdb/series_segment_test.go
Labels: area/tsm, kind/bug, 1.x, team/edge

#24520 fix: avoid SIGBUS when reading non-std series segment files (#24509)
  cmd/influxd/inspect/verify_seriesfile/verify_seriesfile.go
  tsdb/series_file.go
  tsdb/series_partition.go
  tsdb/series_segment.go
  tsdb/series_segment_test.go
  tsdb/shard_test.go
Labels: area/tsm, kind/bug, area/2.x, team/edge

#24521 fix: avoid SIGBUS when reading non-std series segment files (#24509) (#24520)
  cmd/influxd/inspect/verify_seriesfile/verify_seriesfile.go
  tsdb/series_file.go
  tsdb/series_partition.go
  tsdb/series_segment.go
  tsdb/series_segment_test.go
  tsdb/shard_test.go
Labels: area/tsm, kind/bug, area/2.x, team/edge

#24524 fix: enable HttpOnly and Secure using TLS
  session/http_server.go
  session/http_server_test.go
Labels: security, kind/bug, area/api, area/2.x, team/edge

#24526 fix: enable Secure when using TLS and enable HttpOnly (#24524)
  session/http_server.go
  session/http_server_test.go
Labels: security, kind/bug, area/api, area/2.x, team/edge

#24528 chore: Run cargo fmt --all
  ingest_structure/src/lib.rs
Labels: v3

#24527 chore: Sync and release v1.0.1 of influxdb-line-protocol
  Cargo.lock
  influxdb_line_protocol/Cargo.toml
  influxdb_line_protocol/README.md
  influxdb_line_protocol/RELEASE.md
  influxdb_line_protocol/src/lib.rs
Labels: v3

#24519 fix: corrrectly return 4XX errors instead of 5XX errors
  authorization/error.go
  authorization/storage_authorization.go
  bolt/kv.go
  bucket.go
  checks/service_external_test.go
  dashboards/testing/dashboards.go
  dashboards/testing/util.go
  kit/errors/errors.go
  kit/errors/list.go
  kit/platform/errors/errors.go
  kit/transport/http/error_handler.go
  label/error.go
  notification/endpoint/endpoint_test.go
  organization.go
  query/control/controller.go
  query/stdlib/influxdata/influxdb/rules_test.go
  replications/remotewrite/writer_test.go
  sqlite/migrator_test.go
  storage/reads/aggregate_resultset.go
  task/backend/analytical_storage.go
  tenant/error.go
  tenant/http_server_org_test.go
  tenant/http_server_user_test.go
  tenant/middleware_org_logging_test.go
  tenant/middleware_user_logging_test.go
  tenant/service_org_test.go
  tenant/service_user_test.go
  tenant/storage_bucket.go
  tenant/storage_bucket_test.go
  tenant/storage_org.go
  tenant/storage_org_test.go
  tenant/storage_user.go
  tenant/storage_user_test.go
  testing/auth.go
  testing/bucket_service.go
  testing/label_service.go
  testing/organization_service.go
  testing/scraper_target.go
  testing/session.go
  testing/source.go
  testing/user_service.go
  testing/util.go
  testing/variable.go
  tsdb/engine/tsm1/engine_test.go
  tsdb/index_test.go
  v1/authorization/error.go
  v1/authorization/storage_authorization.go
  v1/authorization/storage_authorization_test.go
Labels: kind/bug, area/api, area/2.x, team/edge

#24534 fix: corrrectly return 4XX errors instead of 5XX errors (#24519)
  authorization/error.go
  authorization/storage_authorization.go
  bolt/kv.go
  bucket.go
  checks/service_external_test.go
  dashboards/testing/dashboards.go
  dashboards/testing/util.go
  kit/errors/errors.go
  kit/errors/list.go
  kit/platform/errors/errors.go
  kit/transport/http/error_handler.go
  label/error.go
  notification/endpoint/endpoint_test.go
  organization.go
  query/control/controller.go
  query/stdlib/influxdata/influxdb/rules_test.go
  replications/remotewrite/writer_test.go
  sqlite/migrator_test.go
  storage/reads/aggregate_resultset.go
  task/backend/analytical_storage.go
  tenant/error.go
  tenant/http_server_org_test.go
  tenant/http_server_user_test.go
  tenant/middleware_org_logging_test.go
  tenant/middleware_user_logging_test.go
  tenant/service_org_test.go
  tenant/service_user_test.go
  tenant/storage_bucket.go
  tenant/storage_bucket_test.go
  tenant/storage_org.go
  tenant/storage_org_test.go
  tenant/storage_user.go
  tenant/storage_user_test.go
  testing/auth.go
  testing/bucket_service.go
  testing/label_service.go
  testing/organization_service.go
  testing/scraper_target.go
  testing/session.go
  testing/source.go
  testing/user_service.go
  testing/util.go
  testing/variable.go
  tsdb/engine/tsm1/engine_test.go
  tsdb/index_test.go
  v1/authorization/error.go
  v1/authorization/storage_authorization.go
  v1/authorization/storage_authorization_test.go
Labels: kind/bug, area/api, area/2.x, team/edge
