Repository influxdata/influxdb, pull requests merged in 2023-11, with the labels that each got.

#24391 chore: Update dependabot.yml
  .github/dependabot.yml
Labels: v3

#24452 fix: handle MetricSlice to Points conversion errors
  gather/metrics.go
  gather/scheduler_test.go
Labels: area/error handling, kind/bug, area/subscriptions, team/edge, area/metrics

#24453 fix: handle MetricSlice to Points conversion errors (#24452)
  gather/metrics.go
  gather/scheduler_test.go
Labels: area/error handling, kind/bug, area/subscriptions, team/edge, area/metrics

#24474 feat: Add authenticating ID and user ID to request logging
  context/token.go
  http/authentication_middleware.go
  http/legacy/influx1x_authentication_handler.go
  http/middleware.go
Labels: kind/enhancement, area/2.x, team/edge, area/logging

#24479 feat: Add authenticating ID and user ID to request logging (#24474)
  context/token.go
  http/authentication_middleware.go
  http/legacy/influx1x_authentication_handler.go
  http/middleware.go
Labels: kind/enhancement, area/2.x, team/edge, area/logging

#24496 feat: write detailed logs from EDR failures
  replications/remotewrite/writer.go
  replications/remotewrite/writer_test.go
Labels: kind/enhancement, area/2.x, team/edge, area/logging

#24497 feat: write detailed logs from EDR failures (#24496)
  replications/remotewrite/writer.go
  replications/remotewrite/writer_test.go
Labels: kind/enhancement, area/2.x, team/edge, area/logging
