Repository influxdata/influxdb, pull requests merged in 2023-05, with the labels that each got.

#24223 fix: /api/v2/delete - user nil sources field, do not set measurement db or rp
  services/httpd/handler.go
Labels: kind/bug, 1.x, area/api, team/edge

#24235 fix: prevent world-writable MANIFEST files
  tsdb/index/tsi1/partition.go
Labels: kind/bug, area/tsi, 1.x, team/edge

#24236 fix: prevent world-writable MANIFEST files (#24235)
  tsdb/index/tsi1/partition.go
Labels: kind/bug, area/tsi, 1.x, team/edge

#24238 fix: prevent world-writable MANIFEST files [Port to 1.10]
  tsdb/index/tsi1/partition.go
Labels: kind/bug, area/tsi, 1.x, team/edge

#24245 chore: upgrade changelogger to latest version (2.7)
  .circleci/config.yml
Labels: area/build

#24246 chore: upgrade changelogger to latest version (2.6)
  .circleci/config.yml
Labels: area/build

#24253 chore: upgrade flux to v0.194.3 (1.11)
  go.mod
  go.sum
Labels: area/flux, 1.x

#24254 chore: upgrade flux to v0.194.3 (master-1.x)
  go.mod
  go.sum
Labels: area/flux, 1.x
