Repository influxdata/influxdb, pull requests merged in 2023-06, with the labels that each got.

#23916 fix: series file index compaction
  tsdb/series_partition.go
Labels: area/tsm, kind/bug, 1.x, team/edge

#24259 fix: series file index compaction (#23916)
  tsdb/series_partition.go
Labels: kind/bug, area/tsi, 1.x, team/edge

#24260 fix: execute "compact-series-file" at startup (1.x)
  .circleci/scripts/sign-packages
  scripts/influxd-systemd-start.sh
  scripts/init.sh
Labels: 1.x

#24311 fix: do not escape CSV output
  cmd/influx_inspect/dumptsi/dumptsi.go
  models/points.go
  models/points_test.go
  monitor/service_test.go
  services/httpd/response_writer.go
  storage/reads/resultset_lineprotocol.go
  storage/reads/store_test.go
  tsdb/engine/tsm1/engine_test.go
  tsdb/index_test.go
Labels: area/queries, kind/bug, 1.x, team/edge

#24313 fix: do not escape CSV output (#24311)
  cmd/influx_inspect/dumptsi/dumptsi.go
  models/points.go
  models/points_test.go
  monitor/service_test.go
  services/httpd/response_writer.go
  storage/reads/resultset_lineprotocol.go
  storage/reads/store_test.go
  tsdb/engine/tsm1/engine_test.go
  tsdb/index_test.go
Labels: area/queries, kind/bug, 1.x, team/edge
