Repository influxdata/influxdb, pull requests merged in 2024-07, with the labels that each got.

#25121 fix: prevent retention service from hanging
  internal/tsdb_store.go
  tsdb/engine.go
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
  tsdb/engine/tsm1/file_store_test.go
  tsdb/shard.go
  tsdb/shard_test.go
  tsdb/store.go
  tsdb/store_test.go
  v1/services/retention/service.go
  v1/services/retention/service_test.go
Labels: area/storage, area/2.x, team/edge

#25125 feat: support addition of newly written columns to last cache
  influxdb3_write/src/last_cache.rs
Labels: v3

#25138 chore: sync latest core
  Cargo.lock
  Cargo.toml
  influxdb3/tests/server/system_tables.rs
  influxdb3_write/src/cache.rs
  influxdb3_write/src/catalog/serialize.rs
  influxdb3_write/src/persister.rs
Labels: v3

#25133 refactor: improvements to last cache implementation
  influxdb3_write/src/last_cache.rs
  influxdb3_write/src/write_buffer/mod.rs
Labels: v3

#25146 fix: Store.validateArgs wrongfully overwriting start, end unix time
  v1/services/storage/store.go
  v1/services/storage/store_test.go
Labels: kind/bug, area/flux, team/edge

#25155 fix: prevent an infinite loop in measurementFieldSetChangeMgr
  tsdb/shard.go
Labels: area/tsm, kind/bug, team/edge

#25156 fix: prevent an infinite loop in measurementFieldSetChangeMgr (#25155)
  tsdb/shard.go
Labels: area/tsm, kind/bug, team/edge

#25143 feat: hook up last cache to query executor using DataFusion traits
  Cargo.lock
  influxdb3/src/commands/serve.rs
  influxdb3_server/src/builder.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor.rs
  influxdb3_write/src/last_cache/mod.rs
  influxdb3_write/src/last_cache/table_function.rs
  influxdb3_write/src/lib.rs
Labels: v3

#25147 feat: API to create last caches
  Cargo.lock
  Cargo.toml
  influxdb3/tests/server/configure.rs
  influxdb3/tests/server/main.rs
  influxdb3_server/Cargo.toml
  influxdb3_server/src/http.rs
  influxdb3_write/src/last_cache/mod.rs
  influxdb3_write/src/write_buffer/mod.rs
Labels: v3

#25162 feat: `DELETE` last cache API
  influxdb3/tests/server/configure.rs
  influxdb3_server/src/http.rs
  influxdb3_write/src/last_cache/mod.rs
Labels: v3

#25165 fix: Store.validateArgs wrongfully overwriting start, end unix time (#25146)
  services/storage/store.go
Labels: kind/bug, area/flux, team/edge

#25164 fix: prevent an infinite loop in measurementFieldSetChangeMgr
  tsdb/shard.go
Labels: kind/bug, area/flux, team/edge

#25163 fix: Store.validateArgs wrongfully overwriting start, end unix time (#25146)
  v1/services/storage/store.go
  v1/services/storage/store_test.go
Labels: kind/bug, area/flux, team/edge

#25166 feat: `last_caches` system table
  influxdb3/tests/server/flight.rs
  influxdb3/tests/server/main.rs
  influxdb3/tests/server/system_tables.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor.rs
  influxdb3_server/src/system_tables/last_caches.rs
  influxdb3_server/src/system_tables/mod.rs
  influxdb3_server/src/system_tables/queries.rs
  influxdb3_write/src/last_cache/mod.rs
Labels: v3

#25167 feat: add methods to create and delete last caches to `influxdb3_client`
  influxdb3_client/src/lib.rs
Labels: v3

#25168 feat: CLI to manage last caches
  influxdb3/src/commands/last_cache/create.rs
  influxdb3/src/commands/last_cache/delete.rs
  influxdb3/src/commands/last_cache/mod.rs
  influxdb3/src/commands/token.rs
  influxdb3/src/main.rs
Labels: v3

#25175 feat: support `!=`, `IN`, and `NOT IN` predicates in last cache queries
  influxdb3_server/src/lib.rs
  influxdb3_write/src/last_cache/mod.rs
Labels: v3

#25185 fix: last cache catalog configuration tracks explicit vs. non-explicit value columns
  Cargo.lock
  influxdb3/tests/server/client.rs
  influxdb3/tests/server/main.rs
  influxdb3/tests/server/system_tables.rs
  influxdb3_client/src/lib.rs
  influxdb3_server/src/system_tables/last_caches.rs
  influxdb3_write/src/catalog.rs
  influxdb3_write/src/catalog/serialize.rs
  influxdb3_write/src/last_cache/mod.rs
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-after-allowing-time-to-persist-segments-after-create.snap
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-create.snap
Labels: v3

#25192 test: add a test to check last cache init from catalog
  influxdb3_write/src/catalog.rs
  influxdb3_write/src/last_cache/mod.rs
  influxdb3_write/src/last_cache/snapshots/influxdb3_write__last_cache__tests__catalog_initialization.snap
Labels: v3

#25195 chore: update object_store to 0.10.2
  Cargo.lock
  Cargo.toml
Labels: v3
