Repository influxdata/influxdb, pull requests merged in 2024-11, with the labels that each got.

#25495 refactor: move to `ColumnId` and `Arc<str>` as much as possible
  Cargo.lock
  influxdb3/tests/server/configure.rs
  influxdb3/tests/server/system_tables.rs
  influxdb3_catalog/Cargo.toml
  influxdb3_catalog/src/catalog.rs
  influxdb3_catalog/src/serialize.rs
  influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__catalog_serialization.snap
  influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_last_cache.snap
  influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_series_keys.snap
  influxdb3_client/src/lib.rs
  influxdb3_id/Cargo.toml
  influxdb3_id/src/lib.rs
  influxdb3_id/src/serialize.rs
  influxdb3_server/src/http.rs
  influxdb3_server/src/system_tables/last_caches.rs
  influxdb3_wal/Cargo.toml
  influxdb3_wal/src/lib.rs
  influxdb3_wal/src/object_store.rs
  influxdb3_wal/src/serialize.rs
  influxdb3_write/src/last_cache/mod.rs
  influxdb3_write/src/last_cache/snapshots/influxdb3_write__last_cache__tests__catalog_initialization.snap
  influxdb3_write/src/last_cache/table_function.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/persister.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-after-last-cache-create-and-new-field.snap
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-create.snap
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-delete.snap
  influxdb3_write/src/write_buffer/table_buffer.rs
  influxdb3_write/src/write_buffer/validator.rs
Labels: v3

#25510 fix: the cache target for build artefacts in Dockerfile
  Dockerfile
Labels: v3

#25516 chore: remove unnecessary rustsec for the tonic cve
  Cargo.lock
  Cargo.toml
  deny.toml
  influxdb3_write/src/write_buffer/table_buffer.rs
Labels: v3

#25515 refactor: remove conversion step in validator
  influxdb3_write/src/lib.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/validator.rs
Labels: v3

#25520 feat: configurable last cache eviction
  influxdb3/src/commands/serve.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor.rs
  influxdb3_write/src/last_cache/mod.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
Labels: v3

#25525 fix: throw error when adding fields to non-existent table in WAL
  influxdb3_catalog/src/catalog.rs
  influxdb3_wal/src/create.rs
  influxdb3_wal/src/lib.rs
Labels: v3

#25526 feat: Update catalog to use sequence number in path
  influxdb3_catalog/src/catalog.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/paths.rs
  influxdb3_write/src/persister.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/persisted_files.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
  influxdb3_write/src/write_buffer/validator.rs
Labels: v3

#25513 chore: loadShards changes to more cleanly support 2.x feature
  tsdb/store.go
  tsdb/store_test.go
Labels: area/tsm, 1.x

#25536 chore: remove unnecessary fmt.Sprintf calls
  tsdb/store_test.go
Labels: 1.x

#25541 refactor: use `SerdeVecMap` in `PersistedSnapshot`
  influxdb3_write/src/lib.rs
  influxdb3_write/src/persister.rs
  influxdb3_write/src/snapshots/influxdb3_write__persister__tests__persisted_snapshot_structure.snap
Labels: v3

#25540 feat: check for uncommitted WRR segments during startup
  tsdb/store.go
  tsdb/store_test.go
Labels: area/tsm, kind/feature, area/2.x

#25554 feat: improve logging for subscriptions
  services/subscriber/http.go
  services/subscriber/service.go
  services/subscriber/service_test.go
  services/subscriber/udp.go
Labels: kind/enhancement, area/subscriptions, 1.x, team/edge, area/logging

#25556 chore: loadShards changes to more cleanly support 2.x feature
  tsdb/store.go
  tsdb/store_test.go
Labels: area/tsm, area/2.x

#25560 feat: check for uncommitted WRR segments during startup
  tsdb/store.go
  tsdb/store_test.go
Labels: area/2.x

#25570 fix: don't rebuild snapshot if it has already been taken.
  influxdb3_wal/src/object_store.rs
  influxdb3_write/src/write_buffer/mod.rs
Labels: v3

#25566 feat: metadata cache provider and datafusion trait impls
  Cargo.lock
  influxdb3_cache/Cargo.toml
  influxdb3_cache/src/meta_cache/cache.rs
  influxdb3_cache/src/meta_cache/mod.rs
  influxdb3_cache/src/meta_cache/provider.rs
  influxdb3_cache/src/meta_cache/table_function.rs
  influxdb3_catalog/src/catalog.rs
  influxdb3_wal/src/create.rs
  influxdb3_wal/src/lib.rs
  influxdb3_write/src/write_buffer/validator.rs
Labels: v3

#25589 fix: log rejected writes to subscriptions
  services/subscriber/service.go
Labels: kind/enhancement, 1.x, team/edge, area/logging, area/replications

#25587 feat: metacache REST APIs to create and delete
  Cargo.lock
  influxdb3/Cargo.toml
  influxdb3/src/commands/serve.rs
  influxdb3/tests/server/configure.rs
  influxdb3/tests/server/query.rs
  influxdb3_cache/Cargo.toml
  influxdb3_cache/src/meta_cache/cache.rs
  influxdb3_cache/src/meta_cache/mod.rs
  influxdb3_cache/src/meta_cache/provider.rs
  influxdb3_catalog/src/catalog.rs
  influxdb3_server/Cargo.toml
  influxdb3_server/src/http.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor.rs
  influxdb3_wal/src/lib.rs
  influxdb3_write/Cargo.toml
  influxdb3_write/src/last_cache/mod.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
  influxdb3_write/src/write_buffer/validator.rs
Labels: v3

#25593 feat: meta_caches system table
  influxdb3/tests/server/flight.rs
  influxdb3/tests/server/main.rs
  influxdb3/tests/server/system_tables.rs
  influxdb3_cache/src/meta_cache/cache.rs
  influxdb3_cache/src/meta_cache/provider.rs
  influxdb3_server/src/system_tables/meta_caches.rs
  influxdb3_server/src/system_tables/mod.rs
Labels: v3

#25595 feat: CLI to create and delete metadata caches
  influxdb3/src/commands/meta_cache/create.rs
  influxdb3/src/commands/meta_cache/delete.rs
  influxdb3/src/commands/meta_cache/mod.rs
  influxdb3/src/main.rs
  influxdb3/tests/server/cli.rs
  influxdb3_client/src/lib.rs
Labels: v3

#25598 refactor: display column names for predicates in EXPLAIN for metadata cache
  influxdb3_cache/src/meta_cache/mod.rs
  influxdb3_cache/src/meta_cache/table_function.rs
Labels: v3

#25599 feat: remove metadata caches on db and table delete
  influxdb3_cache/src/meta_cache/provider.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
Labels: v3

#25604 fix: plan queries on DF threadpool to not block IO in REST API
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor.rs
  influxdb3_server/src/query_planner.rs
Labels: v3

#25605 chore: upgrade to rust 1.83.0
  influxdb3_client/src/lib.rs
  influxdb3_write/src/last_cache/mod.rs
  rust-toolchain.toml
Labels: v3
