Repository influxdata/influxdb, pull requests merged in 2024-08, with the labels that each got.

#25207 feat: add hook for optimizing series reads based on authorizer
  internal/authorizer.go
  query/executor.go
  query/subquery_test.go
  services/meta/data.go
  tsdb/index.go
  tsdb/store.go
Labels: area/auth, 1.x

#25210 refactor: Move Catalog into influxdb3_catalog crate
  Cargo.lock
  Cargo.toml
  deny.toml
  influxdb3_catalog/Cargo.toml
  influxdb3_catalog/src/catalog.rs
  influxdb3_catalog/src/lib.rs
  influxdb3_catalog/src/serialize.rs
  influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__catalog_serialization.snap
  influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_last_cache.snap
  influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_series_keys.snap
  influxdb3_server/Cargo.toml
  influxdb3_server/src/http.rs
  influxdb3_server/src/query_executor.rs
  influxdb3_server/src/system_tables/last_caches.rs
  influxdb3_server/src/system_tables/mod.rs
  influxdb3_write/Cargo.toml
  influxdb3_write/src/last_cache/mod.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/persister.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
  influxdb3_write/src/write_buffer/validator.rs
Labels: v3

#25211 fix: wal skip persist and notify if empty buffer
  influxdb3_wal/src/object_store.rs
  influxdb3_write/src/write_buffer/mod.rs
Labels: v3

#25219 fix: make ParquetChunk fields and mod chunk pub
  Cargo.lock
  influxdb3_write/src/chunk.rs
  influxdb3_write/src/lib.rs
Labels: v3

#25213 fix: query bugs with buffer
  Cargo.lock
  influxdb3/tests/server/query.rs
  influxdb3_wal/src/lib.rs
  influxdb3_wal/src/object_store.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
  influxdb3_write/src/write_buffer/table_buffer.rs
Labels: v3

#25224 feat: use host identifier prefix in object store paths
  influxdb3/src/commands/serve.rs
  influxdb3/tests/server/main.rs
  influxdb3_server/src/lib.rs
  influxdb3_wal/src/object_store.rs
  influxdb3_write/src/last_cache/mod.rs
  influxdb3_write/src/paths.rs
  influxdb3_write/src/persister.rs
  influxdb3_write/src/write_buffer/mod.rs
Labels: v3

#25225 feat: add `system.parquet_files` table
  Cargo.lock
  Cargo.toml
  influxdb3/src/commands/serve.rs
  influxdb3/tests/server/flight.rs
  influxdb3_server/Cargo.toml
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor.rs
  influxdb3_server/src/system_tables/last_caches.rs
  influxdb3_server/src/system_tables/mod.rs
  influxdb3_server/src/system_tables/parquet_files.rs
  influxdb3_wal/src/lib.rs
  influxdb3_wal/src/object_store.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/persister.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
Labels: v3

#25230 fix: un-pub QueryableBuffer and fix compile errors
  influxdb3_server/src/query_executor.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
Labels: v3

#25228 refactor: Make Level0Duration part of WAL
  Cargo.lock
  influxdb3/src/commands/serve.rs
  influxdb3_server/src/lib.rs
  influxdb3_wal/Cargo.toml
  influxdb3_wal/src/lib.rs
  influxdb3_wal/src/object_store.rs
  influxdb3_wal/src/snapshot_tracker.rs
  influxdb3_write/src/last_cache/mod.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/persisted_files.rs
  influxdb3_write/src/write_buffer/validator.rs
Labels: v3

#25231 fix: main
  influxdb3_server/src/query_executor.rs
Labels: v3

#25233 feat: Add last cache create/delete to WAL
  influxdb3_catalog/src/catalog.rs
  influxdb3_catalog/src/serialize.rs
  influxdb3_server/src/http.rs
  influxdb3_server/src/system_tables/last_caches.rs
  influxdb3_wal/src/lib.rs
  influxdb3_wal/src/object_store.rs
  influxdb3_write/src/last_cache/mod.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-after-allowing-time-to-persist-segments-after-delete.snap
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-after-last-cache-create-and-new-field.snap
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-create.snap
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-delete.snap
  influxdb3_write/src/write_buffer/validator.rs
Labels: v3

#25236 feat: Catalog apply_catalog_batch only updates if new
  influxdb3_catalog/src/catalog.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-after-last-cache-create-and-new-field.snap
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-delete.snap
Labels: v3

#25240 fix: GROUP BY queries with offset that crosses a DST boundary fail. (#25082)
  query/iterator.go
  query/iterator_test.go
Labels: area/queries, kind/bug, 1.x, team/edge

#25241 fix: prevent an infinite loop in measurementFieldSetChangeMgr (#25155)
  tsdb/shard.go
Labels: area/tsm, kind/bug, team/edge

#25242 fix: Store.validateArgs wrongfully overwriting start, end unix time (#25146) (#25165)
  services/storage/store.go
Labels: kind/bug, area/flux, team/edge

#25243 fix(tsi1): fix data race between appendEntry and FlushAndSync tsi1.(*LogFile) (#25182)
  tsdb/index/tsi1/log_file.go
Labels: kind/bug, area/tsi, team/edge

#25248 build(flux): update flux to v0.195.2
  go.mod
  go.sum
Labels: area/performance, area/flux, area/2.x

#25252 chore: ignore sqlx rustsec advisory
  Cargo.lock
  deny.toml
Labels: v3

#25251 chore: core sync and add reqwest json feature
  Cargo.lock
  Cargo.toml
Labels: v3

#25255 feat: snapshots track their own sequence number
  influxdb3_catalog/src/catalog.rs
  influxdb3_wal/src/lib.rs
  influxdb3_wal/src/object_store.rs
  influxdb3_wal/src/snapshot_tracker.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/paths.rs
  influxdb3_write/src/persister.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
Labels: v3

#25260 refactor: remove `Persister` trait in favour of concrete implementation
  deny.toml
  influxdb3/src/commands/serve.rs
  influxdb3_server/src/builder.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor.rs
  influxdb3_write/src/last_cache/mod.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/persister.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
Labels: v3

#25264 refactor: use more `dyn Trait` in write buffer
  influxdb3/src/commands/serve.rs
  influxdb3_server/src/builder.rs
  influxdb3_server/src/http.rs
  influxdb3_server/src/http/v1.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor.rs
  influxdb3_write/src/last_cache/mod.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
Labels: v3

#25273 refactor: move catalog and last cache initialization out of write buffer
  Cargo.lock
  influxdb3/Cargo.toml
  influxdb3/src/commands/serve.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor.rs
  influxdb3_write/src/last_cache/mod.rs
  influxdb3_write/src/persister.rs
  influxdb3_write/src/write_buffer/mod.rs
Labels: v3
