Repository influxdata/influxdb, pull requests merged in 2024-05, with the labels that each got.

#24940 chore: update google.golang.org/protobuf to 1.33.0
  go.mod
  go.sum
  influxql/query/internal/internal.pb.go
  pkg/tracing/wire/binary.pb.go
  storage/reads/datatypes/predicate.pb.go
  storage/reads/datatypes/storage_common.pb.go
  tsdb/internal/fieldsindex.pb.go
  v1/services/meta/internal/meta.pb.go
  v1/services/storage/source.pb.go
Labels: security, kind/enhancement, area/2.x, security/negligible

#24957 fix: ensure TSMBatchKeyIterator closes all TSMReaders
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/file_store.go
Labels: area/tsm, kind/bug, 1.x, team/edge

#24963 fix: ensure TSMBatchKeyIterator and FileStore close all TSMReaders (#24957)
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/file_store.go
Labels: area/tsm, kind/bug, 1.x, team/edge

#24964 fix: ensure TSMBatchKeyIterator and FileStore close all TSMReaders (#24957)
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/file_store.go
Labels: area/tsm, kind/bug, area/2.x, team/edge

#24967 chore: clean up heappy, pprof, and jemalloc
  .circleci/config.yml
  .gitignore
  Cargo.lock
  influxdb3/Cargo.toml
  influxdb3/src/main.rs
  influxdb3_process/Cargo.toml
  influxdb3_process/src/lib.rs
  influxdb3_server/src/http.rs
Labels: v3

#24965 fix: ensure TSMBatchKeyIterator and FileStore close all TSMReaders (#24957) (#24964)
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/file_store.go
Labels: area/tsm, kind/bug, area/2.x, team/edge

#24969 chore: remove `_series_id`
  Cargo.lock
  influxdb3/tests/server/query.rs
  influxdb3_server/src/lib.rs
  influxdb3_write/src/catalog.rs
  influxdb3_write/src/write_buffer/buffer_segment.rs
  influxdb3_write/src/write_buffer/loader.rs
  influxdb3_write/src/write_buffer/mod.rs
Labels: v3, epic/perf-prototyping

#24991 chore(README): add preliminary and basic usage instructions
  README.md
Labels: v3

#24982 chore: use latest `influxdb3_core` changes
  Cargo.lock
  Cargo.toml
  influxdb3/src/commands/serve.rs
  influxdb3_server/Cargo.toml
  influxdb3_server/src/grpc.rs
  influxdb3_server/src/http.rs
  influxdb3_server/src/http/v1.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/wal.rs
Labels: v3

#24975 fix: return MergeIterator.Close errors
  query/iterator.gen.go
  query/iterator.gen.go.tmpl
Labels: area/queries, kind/bug, 1.x, team/edge

#24996 fix: return MergeIterator.Close errors (#24975)
  query/iterator.gen.go
  query/iterator.gen.go.tmpl
Labels: area/queries, area/tsm, kind/bug, 1.x, team/edge

#24997 fix: return MergeIterator.Close errors (#24975)
  influxql/query/iterator.gen.go
  influxql/query/iterator.gen.go.tmpl
Labels: area/queries, area/tsm, kind/bug, team/edge

#24998 fix: return MergeIterator.Close errors (#24975) (#24997)
  influxql/query/iterator.gen.go
  influxql/query/iterator.gen.go.tmpl
Labels: area/queries, area/tsm, kind/bug, team/edge

#25005 chore: sync latest core
  Cargo.lock
  Cargo.toml
Labels: v3

#25012 refactor: cleanup unused methods in Bufferer trait
  influxdb3_write/src/lib.rs
  influxdb3_write/src/wal.rs
  influxdb3_write/src/write_buffer/mod.rs
Labels: v3

#24990 feat: add SystemSchemaProvider to QueryExecutor
  influxdb3_server/src/query_executor.rs
Labels: v3

#24992 feat: add the `system.queries` table
  Cargo.lock
  influxdb3/src/commands/serve.rs
  influxdb3/tests/server/main.rs
  influxdb3/tests/server/system_tables.rs
  influxdb3_server/Cargo.toml
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor.rs
Labels: v3

#25000 refactor: expose system tables by default in edge/pro
  influxdb3/tests/server/flight.rs
  influxdb3/tests/server/main.rs
  influxdb3/tests/server/system_tables.rs
  influxdb3_server/src/query_executor.rs
Labels: v3

#25017 feat: Add last_write_time and table buffer size
  influxdb3_write/src/write_buffer/buffer_segment.rs
  influxdb3_write/src/write_buffer/table_buffer.rs
Labels: v3

#25022 fix: writes with incorrect schema should fail
  influxdb3/tests/server/write.rs
  influxdb3_write/src/write_buffer/flusher.rs
  influxdb3_write/src/write_buffer/mod.rs
Labels: v3
