Repository influxdata/influxdb, pull requests merged in 2024-04, with the labels that each got.

#24864 feat: `/ping` API to serve version and revision
  .circleci/config.yml
  Cargo.lock
  Cargo.toml
  influxdb3/Cargo.toml
  influxdb3/src/commands/serve.rs
  influxdb3/src/main.rs
  influxdb3/tests/server/main.rs
  influxdb3/tests/server/ping.rs
  influxdb3_process/Cargo.toml
  influxdb3_process/build.rs
  influxdb3_process/src/jemalloc.rs
  influxdb3_process/src/lib.rs
  influxdb3_server/Cargo.toml
  influxdb3_server/src/http.rs
  influxdb3_write/src/paths.rs
Labels: v3

#24872 fix: make write load_generators wait
  influxdb3_load_generator/src/commands/write.rs
Labels: v3, epic/perf-prototyping

#24871 feat: report system stats in load generator
  Cargo.lock
  Cargo.toml
  influxdb3_load_generator/Cargo.toml
  influxdb3_load_generator/src/commands/query.rs
  influxdb3_load_generator/src/commands/write.rs
  influxdb3_load_generator/src/report.rs
  influxdb3_process/src/lib.rs
Labels: v3, epic/perf-prototyping

#24876 chore: update to latest core
  Cargo.lock
  Cargo.toml
  influxdb3/tests/server/flight.rs
Labels: v3

#24881 refactor: make end argument common to query and write load generation
  influxdb3_load_generator/src/commands/common.rs
  influxdb3_load_generator/src/commands/full.rs
  influxdb3_load_generator/src/commands/query.rs
  influxdb3_load_generator/src/commands/write.rs
  influxdb3_load_generator/src/report.rs
  influxdb3_write/src/write_buffer/table_buffer.rs
Labels: v3, epic/perf-prototyping

#24857 feat: add optional stricter password requirements
  cmd/influxd/launcher/cmd.go
  cmd/influxd/launcher/launcher.go
  cmd/influxd/recovery/user/user_test.go
  cmd/influxd/upgrade/upgrade.go
  kit/platform/errors/error_user.go
  session/http_server.go
  tenant/service.go
  tenant/service_onboarding_test.go
  tenant/service_user.go
  tenant/service_user_test.go
  tenant/storage_user.go
  tenant/storage_user_test.go
  testing/passwords.go
  v1/authorization/authorizer_test.go
  v1/authorization/caching_password_service_test.go
  v1/authorization/service.go
  v1/authorization/service_password.go
Labels: kind/feature-request, area/cli, area/auth, area/api, area/2.x

#24887 fix: additional constant time code
  tenant/service_user.go
Labels: security, kind/enhancement, area/auth, team/edge, security/misc

#24889 feat: add basic load generator comparison app
  influxdb3_load_generator/analysis/README.md
  influxdb3_load_generator/analysis/app.py
  influxdb3_load_generator/analysis/templates/index.html
Labels: v3, epic/perf-prototyping

#24890 feat: add optional stricter password requirements (#24857)
  cmd/influxd/launcher/cmd.go
  cmd/influxd/launcher/launcher.go
  cmd/influxd/recovery/user/user_test.go
  cmd/influxd/upgrade/upgrade.go
  kit/platform/errors/error_user.go
  session/http_server.go
  tenant/service.go
  tenant/service_onboarding_test.go
  tenant/service_user.go
  tenant/service_user_test.go
  tenant/storage_user.go
  tenant/storage_user_test.go
  testing/passwords.go
  v1/authorization/authorizer_test.go
  v1/authorization/caching_password_service_test.go
  v1/authorization/service.go
  v1/authorization/service_password.go
Labels: security, kind/enhancement, area/auth, area/2.x, team/edge, security/misc

#24898 fix: additional constant time code (#24887)
  tenant/service_user.go
Labels: security, kind/enhancement, area/auth, team/edge, security/misc

#24893 fix: improved shard deletion (#24602)
  tsdb/store.go
Labels: area/tsm, kind/bug, 1.x, team/edge

#24894 fix: return and respect cursor errors (#24791)
  cmd/influx_tools/internal/storage/resultset.go
  storage/reads/array_cursor.gen.go
  storage/reads/array_cursor.gen.go.tmpl
  storage/reads/array_cursor.go
  tsdb/engine/tsm1/array_cursor.gen.go
  tsdb/engine/tsm1/array_cursor.gen.go.tmpl
  tsdb/engine/tsm1/array_cursor_iterator.gen.go
  tsdb/engine/tsm1/array_cursor_iterator.gen.go.tmpl
  tsdb/engine/tsm1/array_cursor_iterator.go
  tsdb/engine/tsm1/array_cursor_test.go
Labels: area/queries, area/tsm, kind/bug, 1.x, team/edge

#24914 feat: QoL improvements to the load generator and analysis tools
  influxdb3_load_generator/analysis/app.py
  influxdb3_load_generator/analysis/templates/index.html
  influxdb3_load_generator/src/commands/common.rs
Labels: v3, epic/perf-prototyping

#24937 chore: point at latest core
  Cargo.lock
  Cargo.toml
Labels: v3
