Repository influxdata/influxdb, pull requests merged in 2024-01, with the labels that each got.

#24530 fix: prevent retention service creating orphaned shard files
  cmd/influxd/run/server.go
  go.mod
  go.sum
  services/meta/client.go
  services/meta/client_test.go
  services/meta/data.go
  services/retention/helpers/test_helpers.go
  services/retention/service.go
  services/retention/service_test.go
  toml/toml.go
Labels: area/retention policies, kind/bug, 1.x, team/edge

#24547 fix: prevent retention service creating orphaned shard files (#24530)
  go.mod
  go.sum
  storage/engine.go
  v1/services/meta/client.go
  v1/services/meta/client_test.go
  v1/services/meta/data.go
  v1/services/retention/helpers/test_helpers.go
  v1/services/retention/service.go
  v1/services/retention/service_test.go
Labels: area/tsm, kind/bug, area/2.x, team/edge

#24548 fix: prevent retention service creating orphaned shard files (#24530)(#24547)
  go.mod
  go.sum
  storage/engine.go
  v1/services/meta/client.go
  v1/services/meta/client_test.go
  v1/services/meta/data.go
  v1/services/retention/helpers/test_helpers.go
  v1/services/retention/service.go
  v1/services/retention/service_test.go
Labels: area/tsm, kind/bug, area/2.x, team/edge

#24570 feat: add basic wal implementation for Edge
  Cargo.lock
  influxdb3/src/commands/serve.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor.rs
  influxdb3_write/Cargo.toml
  influxdb3_write/src/lib.rs
  influxdb3_write/src/wal.rs
  influxdb3_write/src/write_buffer.rs
Labels: v3

#24505 chore: upgrade flux
  cmd/influx_tools/internal/format/binary/tools_binary.pb.go
  cmd/influxd/backup_util/internal/backup_util.pb.go
  go.mod
  go.sum
  pkg/tracing/wire/binary.pb.go
  query/internal/internal.pb.go
  services/meta/internal/meta.pb.go
  services/storage/source.pb.go
  storage/reads/datatypes/predicate.pb.go
  storage/reads/datatypes/storage_common.pb.go
  tsdb/internal/fieldsindex.pb.go
Labels: kind/enhancement, area/flux, 1.x, team/edge

#24504 chore: upgrade flux
  cmd/influx_tools/internal/format/binary/tools_binary.pb.go
  cmd/influxd/backup_util/internal/backup_util.pb.go
  go.mod
  go.sum
  pkg/tracing/wire/binary.pb.go
  query/internal/internal.pb.go
  services/meta/internal/meta.pb.go
  services/storage/source.pb.go
  storage/reads/datatypes/predicate.pb.go
  storage/reads/datatypes/storage_common.pb.go
  tsdb/internal/fieldsindex.pb.go
Labels: kind/enhancement, area/flux, 1.x, team/edge

#24588 feat: Implement Persister for PersisterImpl
  Cargo.lock
  influxdb3_write/Cargo.toml
  influxdb3_write/src/catalog.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/paths.rs
  influxdb3_write/src/persister.rs
Labels: v3
