Repository influxdata/influxdb, pull requests merged in 2024-10, with the labels that each got.

#25415 feat: enable parquet cache config through CLI
  influxdb3/src/commands/serve.rs
  influxdb3_write/src/parquet_cache/mod.rs
Labels: v3

#25416 fix: use correct multiplier for parquet cache size
  influxdb3/src/commands/serve.rs
Labels: v3

#25419 chore: unblock CI for tonic/hyper audit failures
  deny.toml
Labels: v3

#25420 test: add test helpers for object store types
  Cargo.lock
  Cargo.toml
  influxdb3_test_helpers/Cargo.toml
  influxdb3_test_helpers/src/lib.rs
  influxdb3_test_helpers/src/object_store/mod.rs
  influxdb3_write/Cargo.toml
  influxdb3_write/src/parquet_cache/mod.rs
  influxdb3_write/src/write_buffer/mod.rs
Labels: v3

#25426 fix: flaky parquet cache for real this time
  influxdb3_write/src/parquet_cache/mod.rs
Labels: v3

#25428 fix: add host id to parquet file paths
  influxdb3_write/src/paths.rs
  influxdb3_write/src/persister.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
Labels: v3

#25433 chore: cargo update
  Cargo.lock
Labels: v3

#25444 feat: add option to flush WAL on shutdown
  cmd/influxd/launcher/cmd.go
  tsdb/config.go
  tsdb/config_test.go
  tsdb/engine.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
  tsdb/engine/tsm1/wal.go
  tsdb/shard.go
  tsdb/store.go
  tsdb/store_test.go
Labels: area/tsm, kind/feature, area/2.x

#25452 feat: add option to flush WAL on shutdown
  cmd/influxd/launcher/cmd.go
  tsdb/config.go
  tsdb/config_test.go
  tsdb/engine.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
  tsdb/engine/tsm1/wal.go
  tsdb/shard.go
  tsdb/store.go
  tsdb/store_test.go
Labels: area/tsm, kind/feature, area/2.x

#25468 refactor: separate catalog schema API
  influxdb3/src/commands/serve.rs
  influxdb3_catalog/src/catalog.rs
  influxdb3_catalog/src/lib.rs
  influxdb3_server/src/http.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor.rs
  influxdb3_server/src/system_tables/parquet_files.rs
  influxdb3_write/src/last_cache/mod.rs
  influxdb3_write/src/last_cache/table_function.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
Labels: v3

#25472 feat: allow `influx -import` to import from stdin
  cmd/influx/main.go
  importer/v8/importer.go
Labels: area/cli, 1.x

#25479 refactor: changes needed for IDs in pro
  influxdb3/src/commands/serve.rs
  influxdb3/tests/server/main.rs
  influxdb3_catalog/src/catalog.rs
  influxdb3_catalog/src/lib.rs
  influxdb3_id/src/lib.rs
  influxdb3_server/src/http.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor.rs
  influxdb3_server/src/system_tables/parquet_files.rs
  influxdb3_telemetry/src/store.rs
  influxdb3_write/src/last_cache/mod.rs
  influxdb3_write/src/last_cache/table_function.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
Labels: v3

#25482 feat: add insta crate yaml feature
  Cargo.toml
Labels: v3

#25483 refactor: method on catalog did not need mut self
  influxdb3_catalog/src/catalog.rs
  influxdb3_write/src/last_cache/mod.rs
Labels: v3

#25485 fix: last cache cli parser bug
  influxdb3/src/commands/common.rs
  influxdb3/src/commands/last_cache/create.rs
Labels: v3

#25490 fix: correct flaky test (TestLauncher_PIDFile_Locked)
  cmd/influxd/launcher/launcher_test.go
Labels: kind/bug, area/2.x

#25499 feat: add `--pid-file` option to write PID files
  cmd/influxd/launcher/cmd.go
  cmd/influxd/launcher/launcher.go
  cmd/influxd/launcher/launcher_helpers.go
  cmd/influxd/launcher/launcher_test.go
Labels: area/configuration, kind/feature, area/2.x

#25505 chore: upgrade ui assets package to 2.7.10
  scripts/fetch-ui-assets.sh
Labels: kind/bug, area/ui, kind/feature, area/2.x

#25477 fix: strip double quotes from measurement names in v2/delete (#25407)
  services/httpd/handler.go
  services/httpd/handler_test.go
Labels: area/tsm, kind/bug, area/api, team/edge
