Repository influxdata/influxdb, pull requests merged in 2024-09, with the labels that each got.

#25276 test: repro for dropped wal files during snapshot
  influxdb3_server/src/query_executor.rs
  influxdb3_wal/src/snapshot_tracker.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
Labels: v3

#25285 chore: updates for pro
  influxdb3_wal/src/lib.rs
  influxdb3_wal/src/object_store.rs
  influxdb3_wal/src/serialize.rs
  influxdb3_write/src/last_cache/mod.rs
  influxdb3_write/src/persister.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/persisted_files.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
  influxdb3_write/src/write_buffer/table_buffer.rs
Labels: v3

#25284 chore: sync to latest core
  Cargo.lock
  Cargo.toml
  influxdb3/tests/server/write.rs
  influxdb3_server/src/query_executor.rs
  influxdb3_server/src/system_tables/mod.rs
  influxdb3_server/src/system_tables/queries.rs
  influxdb3_write/src/last_cache/mod.rs
  influxdb3_write/src/last_cache/table_function.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
Labels: v3

#25309 fix: add additional logging on loading fields.idxl files
  tsdb/shard.go
Labels: area/tsm, kind/enhancement, 1.x, area/logging

#25318 fix: add additional logging on loading fields.idxl files (#25309)
  tsdb/shard.go
Labels: area/tsm, kind/enhancement, 1.x, area/logging

#25314 chore: improve error messages and logging during shard opening
  tsdb/engine.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
  tsdb/engine/tsm1/wal.go
  tsdb/index.go
  tsdb/shard.go
  tsdb/store.go
  tsdb/store_test.go
Labels: area/tsm, area/logging

#25319 fix: add additional logging on loading fields.idxl files (#25309)
  tsdb/shard.go
Labels: area/tsm, kind/enhancement, area/2.x, area/logging

#25323 chore: improve error messages and logging during shard opening
  tsdb/engine.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
  tsdb/engine/tsm1/wal.go
  tsdb/index.go
  tsdb/shard.go
  tsdb/store.go
  tsdb/store_test.go
Labels: area/tsm, 1.x

#25324 fix: add additional logging on loading fields.idxl files (#25309) (#25319)
  tsdb/shard.go
Labels: area/tsm, kind/enhancement, area/logging

#25322 test: split e2e test harness up for pro
  influxdb3/tests/server/auth.rs
  influxdb3/tests/server/main.rs
Labels: v3

#25330 feat: add watch to writebuffer for persisted snapshots
  influxdb3_write/src/lib.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
Labels: v3

#25333 chore: improve error messages and logging during shard opening
  tsdb/engine.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
  tsdb/engine/tsm1/wal.go
  tsdb/index.go
  tsdb/shard.go
  tsdb/store.go
  tsdb/store_test.go
Labels: area/tsm, area/2.x

#25340 fix: do not rename files on mmap failure
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
  tsdb/engine/tsm1/file_store_internal_test.go
  tsdb/engine/tsm1/file_store_test.go
  tsdb/engine/tsm1/reader.go
Labels: area/tsm, area/2.x

#25345 fix(tsi1/partition/test): fix data races in test code (#57) (#25338)
  tsdb/index/tsi1/index.go
  tsdb/index/tsi1/partition.go
  tsdb/index/tsi1/partition_test.go
Labels: kind/bug, area/tsi, area/tests, team/edge

#25344 fix(tsi1/partition/test): fix data races in test code (#57) (#25338)
  tsdb/index/tsi1/partition.go
Labels: kind/bug, area/tsi, area/tests, team/edge

#25352 fix(tsi1/partition/test): fix data races in test code (#57) (#25338) …
  tsdb/index/tsi1/index.go
  tsdb/index/tsi1/partition.go
  tsdb/index/tsi1/partition_test.go
Labels: kind/bug, area/tsi, area/tests, team/edge

#25364 chore: upgrade to go1.22.7
  .circleci/config.yml
  go.mod
Labels: 1.x

#25365 feat(ci): Update master-1.x to go1.22.7
  .circleci/config.yml
  go.mod
Labels: 1.x

#25377 feat: memory-cached object store for parquet files
  Cargo.lock
  Cargo.toml
  influxdb3/src/commands/serve.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor.rs
  influxdb3_write/Cargo.toml
  influxdb3_write/src/last_cache/mod.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/parquet_cache/mod.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
Labels: v3

#25356 fix: do not rename files on mmap failure
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
  tsdb/engine/tsm1/file_store_internal_test.go
  tsdb/engine/tsm1/file_store_test.go
  tsdb/engine/tsm1/reader.go
Labels: area/tsm, area/2.x

#25358 chore: replace uses of %v with %w
  tsdb/engine/tsm1/file_store.go
Labels: area/tsm, kind/tech-debt, area/2.x

#25400 chore: replace uses of %v with %w
  tsdb/engine/tsm1/file_store.go
Labels: area/tsm, kind/tech-debt, area/2.x

#25389 refactor: parquet cache with less locking
  Cargo.lock
  influxdb3/src/commands/serve.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor.rs
  influxdb3_write/Cargo.toml
  influxdb3_write/src/last_cache/mod.rs
  influxdb3_write/src/parquet_cache/mod.rs
  influxdb3_write/src/write_buffer/mod.rs
Labels: v3

#25407 fix: strip double quotes from measurement names in v2/delete
  services/httpd/handler.go
  services/httpd/handler_test.go
Labels: area/tsm, 1.x, area/api, team/edge

#25410 chore: remove unused parquet cache code
  influxdb3_write/src/cache.rs
  influxdb3_write/src/lib.rs
Labels: v3

#25411 test: check parquet cache in the write buffer
  influxdb3/src/commands/serve.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor.rs
  influxdb3_write/src/last_cache/mod.rs
  influxdb3_write/src/parquet_cache/mod.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
Labels: v3
