Repository influxdata/influxdb, pull requests merged in 2024-06, with the labels that each got.

#25042 refactor: add dedicated type for serializaing catalog tables
  Cargo.lock
  Cargo.toml
  influxdb3_write/Cargo.toml
  influxdb3_write/src/catalog.rs
  influxdb3_write/src/catalog/serialize.rs
  influxdb3_write/src/persister.rs
  influxdb3_write/src/snapshots/influxdb3_write__catalog__tests__catalog_serialization.snap
  influxdb3_write/src/write_buffer/buffer_segment.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/table_buffer.rs
Labels: v3

#25043 fix: ignore empty index error deleting last measurement (#25037)
  cmd/influx_inspect/deletetsm/deletetsm.go
Labels: area/tsm, kind/bug, 1.x, team/edge

#25055 fix: prevent retention service from hanging
  cmd/influx_tools/compact/command.go
  internal/tsdb_store.go
  services/retention/service.go
  services/retention/service_test.go
  tsdb/engine.go
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
  tsdb/engine/tsm1/file_store_test.go
  tsdb/shard.go
  tsdb/shard_test.go
  tsdb/store.go
  tsdb/store_test.go
Labels: area/tsm, kind/bug, team/edge

#25060 build(flux): update flux to v0.195.1
  go.mod
  go.sum
  prometheus/codec.go
  prometheus/codec_test.go
  prometheus/example_test.go
  prometheus/filter_test.go
  scripts/ci/check-system-go-matches-go-mod.sh
  telemetry/handler.go
  telemetry/handler_test.go
  telemetry/push.go
  telemetry/push_test.go
Labels: area/flux, area/2.x, team/edge

#25064 fix: prevent retention service from hanging
  cmd/influx_tools/compact/command.go
  internal/tsdb_store.go
  services/retention/service.go
  services/retention/service_test.go
  tsdb/engine.go
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
  tsdb/engine/tsm1/file_store_test.go
  tsdb/shard.go
  tsdb/shard_test.go
  tsdb/store.go
  tsdb/store_test.go
Labels: area/storage, 1.x, team/edge

#25066 feat: v3 write API with series key
  Cargo.lock
  Cargo.toml
  influxdb3/tests/server/flight.rs
  influxdb3/tests/server/main.rs
  influxdb3/tests/server/write.rs
  influxdb3_server/src/http.rs
  influxdb3_write/src/catalog.rs
  influxdb3_write/src/catalog/serialize.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/write_buffer/buffer_segment.rs
  influxdb3_write/src/write_buffer/flusher.rs
  influxdb3_write/src/write_buffer/loader.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/segment_state.rs
  influxdb3_write/src/write_buffer/table_buffer.rs
  influxdb3_write/src/write_buffer/validator.rs
Labels: v3

#24858 feat: disable file:// urls when hardening enabled
  cmd/influxd/launcher/cmd.go
  cmd/influxd/launcher/launcher.go
  pkg/fs/special.go
  pkg/fs/special_linux.go
  pkger/parser.go
  pkger/parser_test.go
  pkger/service.go
  pkger/service_test.go
Labels: area/2.x

#25082 fix: GROUP BY queries with offset that crosses a DST boundary fail.
  query/iterator.go
  query/iterator_test.go
Labels: area/queries, kind/bug, 1.x, team/edge

#25087 fix: GROUP BY queries with offset that crosses a DST boundary fail. (#25082)
  influxql/query/iterator.go
  influxql/query/iterator_test.go
Labels: area/queries, kind/bug, area/2.x, team/edge

#25030 feat: add csv influx v1
  Cargo.lock
  influxdb3/tests/server/main.rs
  influxdb3/tests/server/query.rs
  influxdb3_server/Cargo.toml
  influxdb3_server/src/http.rs
  influxdb3_server/src/http/v1.rs
Labels: v3

#25089 fix: GROUP BY queries with offset that crosses a DST boundary fail. (#25082) (#25087)
  influxql/query/iterator.go
  influxql/query/iterator_test.go
Labels: area/queries, kind/bug, area/2.x, team/edge

#25102 chore: clean up log statements in query_executor
  Cargo.lock
  influxdb3_server/src/query_executor.rs
Labels: v3

#25108 refactor: move persisted files out of segment state
  influxdb3_write/src/write_buffer/flusher.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/persisted_files.rs
  influxdb3_write/src/write_buffer/persister.rs
  influxdb3_write/src/write_buffer/segment_state.rs
Labels: v3

#25107 chore: Updating 1.x README for clarity and direction
  README.md
  assets/influxdb-logo-dark.png
  assets/influxdb-logo.png
Labels: 1.x

#25103 chore: Update README to approved version.
  README.md
  assets/influxdb-logo-dark.png
Labels: area/2.x

#25112 fix: preserve time zone information in Task Scheduler
  task/backend/scheduler/scheduler_test.go
  task/backend/scheduler/treescheduler.go
Labels: kind/bug, area/tasks, area/2.x, team/edge

#25113 fix: preserve time zone information in Task Scheduler (#25112)
  task/backend/scheduler/scheduler_test.go
  task/backend/scheduler/treescheduler.go
Labels: kind/bug, area/tasks, area/2.x, team/edge
