Repository influxdata/influxdb, pull requests merged in 2024-03, with the labels that each got.

#24696 feat: add the `api/v3/query_influxql` API
  Cargo.lock
  Cargo.toml
  influxdb3/Cargo.toml
  influxdb3/src/commands/query.rs
  influxdb3/tests/server/auth.rs
  influxdb3/tests/server/flight.rs
  influxdb3/tests/server/main.rs
  influxdb3/tests/server/query.rs
  influxdb3_client/src/lib.rs
  influxdb3_server/Cargo.toml
  influxdb3_server/src/http.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor.rs
  influxdb3_write/Cargo.toml
  influxdb3_write/src/catalog.rs
  influxdb3_write/src/write_buffer/loader.rs
  iox_query_influxql_rewrite/Cargo.toml
  iox_query_influxql_rewrite/src/lib.rs
Labels: v3

#24703 feat: Add limits for InfluxDB Edge
  influxdb3/tests/server/flight.rs
  influxdb3/tests/server/limits.rs
  influxdb3/tests/server/main.rs
  influxdb3/tests/server/query.rs
  influxdb3_server/src/http.rs
  influxdb3_write/src/catalog.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/write_buffer/mod.rs
Labels: v3

#24729 feat: support `SHOW RETENTION POLICIES`
  Cargo.lock
  Cargo.toml
  influxdb3/tests/server/query.rs
  influxdb3_server/Cargo.toml
  influxdb3_server/src/http.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor.rs
Labels: v3

#24732 test: add tests to check InfluxQL over Flight
  Cargo.lock
  influxdb3/tests/server/flight.rs
  influxdb3/tests/server/main.rs
Labels: v3

#24737 chore: gate `limits` test behind a feature flag
  .circleci/config.yml
  influxdb3/Cargo.toml
  influxdb3/tests/server/limits.rs
Labels: v3

#24743 refactor: use dynamic dispatch for Authorizer
  influxdb3/src/commands/serve.rs
  influxdb3_server/src/builder.rs
  influxdb3_server/src/http.rs
  influxdb3_server/src/lib.rs
Labels: v3

#24738 feat: implement `Authorizer` to authorize all HTTP requests
  Cargo.lock
  influxdb3/Cargo.toml
  influxdb3/src/commands/serve.rs
  influxdb3/tests/server/auth.rs
  influxdb3/tests/server/main.rs
  influxdb3_server/src/auth.rs
  influxdb3_server/src/builder.rs
  influxdb3_server/src/http.rs
  influxdb3_server/src/lib.rs
Labels: v3

#24745 feat: Segment the write buffer on time
  Cargo.lock
  influxdb3/src/commands/serve.rs
  influxdb3_server/src/builder.rs
  influxdb3_server/src/http.rs
  influxdb3_server/src/lib.rs
  influxdb3_write/Cargo.toml
  influxdb3_write/src/lib.rs
  influxdb3_write/src/paths.rs
  influxdb3_write/src/wal.rs
  influxdb3_write/src/write_buffer/buffer_segment.rs
  influxdb3_write/src/write_buffer/flusher.rs
  influxdb3_write/src/write_buffer/loader.rs
  influxdb3_write/src/write_buffer/mod.rs
Labels: v3

#24747 feat: Implement automatic segment persistence
  influxdb3_write/src/lib.rs
  influxdb3_write/src/persister.rs
  influxdb3_write/src/wal.rs
  influxdb3_write/src/write_buffer/buffer_segment.rs
  influxdb3_write/src/write_buffer/flusher.rs
  influxdb3_write/src/write_buffer/loader.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/segment_state.rs
Labels: v3

#24749 feat: wire up query from parquet files
  Cargo.lock
  influxdb3/Cargo.toml
  influxdb3/src/commands/serve.rs
  influxdb3_server/src/query_executor.rs
  influxdb3_write/Cargo.toml
  influxdb3_write/src/chunk.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/write_buffer/buffer_segment.rs
  influxdb3_write/src/write_buffer/flusher.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/segment_state.rs
Labels: v3

#24760 feat: support authenticating v1 APIs with p parameter
  influxdb3/tests/server/auth.rs
  influxdb3_server/src/http.rs
Labels: v3

#24764 chore: upgrade to influxdata/influxql v1.2.0
  go.mod
  go.sum
  query/compile_test.go
  services/storage/predicate_test.go
Labels: area/influxql, 1.x, team/edge

#24767 chore: upgrade to influxdata/influxql v1.2.0
  go.mod
  go.sum
  query/compile_test.go
  services/storage/predicate_test.go
Labels: area/influxql, 1.x, team/edge

#24746 feat: support v1 query API
  Cargo.lock
  Cargo.toml
  influxdb3/Cargo.toml
  influxdb3/tests/server/auth.rs
  influxdb3/tests/server/main.rs
  influxdb3/tests/server/query.rs
  influxdb3_server/Cargo.toml
  influxdb3_server/src/auth.rs
  influxdb3_server/src/http.rs
  influxdb3_server/src/http/v1.rs
Labels: v3

#24784 fix: do not panic when empty tags are queried
  tsdb/cursors/arrayvalues.gen.go
  tsdb/cursors/arrayvalues.gen.go.tmpl
Labels: area/queries, kind/bug, team/edge

#24785 fix: do not panic when empty tags are queried (#24784)
  tsdb/cursors/arrayvalues.gen.go
  tsdb/cursors/arrayvalues.gen.go.tmpl
Labels: area/queries, kind/bug, team/edge

#24787 fix: do not panic when empty tags are queried (#24784)
  tsdb/cursors/arrayvalues.gen.go
  tsdb/cursors/arrayvalues.gen.go.tmpl
Labels: area/queries, kind/bug, team/edge

#24786 fix: do not panic when empty tags are queried (#24784)
  tsdb/cursors/arrayvalues.gen.go
  tsdb/cursors/arrayvalues.gen.go.tmpl
Labels: area/queries, kind/bug, team/edge

#24798 chore: `influxdb3_core` update
  Cargo.lock
  Cargo.toml
  influxdb3/src/commands/serve.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor.rs
  influxdb3_write/src/chunk.rs
  influxdb3_write/src/write_buffer/mod.rs
Labels: v3

#24804 feat: support query parameters
  influxdb3/tests/server/query.rs
  influxdb3_server/src/http.rs
  influxdb3_server/src/http/v1.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor.rs
Labels: v3

#24808 feat: initial load generator implementation
  Cargo.lock
  Cargo.toml
  influxdb3_load_generator/Cargo.toml
  influxdb3_load_generator/src/commands/common.rs
  influxdb3_load_generator/src/commands/query.rs
  influxdb3_load_generator/src/commands/write.rs
  influxdb3_load_generator/src/line_protocol_generator.rs
  influxdb3_load_generator/src/main.rs
  influxdb3_load_generator/src/report.rs
  influxdb3_load_generator/src/specification.rs
  influxdb3_load_generator/src/specs/example.rs
  influxdb3_load_generator/src/specs/mod.rs
  influxdb3_load_generator/src/specs/one_mil.rs
Labels: v3

#24820 chore: add SECURITY.md
  SECURITY.md
Labels: v3

#24813 fix: catalog persist with new segment
  influxdb3_write/src/lib.rs
  influxdb3_write/src/write_buffer/buffer_segment.rs
  influxdb3_write/src/write_buffer/flusher.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/segment_state.rs
Labels: v3

#24814 fix: loader error with single wal file
  influxdb3_write/src/write_buffer/buffer_segment.rs
  influxdb3_write/src/write_buffer/loader.rs
Labels: v3

#24602 fix: improved shard deletion
  tsdb/store.go
Labels: area/tsm, kind/bug, 1.x, team/edge

#24791 fix: return and respect cursor errors
  cmd/influx_tools/internal/storage/resultset.go
  storage/reads/array_cursor.gen.go
  storage/reads/array_cursor.gen.go.tmpl
  storage/reads/array_cursor.go
  tsdb/engine/tsm1/array_cursor.gen.go
  tsdb/engine/tsm1/array_cursor.gen.go.tmpl
  tsdb/engine/tsm1/array_cursor_iterator.gen.go
  tsdb/engine/tsm1/array_cursor_iterator.gen.go.tmpl
  tsdb/engine/tsm1/array_cursor_iterator.go
  tsdb/engine/tsm1/array_cursor_test.go
Labels: area/queries, kind/bug, team/edge

#24842 feat: add `_series_id` to tables on write
  Cargo.lock
  influxdb3/tests/server/auth.rs
  influxdb3/tests/server/flight.rs
  influxdb3/tests/server/query.rs
  influxdb3_server/src/lib.rs
  influxdb3_write/Cargo.toml
  influxdb3_write/src/catalog.rs
  influxdb3_write/src/write_buffer/loader.rs
  influxdb3_write/src/write_buffer/mod.rs
Labels: v3

#24844 fix: improved shard deletion (#24602)
  tsdb/store.go
Labels: area/tsm, kind/bug, area/2.x, team/edge

#24846 fix: return and respect cursor errors (#24791)
  storage/reads/array_cursor.gen.go
  storage/reads/array_cursor.gen.go.tmpl
  storage/reads/array_cursor.go
  tsdb/engine/tsm1/array_cursor.gen.go
  tsdb/engine/tsm1/array_cursor.gen.go.tmpl
  tsdb/engine/tsm1/array_cursor_iterator.gen.go
  tsdb/engine/tsm1/array_cursor_iterator.gen.go.tmpl
  tsdb/engine/tsm1/array_cursor_iterator.go
  tsdb/engine/tsm1/array_cursor_test.go
Labels: area/tsm, kind/bug, area/2.x, team/edge

#24848 fix: improved shard deletion (#24602) (#24844)
  tsdb/store.go
Labels: area/tsm, kind/bug, area/2.x, team/edge

#24847 fix: return and respect cursor errors (#24791) (#24846)
  storage/reads/array_cursor.gen.go
  storage/reads/array_cursor.gen.go.tmpl
  storage/reads/array_cursor.go
  tsdb/engine/tsm1/array_cursor.gen.go
  tsdb/engine/tsm1/array_cursor.gen.go.tmpl
  tsdb/engine/tsm1/array_cursor_iterator.gen.go
  tsdb/engine/tsm1/array_cursor_iterator.gen.go.tmpl
  tsdb/engine/tsm1/array_cursor_iterator.go
  tsdb/engine/tsm1/array_cursor_test.go
Labels: area/queries, kind/bug, area/2.x, team/edge

#24793 feat: support v1 and v2 write APIs
  Cargo.lock
  influxdb3/tests/server/auth.rs
  influxdb3/tests/server/main.rs
  influxdb3/tests/server/write.rs
  influxdb3_client/src/lib.rs
  influxdb3_server/Cargo.toml
  influxdb3_server/src/http.rs
  influxdb3_server/src/lib.rs
  influxdb3_write/Cargo.toml
  influxdb3_write/src/lib.rs
Labels: v3

#24852 fix: tests that were broken with recent merges
  influxdb3/tests/server/write.rs
Labels: v3

#24854 feat: initial query load generator
  Cargo.lock
  influxdb3_load_generator/Cargo.toml
  influxdb3_load_generator/src/commands/common.rs
  influxdb3_load_generator/src/commands/query.rs
  influxdb3_load_generator/src/commands/write.rs
  influxdb3_load_generator/src/line_protocol_generator.rs
  influxdb3_load_generator/src/main.rs
  influxdb3_load_generator/src/query_generator.rs
  influxdb3_load_generator/src/report.rs
  influxdb3_load_generator/src/specification.rs
  influxdb3_load_generator/src/specs/example.rs
  influxdb3_load_generator/src/specs/mod.rs
  influxdb3_load_generator/src/specs/one_mil.rs
Labels: v3

#24853 refactor: buffer using Arrow builders
  influxdb3_write/src/catalog.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/write_buffer/buffer_segment.rs
  influxdb3_write/src/write_buffer/flusher.rs
  influxdb3_write/src/write_buffer/loader.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/segment_state.rs
  influxdb3_write/src/write_buffer/table_buffer.rs
Labels: v3, epic/perf-prototyping
