Repository influxdata/influxdb, pull requests merged in 2025-06, with the labels that each got.

#26488 feat: Add new logging for compaction level 5 and remove bug with holdoff
  tsdb/engine/tsm1/engine.go
Labels: kind/bug, 1.x, area/logging

#26490 feat: Add new logging for compaction level 5 and remove bug with opt holdoff time (#26488)
  tsdb/engine/tsm1/engine.go
Labels: kind/bug, 1.x, area/logging

#26491 chore: update `influxdb3_core`
  Cargo.lock
  Cargo.toml
Labels: v3

#26507 fix: do not allow _ in db names on API-based create
  influxdb3/tests/cli/mod.rs
  influxdb3_server/src/http.rs
Labels: v3

#26527 fix: stop noisy logging about phantom shards that do not belong to node
  cmd/influxd/run/server.go
  services/retention/service.go
  services/retention/service_test.go
Labels: area/retention policies, 1.x, team/edge

#26535 fix: stop noisy logging about phantom shards that do not belong to node
  cmd/influxd/run/server.go
  services/retention/service.go
  services/retention/service_test.go
Labels: area/retention policies, 1.x, team/edge

#26543 chore: stop publishing nightly changelog
  .circleci/config.yml
Labels: 1.x, area/build, team/edge

#26565 fix: stop noisy logging about phantom shards that do not belong to node
  storage/engine.go
  v1/services/retention/service.go
  v1/services/retention/service_test.go
Labels: area/retention policies, area/2.x, team/edge, area/logging

#26545 chore: improve logging on compaction failures
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
Labels: area/tsm, 1.x, team/edge, area/logging
