Repository influxdata/influxdb, pull requests merged in 2025-09, with the labels that each got.

#26617 chore: backport visibility changes for system tables from PR #1031
  influxdb3_server/src/system_tables/databases.rs
  influxdb3_server/src/system_tables/mod.rs
  influxdb3_server/src/system_tables/tables.rs
Labels: v3

#26787 chore: backport v2 write API error response format fix
  influxdb3/tests/server/write.rs
  influxdb3_server/src/http.rs
Labels: v3

#26831 fix: add locking in ClearBadShardList (#26423)
  tsdb/store.go
Labels: kind/bug, 1.x

#26833 feat: Adds time_format param for httpd (#26596)
  services/httpd/handler.go
  services/httpd/handler_test.go
Labels: area/HTTP, 1.x

#26841 chore: update Cargo.toml to 3.6.0-nightly
  Cargo.lock
  Cargo.toml
Labels: v3

#26848 chore: back-port object-store-request-timeout arg
  influxdb3/src/commands/serve/cli_params.rs
  influxdb3_clap_blocks/src/object_store.rs
Labels: v3

#26851 chore(deps): bump golang.org/x/oauth2 from v0.21.0 to 0.27.0 (#26625)
  go.mod
  go.sum
Labels: security, 1.x

#26853 feat: TagValueIterator holds RLock for too long (#26369) (#26372)
  tsdb/index/tsi1/log_file.go
Labels: kind/bug, 1.x

#26849 chore: back-port --node-id-from-env from enterprise
  influxdb3/src/commands/serve.rs
  influxdb3/src/commands/serve/cli_params.rs
  influxdb3/tests/cli/mod.rs
Labels: v3

#26860 feat: Adds 'config' to 'debug/vars' http endpoint (#26624)
  cmd/influxd/run/server.go
  monitor/build_info_test.go
  monitor/go_runtime_test.go
  monitor/network_test.go
  monitor/service.go
  monitor/service_test.go
  monitor/system_test.go
  services/httpd/handler.go
  tsdb/config.go
Labels: area/HTTP, 1.x

#26864 chore: update CHANGELOG link (#26777)
  CHANGELOG.md
Labels: area/documentation, kind/bug, 1.x
