Repository influxdata/influxdb, pull requests merged in 2025-04, with the labels that each got.

#26206 chore: back-port changes to shutdown code from enterprise
  influxdb3/tests/cli/mod.rs
  influxdb3_shutdown/src/lib.rs
  influxdb3_wal/src/object_store.rs
Labels: v3

#26214 refactor: split existence check to two method in Repository
  influxdb3_catalog/src/catalog.rs
Labels: v3

#26220 fix: rename influxdb3 to influxdb3-core when building packages
  .circleci/packages/config.yaml
Labels: v3

#26223 fix: empty writes do not corrupt wal
  influxdb3_server/src/http.rs
  influxdb3_write/src/write_buffer/mod.rs
Labels: v3

#26234 chore: update tokio to 1.43.1 for RUSTSEC
  Cargo.lock
  Cargo.toml
Labels: v3

#26233 test: check error behaviour on create table api
  influxdb3/tests/server/configure.rs
Labels: v3

#26211 fix: PlanOptimize is running too frequently
  cmd/influx_tools/compact/command.go
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
Labels: area/tsm, kind/bug, team/edge

#26238 fix: PlanOptimize is running too frequently (#26211)
  cmd/influx_tools/compact/command.go
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
Labels: area/tsm, kind/bug, 1.x

#26241 feat: catalog updates state to stopped on shutdown
  Cargo.lock
  influxdb3/src/commands/serve.rs
  influxdb3_catalog/Cargo.toml
  influxdb3_catalog/src/catalog.rs
  influxdb3_catalog/src/catalog/update.rs
  influxdb3_catalog/src/log/versions/v2.rs
Labels: v3

#26245 fix(install_influxdb.sh): use 'shasum -a 256' on OSX
  install_influxdb.sh
Labels: v3

#26248 fix: build after some merge regressions
  influxdb3/src/commands/delete.rs
  influxdb3/tests/cli/mod.rs
  influxdb3/tests/server/configure.rs
Labels: v3

#26251 feat: catalog metrics retry counter
  Cargo.lock
  influxdb3/src/commands/serve.rs
  influxdb3_cache/src/last_cache/mod.rs
  influxdb3_cache/src/test_helpers.rs
  influxdb3_catalog/Cargo.toml
  influxdb3_catalog/src/catalog.rs
  influxdb3_catalog/src/catalog/metrics.rs
  influxdb3_catalog/src/catalog/update.rs
  influxdb3_processing_engine/src/lib.rs
  influxdb3_processing_engine/src/plugins.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor/mod.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
  influxdb3_write/src/write_buffer/table_buffer.rs
  influxdb3_write/src/write_buffer/validator.rs
Labels: v3

#26265 chore: back-port changes from enterprise
  influxdb3_catalog/src/log/versions/v2.rs
  influxdb3_processing_engine/src/lib.rs
  influxdb3_processing_engine/src/plugins.rs
Labels: v3

#26266 docs: fix typos in help text
  influxdb3/src/help/serve.txt
  influxdb3/src/help/serve_all.txt
Labels: v3

#26268 chore: version bump to release 3.0
  Cargo.lock
  Cargo.toml
Labels: v3

#26278 chore: back-port catalog limit refactor from enterprise
  influxdb3/tests/cli/api.rs
  influxdb3_catalog/src/catalog.rs
  influxdb3_catalog/src/catalog/update.rs
  influxdb3_catalog/src/error.rs
  influxdb3_server/src/http.rs
Labels: v3

#26279 fix: Modify package publishing to fix slack msg & publish_packages
  .circleci/config.yml
Labels: 1.x, area/build

#26257 feat: improve dropped point logging
  coordinator/points_writer.go
  coordinator/points_writer_test.go
Labels: area/writes, kind/enhancement, 1.x, area/2.x, team/edge

#26302 fix: Ensure `iox` table schema is sorted for SHOW TABLES
  influxdb3/tests/cli/api.rs
  influxdb3/tests/server/mod.rs
  influxdb3/tests/server/query.rs
  influxdb3/tests/server/snapshots/lib__server__query__api_v3_query_show_tables_ordering.snap
  influxdb3_server/src/query_executor/mod.rs
Labels: v3

#26324 feat: Add more TLS tests to the test suite
  influxdb3/tests/server/mod.rs
Labels: v3

#26326 fix: group by tag columns with escape quotes
  influxdb3/tests/server/query.rs
  influxdb3_server/src/http/v1.rs
Labels: v3

#26325 feat: improve control of logs on test harness
  influxdb3/src/commands/serve.rs
  influxdb3/tests/server/mod.rs
  influxdb3_server/src/lib.rs
Labels: v3

#26323 chore: back-port changes from influxdb_pro#762
  Cargo.lock
  influxdb3/src/commands/serve.rs
  influxdb3/tests/cli/mod.rs
  influxdb3_catalog/Cargo.toml
  influxdb3_catalog/src/catalog.rs
  influxdb3_catalog/src/catalog/update.rs
  influxdb3_catalog/src/error.rs
  influxdb3_catalog/src/log/versions/v1/conversion.rs
  influxdb3_catalog/src/log/versions/v2.rs
  influxdb3_process/src/lib.rs
  influxdb3_server/src/http.rs
  influxdb3_server/src/lib.rs
  influxdb3_types/Cargo.toml
  influxdb3_types/src/http.rs
Labels: v3

#26332 fix: distinct cache counting bug
  influxdb3_cache/src/distinct_cache/cache.rs
  influxdb3_cache/src/distinct_cache/mod.rs
  influxdb3_catalog/src/catalog.rs
Labels: v3
