Repository influxdata/influxdb, pull requests merged in 2025-05, with the labels that each got.

#26350 chore: version bump to 3.0.2
  Cargo.lock
  Cargo.toml
Labels: v3

#26351 docs: update RELEASE.md for post-GA process
  RELEASE.md
Labels: v3

#26355 chore: update rust toolchain to 1.86.0
  influxdb3_clap_blocks/src/object_store.rs
  influxdb3_server/src/http.rs
  rust-toolchain.toml
Labels: v3

#26303 feat: improve dropped point logging
  tsdb/shard.go
  v1/coordinator/points_writer.go
  v1/coordinator/points_writer_test.go
Labels: area/writes, kind/feature-request, area/2.x, team/edge, area/logging

#26319 fix: limit number of concurrent optimized compactions
  tsdb/config.go
  tsdb/engine.go
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/scheduler.go
  tsdb/store.go
Labels: area/tsm, kind/bug, 1.x

#26357 feat: catalog metrics to count operation types
  influxdb3_catalog/src/catalog.rs
  influxdb3_catalog/src/catalog/metrics.rs
Labels: v3

#26364 docs: add Building from source section to CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: v3

#26365 feat: track object store metrics
  Cargo.lock
  Cargo.toml
  influxdb3/Cargo.toml
  influxdb3/src/commands/serve.rs
Labels: v3

#26374 fix(influxd): update xxhash, avoid stringtoslicebyte in cache
  go.mod
  go.sum
  pkg/bloom/bloom.go
  pkg/estimator/hll/hll.go
  pkg/rhh/rhh.go
  task/backend/scheduler/treescheduler.go
  tsdb/engine/tsm1/cache.go
  tsdb/engine/tsm1/cache_test.go
  tsdb/engine/tsm1/ring.go
  tsdb/engine/tsm1/ring_test.go
  tsdb/index/tsi1/index.go
  tsdb/series_file.go
Labels: area/tsm, kind/enhancement, area/2.x, team/edge

#26389 fix: avoid panic if shard group has no shards (#25717)
  v1/coordinator/points_writer.go
Labels: area/writes, kind/bug, team/edge

#26392 fix: move aside TSM file on errBlockRead (#25899)
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/reader_test.go
Labels: area/tsm, kind/bug, area/2.x, team/edge

#26393 fix: defer calls that return a closure need to be called (#25951)
  cmd/influxd/inspect/type_conflicts/schema.go
  sqlite/sqlite.go
Labels: kind/bug, area/2.x, team/edge

#26391 fix: do not leak file handles from Compactor.write (#25725) (#25740)
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/writer.go
Labels: area/tsm, kind/bug, team/edge

#26400 feat: Add error join for file writing in snapshots (#26004) (#26005)
  tsdb/engine/tsm1/compact.go
Labels: area/tsm, kind/bug, area/2.x, team/edge

#26403 fix: prevent differing field types in the same shard (#26025)
  pkg/data/gensyncmap/gensyncmap.go
  tsdb/engine/tsm1/engine.go
  tsdb/field_validator.go
  tsdb/shard.go
  tsdb/shard_test.go
Labels: area/2.x, team/edge

#26401 refactor: use truncate in lvc to ensure elements removed
  influxdb3_cache/src/last_cache/cache.rs
Labels: v3

#26407 fix: ensure temp files removed on failed compaction (#26070) (#26071)
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/engine.go
Labels: area/tsm, kind/bug, area/2.x, team/edge

#26408 fix: remove temp files on error in Compactor.writeNewFiles (#26074) (…
  tsdb/engine/tsm1/compact.go
Labels: area/tsm, kind/bug, area/2.x, team/edge

#26402 fix: ensure fields in memory match on disk
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
  tsdb/field_validator.go
  tsdb/shard.go
  tsdb/shard_test.go
Labels: area/tsm, kind/bug, area/2.x, team/edge

#26409 chore: add logging to Filestore.purger (#26089) (#26103)
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
Labels: area/tsm, area/tests, area/2.x, team/edge

#26410 chore: upgrade to influxdata/influxql v1.2.0 (#24764) (#26155)
  go.mod
  go.sum
  influxql/query/compile_test.go
  v1/services/storage/predicate_test.go
Labels: area/influxql, kind/bug, area/2.x, team/edge

#26411 fix: do not panic on invalid multiple subqueries (#26143) (#26162)
  influxql/query/select.go
  influxql/query/select_test.go
Labels: area/queries, area/influxql, kind/bug, area/2.x, team/edge

#26412 feat: improve dropped point logging (#26303)
  tsdb/shard.go
  v1/coordinator/points_writer.go
  v1/coordinator/points_writer_test.go
Labels: area/writes, kind/feature-request, area/2.x, team/edge

#26388 feat: query duration metrics in lvc
  influxdb3_cache/src/last_cache/metrics.rs
  influxdb3_cache/src/last_cache/mod.rs
  influxdb3_cache/src/last_cache/provider.rs
  influxdb3_cache/src/last_cache/table_function.rs
  influxdb3_catalog/src/catalog.rs
Labels: v3

#26416 chore: use github.com/golang-jwt/jwt/v4 and update golang.org/x/net to v0.38.0
  go.mod
  go.sum
  jsonweb/token.go
  jsonweb/token_test.go
Labels: area/2.x, team/edge

#26415 chore: update UI to OSS-v2.7.12
  scripts/fetch-ui-assets.sh
Labels: area/ui, area/2.x, team/edge

#26419 chore: update UI to OSS-v2.7.12
  scripts/fetch-ui-assets.sh
Labels: area/ui, area/2.x, team/edge

#26421 chore: update Cargo.toml version to 3.0.3
  Cargo.lock
  Cargo.toml
Labels: v3

#26427 docs: update release.md with additional details
  RELEASE.md
Labels: v3

#26443 refactor: remove variants for unused series key type
  Cargo.toml
  influxdb3_cache/src/distinct_cache/cache.rs
  influxdb3_cache/src/last_cache/cache.rs
  influxdb3_py_api/src/system_py.rs
  influxdb3_wal/src/lib.rs
  influxdb3_write/src/write_buffer/table_buffer.rs
Labels: v3

#26446 fix: backfill new tags with NULL instead of empty string
  influxdb3/tests/cli/mod.rs
  influxdb3/tests/server/snapshots/lib__server__query__api_v1_query_group_by_with_nulls-2.snap
  influxdb3/tests/server/snapshots/lib__server__query__api_v1_query_group_by_with_nulls.snap
  influxdb3_server/src/http/v1.rs
  influxdb3_write/src/write_buffer/table_buffer.rs
Labels: v3

#26447 docs: add rust docs to catalog types
  influxdb3_catalog/src/catalog.rs
Labels: v3

#26448 test: reproduce problem with NULL backfill of omitted tag cols
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/table_buffer.rs
Labels: v3

#26453 fix: add key variant back to wal to fix bitcode deserialization
  influxdb3_cache/src/distinct_cache/cache.rs
  influxdb3_cache/src/last_cache/cache.rs
  influxdb3_py_api/src/system_py.rs
  influxdb3_wal/src/lib.rs
  influxdb3_write/src/write_buffer/table_buffer.rs
Labels: v3

#26461 fix: use correct ENV vars in Dockerfile
  Dockerfile
Labels: v3

#26429 chore: update to latest influxdb3_core
  Cargo.lock
  Cargo.toml
  deny.toml
  influxdb3/src/commands/serve.rs
  influxdb3/tests/cli/snapshots/lib__cli__summary_should_show_up_to_ten_entries_from_each_table.snap
  influxdb3/tests/server/flight.rs
  influxdb3/tests/server/mod.rs
  influxdb3/tests/server/snapshots/lib__server__query__api_v3_query_show_tables_ordering.snap
  influxdb3_authz/src/lib.rs
  influxdb3_cache/src/distinct_cache/table_function.rs
  influxdb3_cache/src/last_cache/table_function.rs
  influxdb3_cache/src/parquet_cache/mod.rs
  influxdb3_clap_blocks/Cargo.toml
  influxdb3_clap_blocks/src/datafusion.rs
  influxdb3_clap_blocks/src/object_store.rs
  influxdb3_clap_blocks/src/tokio.rs
  influxdb3_processing_engine/src/lib.rs
  influxdb3_server/Cargo.toml
  influxdb3_server/src/http.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor/mod.rs
  influxdb3_server/src/query_planner.rs
  influxdb3_test_helpers/src/object_store/mod.rs
  influxdb3_write/Cargo.toml
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
Labels: v3

#26466 refactor: move jemalloc to `influxdb3 serve` and address workspace lints
  Cargo.lock
  influxdb3/Cargo.toml
  influxdb3/src/commands/common.rs
  influxdb3/src/commands/create/token.rs
  influxdb3/src/commands/helpers.rs
  influxdb3/src/commands/query.rs
  influxdb3/src/commands/serve.rs
  influxdb3/src/commands/serve/jemalloc.rs
  influxdb3/src/commands/show/system.rs
  influxdb3/tests/cli/api.rs
  influxdb3/tests/server/mod.rs
  influxdb3_id/Cargo.toml
  influxdb3_id/src/lib.rs
  influxdb3_process/Cargo.toml
  influxdb3_process/src/lib.rs
Labels: v3

#26467 chore: add workspace lints to influxd3_authz crate
  influxdb3_authz/Cargo.toml
  influxdb3_authz/src/lib.rs
Labels: v3

#26471 chore: update version to 3.1.0
  Cargo.lock
  Cargo.toml
Labels: v3

#26472 chore: update to version 3.2.0-nightly on main
  Cargo.lock
  Cargo.toml
Labels: v3

#26476 docs: minor release docs
  RELEASE.md
Labels: v3

#25180 fix: fix compilation on alpine linux
  go.mod
  go.sum
  scripts/ci/test-downgrade.sh
  scripts/fetch-ui-assets.sh
Labels: area/build, team/edge
