Repository influxdata/influxdb, pull requests merged in 2025-08, with the labels that each got.

#26649 fix: correct locking bug when deleting a series
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
Labels: area/tsm, kind/bug, 1.x

#26659 chore: add trace logging to compaction scheduler
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/scheduler.go
Labels: 1.x

#26658 fix: correct locking bug when deleting a series
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
Labels: area/tsm, kind/bug, 1.x

#26661 chore: add trace debug logging to DefaultCompactionPlanner
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/engine_test.go
Labels: area/tsm, kind/bug, 1.x

#26668 fix: full compactions not scheduled under some circumstances
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/engine.go
Labels: area/tsm, kind/bug, 1.x, team/edge

#26687 feat: Add --azure-endpoint argument to the CLI
  influxdb3/src/help/serve_all.txt
  influxdb3_clap_blocks/src/object_store.rs
Labels: v3

#26372 feat: TagValueIterator holds RLock for too long (#26369)
  tsdb/index/tsi1/log_file.go
Labels: 1.x

#26624 feat: Adds 'config' to 'debug/vars' http endpoint
  cmd/influxd/run/server.go
  monitor/build_info_test.go
  monitor/go_runtime_test.go
  monitor/network_test.go
  monitor/service.go
  monitor/service_test.go
  monitor/system_test.go
  services/httpd/handler.go
  tsdb/config.go
Labels: 1.x

#26699 fix(packaging): init.sh should run buildtsi as influxdb user
  .circleci/packages/influxdb/fs/usr/lib/influxdb/scripts/init.sh
Labels: 1.x

#26485 test: reproducer for tags with slashes break primary key
  influxdb3_write/src/lib.rs
Labels: v3

#26714 chore(cli): hide the token's env var value in cli help
  influxdb3/src/commands/common.rs
  influxdb3/src/commands/create.rs
  influxdb3/src/commands/create/token.rs
  influxdb3/src/commands/delete.rs
  influxdb3/src/commands/install.rs
  influxdb3/src/commands/show.rs
  influxdb3_load_generator/src/commands/common.rs
  influxdb3_load_generator/src/commands/write_fixed.rs
Labels: v3

#26716 fix(wal_replay): limit the number of wal files preloaded to num_cpus
  Cargo.lock
  influxdb3/src/commands/serve.rs
  influxdb3/src/help/serve_all.txt
  influxdb3/src/lib.rs
  influxdb3_processing_engine/src/lib.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor/mod.rs
  influxdb3_server/tests/lib.rs
  influxdb3_wal/Cargo.toml
  influxdb3_wal/src/object_store.rs
  influxdb3_write/src/write_buffer/mod.rs
Labels: v3

#26756 chore: cherry pick `b85f938f7c` and `3e7f7d5ac3`
  influxdb3_catalog/src/catalog/migrations/v2.rs
  influxdb3_server/src/http.rs
  influxdb3_server/src/lib.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/validator.rs
Labels: v3

#26762 fix: reduce unnecessary purger operations and logging
  tsdb/engine/tsm1/file_store.go
Labels: area/tsm, kind/enhancement, 1.x, kind/perf, team/edge
