Repository influxdata/influxdb, pull requests merged in 2025-03, with the labels that each got.

#26088 feat: improve CLI list arg consistency (always use commas)
  influxdb3/src/commands/common.rs
  influxdb3/src/commands/create.rs
  influxdb3/src/commands/plugin_test/wal.rs
  influxdb3/src/commands/test.rs
  influxdb3/tests/cli/mod.rs
Labels: v3

#26089 chore: add logging to Filestore.purger
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
Labels: area/tsm, area/tests, 1.x, team/edge, area/logging

#26103 chore: add logging to Filestore.purger (#26089)
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/file_store.go
Labels: area/tsm, kind/enhancement, area/tests, team/edge, area/logging

#26108 feat: allow new tags in schema again
  Cargo.lock
  Cargo.toml
  influxdb3_cache/src/test_helpers.rs
  influxdb3_catalog/src/catalog.rs
  influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__catalog_serialization.snap
  influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_distinct_cache.snap
  influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_last_cache.snap
  influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_series_keys.snap
  influxdb3_processing_engine/src/plugins.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-after-last-cache-create-and-new-field.snap
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-create.snap
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-delete.snap
  influxdb3_write/src/write_buffer/table_buffer.rs
  influxdb3_write/src/write_buffer/validator.rs
  rust-toolchain.toml
Labels: v3

#26115 chore: disable release on merge to main for beta
  .circleci/config.yml
Labels: v3

#26126 feat: catalog checkpoints
  Cargo.lock
  influxdb3/tests/cli/snapshots/lib__cli__distinct_cache_create_and_delete.snap.new
  influxdb3_catalog/Cargo.toml
  influxdb3_catalog/src/catalog.rs
  influxdb3_catalog/src/catalog/update.rs
  influxdb3_catalog/src/object_store.rs
  influxdb3_catalog/src/serialize.rs
  influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__catalog_file_ordering.snap
  influxdb3_write/src/write_buffer/mod.rs
Labels: v3

#26129 fix: off-by-one in catalog update logic
  influxdb3_catalog/src/catalog/update.rs
Labels: v3

#26128 chore: back-port catalog debug log cleanup from enterprise
  influxdb3/src/commands/serve.rs
  influxdb3_catalog/src/catalog.rs
  influxdb3_catalog/src/catalog/update.rs
  influxdb3_catalog/src/log.rs
  influxdb3_catalog/src/object_store.rs
  influxdb3_catalog/src/snapshot.rs
  influxdb3_wal/src/object_store.rs
  influxdb3_wal/src/snapshot_tracker.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/write_buffer/validator.rs
Labels: v3

#26135 refactor: use repositories in catalog
  Cargo.lock
  influxdb3_cache/src/distinct_cache/cache.rs
  influxdb3_cache/src/distinct_cache/mod.rs
  influxdb3_cache/src/distinct_cache/provider.rs
  influxdb3_cache/src/distinct_cache/table_function.rs
  influxdb3_cache/src/last_cache/cache.rs
  influxdb3_cache/src/last_cache/mod.rs
  influxdb3_cache/src/last_cache/provider.rs
  influxdb3_cache/src/last_cache/snapshots/influxdb3_cache__last_cache__tests__catalog_initialization.snap
  influxdb3_cache/src/last_cache/table_function.rs
  influxdb3_cache/src/test_helpers.rs
  influxdb3_catalog/src/catalog.rs
  influxdb3_catalog/src/catalog/update.rs
  influxdb3_catalog/src/id.rs
  influxdb3_catalog/src/lib.rs
  influxdb3_catalog/src/log.rs
  influxdb3_catalog/src/log/create.rs
  influxdb3_catalog/src/object_store.rs
  influxdb3_catalog/src/resource.rs
  influxdb3_catalog/src/snapshot.rs
  influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__catalog_file_ordering.snap
  influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__catalog_serialization.snap
  influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_distinct_cache.snap
  influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_last_cache.snap
  influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_series_keys.snap
  influxdb3_client/src/lib.rs
  influxdb3_id/src/lib.rs
  influxdb3_id/src/serialize.rs
  influxdb3_processing_engine/Cargo.toml
  influxdb3_processing_engine/src/lib.rs
  influxdb3_processing_engine/src/plugins.rs
  influxdb3_py_api/src/system_py.rs
  influxdb3_server/src/system_tables/distinct_caches.rs
  influxdb3_server/src/system_tables/last_caches.rs
  influxdb3_server/src/system_tables/mod.rs
  influxdb3_server/src/system_tables/python_call.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-after-last-cache-create-and-new-field.snap
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-create.snap
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-delete.snap
  influxdb3_write/src/write_buffer/table_buffer.rs
Labels: v3

#26125 feat(python): update to python-build-standalone 3.13.2
  .circleci/config.yml
  .circleci/scripts/fetch-python-standalone.bash
  influxdb3_catalog/src/catalog.rs
  influxdb3_processing_engine/src/plugins.rs
  influxdb3_processing_engine/src/virtualenv.rs
  influxdb3_write/src/write_buffer/mod.rs
Labels: v3

#26143 fix: do not panic on invalid multiple subqueries
  query/select.go
  query/select_test.go
Labels: area/queries, area/influxql, kind/bug, team/edge

#26144 chore: re-enable release on merge to main
  .circleci/config.yml
Labels: v3

#26118 feat: ack catalog update broadcast
  influxdb3/src/commands/serve.rs
  influxdb3_cache/src/distinct_cache/mod.rs
  influxdb3_cache/src/distinct_cache/provider.rs
  influxdb3_cache/src/last_cache/mod.rs
  influxdb3_cache/src/last_cache/provider.rs
  influxdb3_catalog/src/catalog.rs
  influxdb3_catalog/src/catalog/update.rs
  influxdb3_catalog/src/channel.rs
  influxdb3_catalog/src/error.rs
  influxdb3_catalog/src/lib.rs
  influxdb3_processing_engine/src/lib.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor/mod.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
Labels: v3

#26158 chore: cleanup token create CLI message
  influxdb3/src/commands/create.rs
Labels: v3

#26183 feat: version 2 catalog serialization
  influxdb3_catalog/src/log.rs
  influxdb3_catalog/src/log/create.rs
  influxdb3_catalog/src/log/versions/mod.rs
  influxdb3_catalog/src/log/versions/v1.rs
  influxdb3_catalog/src/log/versions/v1/conversion.rs
  influxdb3_catalog/src/log/versions/v2.rs
  influxdb3_catalog/src/serialize.rs
  influxdb3_catalog/src/snapshot.rs
  influxdb3_catalog/src/snapshot/versions/mod.rs
  influxdb3_catalog/src/snapshot/versions/v1.rs
  influxdb3_catalog/src/snapshot/versions/v1/conversion.rs
  influxdb3_catalog/src/snapshot/versions/v2.rs
Labels: v3

#26190 chore(ci): push artifiacts to public bucket
  .circleci/config.yml
Labels: 1.x, kind/tech-debt

#26191 chore(ci): push artifiacts to public bucket
  .circleci/config.yml
Labels: 1.x, kind/tech-debt

#26194 chore: cleanup tracing from cache crate
  influxdb3_cache/src/parquet_cache/mod.rs
Labels: v3

#26197 feat: handle graceful shutdown
  Cargo.lock
  Cargo.toml
  influxdb3/Cargo.toml
  influxdb3/src/commands/serve.rs
  influxdb3_processing_engine/Cargo.toml
  influxdb3_processing_engine/src/lib.rs
  influxdb3_server/Cargo.toml
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor/mod.rs
  influxdb3_shutdown/Cargo.toml
  influxdb3_shutdown/src/lib.rs
  influxdb3_wal/Cargo.toml
  influxdb3_wal/src/lib.rs
  influxdb3_wal/src/object_store.rs
  influxdb3_write/Cargo.toml
  influxdb3_write/src/write_buffer/mod.rs
Labels: v3

#26203 feat: shutdown on WAL overwritten
  influxdb3/tests/cli/mod.rs
  influxdb3/tests/server/mod.rs
  influxdb3_wal/src/object_store.rs
Labels: v3

#26205 fix: additional check on frontend shutdown
  influxdb3/src/commands/serve.rs
Labels: v3
