Repository influxdata/influxdb, pull requests merged in 2025-01, with the labels that each got.

#25725 fix: do not leak file handles from Compactor.write
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/writer.go
Labels: area/tsm, kind/bug, team/edge

#25740 fix: do not leak file handles from Compactor.write (#25725)
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/writer.go
Labels: area/tsm, kind/bug, team/edge

#25754 feat: table creation also creates db if it does not exist
  influxdb3_write/src/write_buffer/mod.rs
Labels: v3

#25748 feat: show databases CLI/API
  influxdb3/src/commands/show.rs
  influxdb3/src/main.rs
  influxdb3/tests/server/cli.rs
  influxdb3/tests/server/configure.rs
  influxdb3/tests/server/query.rs
  influxdb3_catalog/src/catalog.rs
  influxdb3_client/src/lib.rs
  influxdb3_server/src/http.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor/mod.rs
Labels: v3

#25761 test: do not pass TEST_LOG to log filter in e2e tests
  influxdb3/tests/server/main.rs
Labels: v3

#25762 feat: handle params in request body for `/query` API
  Cargo.lock
  influxdb3/Cargo.toml
  influxdb3/tests/server/query.rs
  influxdb3_server/src/http.rs
  influxdb3_server/src/http/v1.rs
Labels: v3

#25769 fix: `/query` API emits empty result as JSON
  influxdb3/tests/server/query.rs
  influxdb3_server/src/http/v1.rs
Labels: v3

#25776 chore: patch changes from enterprise
  influxdb3_clap_blocks/src/datafusion.rs
  influxdb3_write/src/persister.rs
Labels: v3

#25780 chore: add helix config dir to gitignore
  .gitignore
Labels: v3

#25775 refactor: rename metadata cache to distinct value cache
  influxdb3/src/commands/create.rs
  influxdb3/src/commands/delete.rs
  influxdb3/src/commands/serve.rs
  influxdb3/tests/server/cli.rs
  influxdb3/tests/server/configure.rs
  influxdb3/tests/server/flight.rs
  influxdb3/tests/server/main.rs
  influxdb3/tests/server/query.rs
  influxdb3/tests/server/snapshots/server__cli__distinct_cache_create_and_delete-2.snap
  influxdb3/tests/server/snapshots/server__cli__distinct_cache_create_and_delete.snap
  influxdb3/tests/server/system_tables.rs
  influxdb3_cache/src/distinct_cache/cache.rs
  influxdb3_cache/src/distinct_cache/mod.rs
  influxdb3_cache/src/distinct_cache/provider.rs
  influxdb3_cache/src/distinct_cache/table_function.rs
  influxdb3_cache/src/lib.rs
  influxdb3_catalog/src/catalog.rs
  influxdb3_client/src/lib.rs
  influxdb3_processing_engine/src/lib.rs
  influxdb3_server/src/http.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor/mod.rs
  influxdb3_server/src/system_tables/distinct_caches.rs
  influxdb3_server/src/system_tables/mod.rs
  influxdb3_wal/src/lib.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
Labels: v3

#25798 chore: patch enterprise back to core
  Cargo.lock
  deny.toml
  influxdb3_cache/src/distinct_cache/cache.rs
  influxdb3_catalog/Cargo.toml
  influxdb3_clap_blocks/src/datafusion.rs
  influxdb3_client/src/lib.rs
  influxdb3_internal_api/src/query_executor.rs
  influxdb3_server/src/http.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor/mod.rs
  influxdb3_telemetry/src/sampler.rs
  influxdb3_telemetry/src/store.rs
  influxdb3_wal/src/create.rs
  influxdb3_wal/src/lib.rs
  influxdb3_wal/src/object_store.rs
  influxdb3_write/Cargo.toml
  influxdb3_write/src/chunk.rs
  influxdb3_write/src/lib.rs
  rust-toolchain.toml
Labels: v3

#25808 fix: package signing artifact names to use core not edge
  .circleci/packages/config.yaml
Labels: v3

#25804 refactor: change host-id to writer-id
  influxdb3/src/commands/create.rs
  influxdb3/src/commands/serve.rs
  influxdb3/src/main.rs
  influxdb3/tests/server/main.rs
  influxdb3_cache/src/last_cache/mod.rs
  influxdb3_catalog/src/catalog.rs
  influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__catalog_serialization.snap
  influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_last_cache.snap
  influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_series_keys.snap
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor/mod.rs
  influxdb3_wal/src/object_store.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/persister.rs
  influxdb3_write/src/snapshots/influxdb3_write__persister__tests__persisted_snapshot_structure.snap
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-after-last-cache-create-and-new-field.snap
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-create.snap
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-delete.snap
  influxdb3_write/src/write_buffer/validator.rs
Labels: v3

#25837 docs: update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: v3

#25845 feat: support v1 query API GROUP BY semantics
  Cargo.lock
  Cargo.toml
  influxdb3/tests/server/query.rs
  influxdb3/tests/server/snapshots/server__query__api_v1_query_group_by-10.snap
  influxdb3/tests/server/snapshots/server__query__api_v1_query_group_by-11.snap
  influxdb3/tests/server/snapshots/server__query__api_v1_query_group_by-12.snap
  influxdb3/tests/server/snapshots/server__query__api_v1_query_group_by-13.snap
  influxdb3/tests/server/snapshots/server__query__api_v1_query_group_by-14.snap
  influxdb3/tests/server/snapshots/server__query__api_v1_query_group_by-15.snap
  influxdb3/tests/server/snapshots/server__query__api_v1_query_group_by-16.snap
  influxdb3/tests/server/snapshots/server__query__api_v1_query_group_by-2.snap
  influxdb3/tests/server/snapshots/server__query__api_v1_query_group_by-3.snap
  influxdb3/tests/server/snapshots/server__query__api_v1_query_group_by-4.snap
  influxdb3/tests/server/snapshots/server__query__api_v1_query_group_by-5.snap
  influxdb3/tests/server/snapshots/server__query__api_v1_query_group_by-6.snap
  influxdb3/tests/server/snapshots/server__query__api_v1_query_group_by-7.snap
  influxdb3/tests/server/snapshots/server__query__api_v1_query_group_by-8.snap
  influxdb3/tests/server/snapshots/server__query__api_v1_query_group_by-9.snap
  influxdb3/tests/server/snapshots/server__query__api_v1_query_group_by.snap
  influxdb3/tests/server/snapshots/server__query__api_v1_query_group_by_with_nulls-2.snap
  influxdb3/tests/server/snapshots/server__query__api_v1_query_group_by_with_nulls.snap
  influxdb3_internal_api/Cargo.toml
  influxdb3_internal_api/src/query_executor.rs
  influxdb3_py_api/src/system_py.rs
  influxdb3_server/Cargo.toml
  influxdb3_server/src/http.rs
  influxdb3_server/src/http/v1.rs
  influxdb3_server/src/query_executor/mod.rs
  influxdb3_server/src/query_planner.rs
Labels: v3

#25858 chore: bring back enterprise changes
  Cargo.lock
  influxdb3_internal_api/Cargo.toml
  influxdb3_internal_api/src/query_executor.rs
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor/mod.rs
  influxdb3_server/src/system_tables/mod.rs
Labels: v3

#25866 feat: expr analyzer for buffer to filter table chunks
  influxdb3_write/src/lib.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/persisted_files.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
  influxdb3_write/src/write_buffer/table_buffer.rs
Labels: v3

#25839 fix: move aside TSM file on errBlockRead
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/reader_test.go
Labels: area/tsm, kind/bug, 1.x, team/edge

#25896 refactor: reduce catalog locks when getting chunks
  influxdb3_catalog/src/catalog.rs
  influxdb3_server/src/query_executor/mod.rs
  influxdb3_wal/src/create.rs
  influxdb3_wal/src/lib.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/persister.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/persisted_files.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
  influxdb3_write/src/write_buffer/table_buffer.rs
  influxdb3_write/src/write_buffer/validator.rs
Labels: v3

#25899 fix: move aside TSM file on errBlockRead
  tsdb/engine/tsm1/compact.go
  tsdb/engine/tsm1/compact_test.go
  tsdb/engine/tsm1/engine.go
  tsdb/engine/tsm1/reader_test.go
Labels: area/tsm, kind/bug, area/2.x, team/edge

#25905 refactor: `writer-id` to `node-id`
  influxdb3/src/commands/create.rs
  influxdb3/src/commands/serve.rs
  influxdb3/src/main.rs
  influxdb3/tests/server/cli.rs
  influxdb3/tests/server/main.rs
  influxdb3_cache/src/last_cache/mod.rs
  influxdb3_catalog/src/catalog.rs
  influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__catalog_serialization.snap
  influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_last_cache.snap
  influxdb3_catalog/src/snapshots/influxdb3_catalog__catalog__tests__serialize_series_keys.snap
  influxdb3_server/src/lib.rs
  influxdb3_server/src/query_executor/mod.rs
  influxdb3_wal/src/object_store.rs
  influxdb3_write/src/lib.rs
  influxdb3_write/src/persister.rs
  influxdb3_write/src/snapshots/influxdb3_write__persister__tests__persisted_snapshot_structure.snap
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-after-last-cache-create-and-new-field.snap
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-create.snap
  influxdb3_write/src/write_buffer/snapshots/influxdb3_write__write_buffer__tests__catalog-immediately-after-last-cache-delete.snap
  influxdb3_write/src/write_buffer/validator.rs
  install_influxdb.sh
  install_influxdb3.sh
Labels: v3

#25910 fix: add alias for node_id to writer_id for backward compatibility
  influxdb3_catalog/src/catalog.rs
  influxdb3_write/src/lib.rs
Labels: v3

#25924 fix: last cache with specific value columns can be queried
  influxdb3_cache/src/last_cache/cache.rs
  influxdb3_cache/src/last_cache/mod.rs
Labels: v3

#25949 refactor: remove buffer index and literal guarantee analysus in filter
  Cargo.lock
  influxdb3_write/Cargo.toml
  influxdb3_write/src/lib.rs
  influxdb3_write/src/write_buffer/mod.rs
  influxdb3_write/src/write_buffer/queryable_buffer.rs
  influxdb3_write/src/write_buffer/table_buffer.rs
Labels: v3

#25952 fix: actually call the deferred function
  cmd/influx_inspect/type_conflicts/schema.go
Labels: kind/bug, 1.x, team/edge
